import type { IR, EnumIR } from "../../../ir/types.js";
import { toSnakeCase } from "../../../ir/names.js";
import type { GeneratorConfig } from "../../../types.js";
import type { Backend } from "./backend.js";
import type { ModuleResolver } from "../../type-ref.js";

export interface FilterPusherOpts {
  /** Reserved for future use; currently unused. */
  serde: boolean;
  /**
   * Decimal crate currently in use. `rust_decimal::Decimal` is `Copy`, so its
   * `push_bind` must deref; `bigdecimal::BigDecimal` is not, so it must clone.
   * Defaults to `rust_decimal` when omitted to preserve old call sites.
   */
  decimalCrate?: GeneratorConfig["decimalCrate"];
  /**
   * Layout-aware module resolver for enum types. When omitted, falls back to
   * `e.module` (the source-file stem), which matches per-file layout. The
   * per-model layout passes a resolver that returns `enums::<snake>`.
   */
  moduleOf?: ModuleResolver;
}

/**
 * Scalar families recognized by the pusher emitter. Each family corresponds
 * to a `*Filter` struct emitted by the generator under `crate::shared::filters`.
 */
type ScalarFamily =
  | "uuid"
  | "string"
  | "int"
  | "bigint"
  | "float"
  | "decimal"
  | "datetime"
  | "bool"
  | "bytes"
  | "json";

interface FamilySpec {
  /** snake_case key used in function names (push_<key>_filter). */
  readonly key: ScalarFamily;
  /** PascalCase Rust type name (without the `Filter` suffix). */
  readonly typeName: string;
  /** Whether `<col> <op> $bind` ordering operators (lt/lte/gt/gte) apply. */
  readonly orderable: boolean;
  /** Whether `r#in` / `not_in` set membership applies (json/bool excludes not_in; we still emit `r#in` for bool). */
  readonly hasInList: boolean;
  /** Whether `not_in` is present on the filter. */
  readonly hasNotInList: boolean;
  /** String-only LIKE/ILIKE branches + QueryMode case-insensitive equality. */
  readonly stringOps: boolean;
}

const FAMILIES: readonly FamilySpec[] = [
  { key: "uuid", typeName: "Uuid", orderable: false, hasInList: true, hasNotInList: true, stringOps: false },
  { key: "string", typeName: "String", orderable: true, hasInList: true, hasNotInList: true, stringOps: true },
  { key: "int", typeName: "Int", orderable: true, hasInList: true, hasNotInList: true, stringOps: false },
  { key: "bigint", typeName: "BigInt", orderable: true, hasInList: true, hasNotInList: true, stringOps: false },
  { key: "float", typeName: "Float", orderable: true, hasInList: true, hasNotInList: true, stringOps: false },
  { key: "decimal", typeName: "Decimal", orderable: true, hasInList: true, hasNotInList: true, stringOps: false },
  { key: "datetime", typeName: "DateTime", orderable: true, hasInList: true, hasNotInList: true, stringOps: false },
  { key: "bool", typeName: "Bool", orderable: false, hasInList: true, hasNotInList: false, stringOps: false },
  { key: "bytes", typeName: "Bytes", orderable: false, hasInList: true, hasNotInList: true, stringOps: false },
  { key: "json", typeName: "Json", orderable: false, hasInList: false, hasNotInList: false, stringOps: false },
];

/**
 * Emit the body of `engine/sqlx_postgres/filters.rs`: one `push_<family>_filter`
 * (and `push_<family>_nullable_filter`) function per scalar family, plus one
 * pair per generated enum.
 *
 * Each function takes a `&mut sqlx::QueryBuilder`, a static column name, and a
 * typed filter reference. It walks the filter's `Option<...>` branches and
 * pushes the corresponding parameterized SQL fragment via `push_bind`. The
 * functions return `true` if they emitted any predicate; otherwise they emit
 * `TRUE` inside the parenthesized group so the caller's `AND`-chain stays
 * valid.
 */
const DEFAULT_OPTS: FilterPusherOpts = { serde: true };

export function emitFilterPushers(
  ir: IR,
  backend: Backend,
  opts: FilterPusherOpts = DEFAULT_OPTS,
): string {
  const header = [
    "// @generated by prisma-rust-generator",
    "#![allow(clippy::too_many_lines)]",
    "#![allow(unused_imports)]",
    "",
    "use crate::shared::filters::QueryMode;",
    "use crate::shared::filters;",
    "",
  ];

  const decimalIsCopy = (opts.decimalCrate ?? "rust_decimal") === "rust_decimal";

  // Skip families this backend doesn't support — sqlx-sqlite, for
  // example, has no rust_decimal::Decimal impls so we can't emit a
  // push_decimal_filter against it.
  const supportedFamilies = FAMILIES.filter((spec) =>
    backend.scalarFamilies.has(spec.key),
  );
  const scalarBlocks = supportedFamilies.flatMap((spec) => [
    emitScalarPusher(spec, /* nullable */ false, backend, decimalIsCopy),
    "",
    emitScalarPusher(spec, /* nullable */ true, backend, decimalIsCopy),
    "",
  ]);

  const enumBlocks = ir.enums.flatMap((e) => [
    emitEnumPusher(e, /* nullable */ false, backend, opts.moduleOf),
    "",
    emitEnumPusher(e, /* nullable */ true, backend, opts.moduleOf),
    "",
  ]);

  return [
    ...header,
    ...scalarBlocks,
    ...enumBlocks,
    emitSortOrderHelper(),
    "",
  ].join("\n");
}

/**
 * Emit the `sort_order_sql` helper, which maps a `SortOrder` variant to its
 * SQL fragment (e.g. `ASC NULLS FIRST`). The function is `pub(crate)` because
 * the `find_many` builder in `finds.ts` references it through
 * `crate::engine::sqlx_postgres::filters::sort_order_sql`.
 *
 * Kept here (rather than in finds.ts) so the helper is emitted exactly once
 * per shared module — `finds.ts` is per-model and would otherwise duplicate
 * the function across modules.
 */
function emitSortOrderHelper(): string {
  return [
    `pub(crate) fn sort_order_sql(o: crate::shared::filters::SortOrder) -> &'static str {`,
    `    match o {`,
    `        crate::shared::filters::SortOrder::Asc => "ASC",`,
    `        crate::shared::filters::SortOrder::Desc => "DESC",`,
    `        crate::shared::filters::SortOrder::AscNullsFirst => "ASC NULLS FIRST",`,
    `        crate::shared::filters::SortOrder::AscNullsLast => "ASC NULLS LAST",`,
    `        crate::shared::filters::SortOrder::DescNullsFirst => "DESC NULLS FIRST",`,
    `        crate::shared::filters::SortOrder::DescNullsLast => "DESC NULLS LAST",`,
    `    }`,
    `}`,
  ].join("\n");
}

/**
 * Decide how to bind a value of the given family. UUID-family values are
 * `Copy`, so we deref-copy; everything else is cloned. For Postgres array
 * binding (the `r#in` / `not_in` branches) we always clone the underlying Vec.
 */
function bindSingle(spec: FamilySpec, expr: string, decimalIsCopy: boolean): string {
  // Deref Copy types — `value.clone()` on a Copy type trips `clippy::clone_on_copy`.
  // Copy: uuid::Uuid, primitive ints/floats/bool, chrono::DateTime<Utc> /
  // time::OffsetDateTime, and rust_decimal::Decimal. Not Copy:
  // String, Vec<u8>/bytes::Bytes, serde_json::Value, bigdecimal::BigDecimal.
  if (
    spec.key === "uuid" ||
    spec.key === "int" ||
    spec.key === "bigint" ||
    spec.key === "float" ||
    spec.key === "bool" ||
    spec.key === "datetime"
  ) {
    return `*${expr}`;
  }
  if (spec.key === "decimal" && decimalIsCopy) {
    return `*${expr}`;
  }
  return `${expr}.clone()`;
}

/**
 * Emit the `r#in` branch for a scalar pusher. The shape of the SQL fragment
 * depends on the backend's `arrayIn` mode:
 *   - "ANY"     — Postgres: bind the whole Vec as an array via `= ANY($1)`.
 *   - "IN_LIST" — SQLite: expand to `IN (?, ?, ?)` with one placeholder per
 *                 element via `QueryBuilder::separated`. Empty list short-
 *                 circuits to `FALSE` to keep the AND-chain valid.
 */
function emitInListBranch(spec: FamilySpec, backend: Backend, decimalIsCopy: boolean): string[] {
  if (backend.arrayIn === "ANY") {
    return [
      `    if let Some(values) = &f.r#in {`,
      `        if any { qb.push(" AND "); }`,
      `        any = true;`,
      `        if values.is_empty() {`,
      `            qb.push("FALSE");`,
      `        } else {`,
      `            qb.push(format!("{col} = ANY("));`,
      `            qb.push_bind(values.clone());`,
      `            qb.push(")");`,
      `        }`,
      `    }`,
    ];
  }
  // backend.arrayIn === "IN_LIST" — SQLite: one placeholder per element.
  return [
    `    if let Some(values) = &f.r#in {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        if values.is_empty() {`,
    `            qb.push("FALSE");`,
    `        } else {`,
    `            qb.push(format!("{col} IN ("));`,
    `            let mut sep = qb.separated(", ");`,
    `            for v in values {`,
    `                sep.push_bind(${bindSingle(spec, "v", decimalIsCopy)});`,
    `            }`,
    `            qb.push(")");`,
    `        }`,
    `    }`,
  ];
}

/**
 * Emit the `not_in` branch for a scalar pusher. Mirror of `emitInListBranch`
 * for negative membership.
 */
function emitNotInListBranch(spec: FamilySpec, backend: Backend, decimalIsCopy: boolean): string[] {
  if (backend.arrayIn === "ANY") {
    return [
      `    if let Some(values) = &f.not_in {`,
      `        if !values.is_empty() {`,
      `            if any { qb.push(" AND "); }`,
      `            any = true;`,
      `            qb.push(format!("{col} <> ALL("));`,
      `            qb.push_bind(values.clone());`,
      `            qb.push(")");`,
      `        }`,
      `    }`,
    ];
  }
  // backend.arrayIn === "IN_LIST" — SQLite: `NOT IN (?, ?, ?)`. Empty list is
  // a no-op (mirrors the Postgres behavior: not_in over an empty set matches
  // every row, which is the same as adding no predicate at all).
  return [
    `    if let Some(values) = &f.not_in {`,
    `        if !values.is_empty() {`,
    `            if any { qb.push(" AND "); }`,
    `            any = true;`,
    `            qb.push(format!("{col} NOT IN ("));`,
    `            let mut sep = qb.separated(", ");`,
    `            for v in values {`,
    `                sep.push_bind(${bindSingle(spec, "v", decimalIsCopy)});`,
    `            }`,
    `            qb.push(")");`,
    `        }`,
    `    }`,
  ];
}

/**
 * Emit the case-insensitive-LIKE setup lines that scalar string pushers use
 * to decide between `ILIKE` (Postgres) and `LOWER(col) LIKE LOWER(?)` (SQLite).
 * Under LOWER_LIKE there is no `like_op` shortcut — every site that consumes
 * the case-insensitive flag must wrap its operands in `LOWER()` directly, so
 * only the `ci` flag is emitted here.
 */
function emitStringOpsHeader(backend: Backend): string[] {
  if (backend.caseInsensitiveLike === "ILIKE") {
    return [
      `    let ci = matches!(f.mode, Some(QueryMode::Insensitive));`,
      `    let like_op = if ci { "ILIKE" } else { "LIKE" };`,
    ];
  }
  // backend.caseInsensitiveLike === "LOWER_LIKE" — SQLite has no ILIKE; we
  // wrap column and parameter in LOWER() at every case-insensitive site.
  return [
    `    let ci = matches!(f.mode, Some(QueryMode::Insensitive));`,
  ];
}

/**
 * Emit the case-insensitive equality branch for the string pusher. Both
 * Postgres and SQLite emit the same `LOWER(col) = LOWER(?)` shape for the
 * insensitive arm — Postgres reuses ILIKE elsewhere but equality has always
 * been LOWER-wrapped to avoid the LIKE-pattern escaping concern. The
 * sensitive arm is identical across backends.
 */
function emitStringEqualsBranch(_backend: Backend): string[] {
  return [
    `    if let Some(value) = &f.equals {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        if ci {`,
    `            qb.push(format!("LOWER({col}) = LOWER("));`,
    `            qb.push_bind(value.clone());`,
    `            qb.push(")");`,
    `        } else {`,
    `            qb.push(format!("{col} = "));`,
    `            qb.push_bind(value.clone());`,
    `        }`,
    `    }`,
  ];
}

/**
 * Emit the contains / starts_with / ends_with branches for the string pusher.
 *   - Postgres: uses the precomputed `like_op` variable (`LIKE` / `ILIKE`).
 *   - SQLite:   wraps both `col` and the bound value in `LOWER()` when `ci`
 *               is true; otherwise emits a plain `LIKE`.
 */
function emitStringLikeBranches(backend: Backend): string[] {
  if (backend.caseInsensitiveLike === "ILIKE") {
    return [
      `    if let Some(value) = &f.contains {`,
      `        if any { qb.push(" AND "); }`,
      `        any = true;`,
      `        qb.push(format!("{col} {like_op} "));`,
      `        qb.push_bind(format!("%{value}%"));`,
      `    }`,
      `    if let Some(value) = &f.starts_with {`,
      `        if any { qb.push(" AND "); }`,
      `        any = true;`,
      `        qb.push(format!("{col} {like_op} "));`,
      `        qb.push_bind(format!("{value}%"));`,
      `    }`,
      `    if let Some(value) = &f.ends_with {`,
      `        if any { qb.push(" AND "); }`,
      `        any = true;`,
      `        qb.push(format!("{col} {like_op} "));`,
      `        qb.push_bind(format!("%{value}"));`,
      `    }`,
    ];
  }
  // backend.caseInsensitiveLike === "LOWER_LIKE" — SQLite path.
  return [
    `    if let Some(value) = &f.contains {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        if ci {`,
    `            qb.push(format!("LOWER({col}) LIKE LOWER("));`,
    `            qb.push_bind(format!("%{value}%"));`,
    `            qb.push(")");`,
    `        } else {`,
    `            qb.push(format!("{col} LIKE "));`,
    `            qb.push_bind(format!("%{value}%"));`,
    `        }`,
    `    }`,
    `    if let Some(value) = &f.starts_with {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        if ci {`,
    `            qb.push(format!("LOWER({col}) LIKE LOWER("));`,
    `            qb.push_bind(format!("{value}%"));`,
    `            qb.push(")");`,
    `        } else {`,
    `            qb.push(format!("{col} LIKE "));`,
    `            qb.push_bind(format!("{value}%"));`,
    `        }`,
    `    }`,
    `    if let Some(value) = &f.ends_with {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        if ci {`,
    `            qb.push(format!("LOWER({col}) LIKE LOWER("));`,
    `            qb.push_bind(format!("%{value}"));`,
    `            qb.push(")");`,
    `        } else {`,
    `            qb.push(format!("{col} LIKE "));`,
    `            qb.push_bind(format!("%{value}"));`,
    `        }`,
    `    }`,
  ];
}

function emitScalarPusher(
  spec: FamilySpec,
  nullable: boolean,
  backend: Backend,
  decimalIsCopy: boolean,
): string {
  const fnName = nullable
    ? `push_${spec.key}_nullable_filter`
    : `push_${spec.key}_filter`;
  const typeName = nullable ? `${spec.typeName}NullableFilter` : `${spec.typeName}Filter`;
  const filterRef = `&filters::${typeName}`;

  const equalsBranch = spec.stringOps
    ? emitStringEqualsBranch(backend)
    : [
        `    if let Some(value) = &f.equals {`,
        `        if any { qb.push(" AND "); }`,
        `        any = true;`,
        `        qb.push(format!("{col} = "));`,
        `        qb.push_bind(${bindSingle(spec, "value", decimalIsCopy)});`,
        `    }`,
      ];

  const orderableBranches = spec.orderable
    ? (
        [
          ["lt", "<"],
          ["lte", "<="],
          ["gt", ">"],
          ["gte", ">="],
        ] as const
      ).flatMap(([field, op]) => [
        `    if let Some(value) = &f.${field} {`,
        `        if any { qb.push(" AND "); }`,
        `        any = true;`,
        `        qb.push(format!("{col} ${op} "));`,
        `        qb.push_bind(${bindSingle(spec, "value", decimalIsCopy)});`,
        `    }`,
      ])
    : [];

  const lines: string[] = [
    `pub(crate) fn ${fnName}(qb: &mut sqlx::QueryBuilder<'_, ${backend.dbType}>, col: &str, f: ${filterRef}) -> bool {`,
    `    qb.push("(");`,
    `    let mut any = false;`,
    ...(spec.stringOps ? emitStringOpsHeader(backend) : []),
    ``,
    // is_null (nullable only)
    ...(nullable
      ? [
          `    if let Some(want_null) = f.is_null {`,
          `        if any { qb.push(" AND "); }`,
          `        any = true;`,
          `        if want_null {`,
          `            qb.push(format!("{col} IS NULL"));`,
          `        } else {`,
          `            qb.push(format!("{col} IS NOT NULL"));`,
          `        }`,
          `    }`,
        ]
      : []),
    ...equalsBranch,
    // r#in
    ...(spec.hasInList ? emitInListBranch(spec, backend, decimalIsCopy) : []),
    // not_in
    ...(spec.hasNotInList ? emitNotInListBranch(spec, backend, decimalIsCopy) : []),
    ...orderableBranches,
    // String-only: contains / starts_with / ends_with
    ...(spec.stringOps ? emitStringLikeBranches(backend) : []),
    // not — recurse
    `    if let Some(inner) = &f.not {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        qb.push("NOT ");`,
    `        ${fnName}(qb, col, inner);`,
    `    }`,
    ``,
    `    if !any { qb.push("TRUE"); }`,
    `    qb.push(")");`,
    `    any`,
    `}`,
  ];

  return lines.join("\n");
}

/**
 * Emit the enum r#in / not_in branches. Same divergence as the scalar pushers:
 * Postgres binds the whole Vec via ANY/ALL; SQLite expands to one placeholder
 * per element via `QueryBuilder::separated`. Generated enums always derive
 * `Copy`, so each element is deref-copied (`*v`) when re-binding under SQLite.
 */
function emitEnumInListBranches(backend: Backend): string[] {
  if (backend.arrayIn === "ANY") {
    return [
      `    if let Some(values) = &f.r#in {`,
      `        if any { qb.push(" AND "); }`,
      `        any = true;`,
      `        if values.is_empty() {`,
      `            qb.push("FALSE");`,
      `        } else {`,
      `            qb.push(format!("{col} = ANY("));`,
      `            qb.push_bind(values.clone());`,
      `            qb.push(")");`,
      `        }`,
      `    }`,
      `    if let Some(values) = &f.not_in {`,
      `        if !values.is_empty() {`,
      `            if any { qb.push(" AND "); }`,
      `            any = true;`,
      `            qb.push(format!("{col} <> ALL("));`,
      `            qb.push_bind(values.clone());`,
      `            qb.push(")");`,
      `        }`,
      `    }`,
    ];
  }
  // backend.arrayIn === "IN_LIST" — SQLite enum IN/NOT IN expansion.
  return [
    `    if let Some(values) = &f.r#in {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        if values.is_empty() {`,
    `            qb.push("FALSE");`,
    `        } else {`,
    `            qb.push(format!("{col} IN ("));`,
    `            let mut sep = qb.separated(", ");`,
    `            for v in values {`,
    `                sep.push_bind(*v);`,
    `            }`,
    `            qb.push(")");`,
    `        }`,
    `    }`,
    `    if let Some(values) = &f.not_in {`,
    `        if !values.is_empty() {`,
    `            if any { qb.push(" AND "); }`,
    `            any = true;`,
    `            qb.push(format!("{col} NOT IN ("));`,
    `            let mut sep = qb.separated(", ");`,
    `            for v in values {`,
    `                sep.push_bind(*v);`,
    `            }`,
    `            qb.push(")");`,
    `        }`,
    `    }`,
  ];
}

function emitEnumPusher(
  e: EnumIR,
  nullable: boolean,
  backend: Backend,
  moduleOf?: ModuleResolver,
): string {
  const snakeName = toSnakeCase(e.name);
  const fnName = nullable
    ? `push_${snakeName}_nullable_filter`
    : `push_${snakeName}_filter`;
  // *Filter and *NullableFilter for enums live in the per-module file where
  // the enum itself was emitted (e.g. crate::schema::RoleFilter), not in the
  // shared filters module. Qualify with the full module path.
  const modulePath = moduleOf ? moduleOf(e.name) : e.module;
  const filterType = nullable
    ? `crate::${modulePath}::${e.name}NullableFilter`
    : `crate::${modulePath}::${e.name}Filter`;

  const lines: string[] = [
    `pub(crate) fn ${fnName}(qb: &mut sqlx::QueryBuilder<'_, ${backend.dbType}>, col: &str, f: &${filterType}) -> bool {`,
    `    qb.push("(");`,
    `    let mut any = false;`,
    ``,
    ...(nullable
      ? [
          `    if let Some(want_null) = f.is_null {`,
          `        if any { qb.push(" AND "); }`,
          `        any = true;`,
          `        if want_null {`,
          `            qb.push(format!("{col} IS NULL"));`,
          `        } else {`,
          `            qb.push(format!("{col} IS NOT NULL"));`,
          `        }`,
          `    }`,
        ]
      : []),
    `    if let Some(value) = &f.equals {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        qb.push(format!("{col} = "));`,
    `        qb.push_bind(*value);`,
    `    }`,
    ...emitEnumInListBranches(backend),
    `    if let Some(inner) = &f.not {`,
    `        if any { qb.push(" AND "); }`,
    `        any = true;`,
    `        qb.push("NOT ");`,
    `        ${fnName}(qb, col, inner);`,
    `    }`,
    ``,
    `    if !any { qb.push("TRUE"); }`,
    `    qb.push(")");`,
    `    any`,
    `}`,
  ];

  return lines.join("\n");
}
