// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]
// engine/sqlx_any/filters.rs

// @generated by prisma-rust-generator
#![allow(clippy::too_many_lines)]
#![allow(unused_imports)]

use crate::shared::filters;
use crate::shared::filters::QueryMode;

pub(crate) fn push_string_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::StringFilter,
) -> bool {
    qb.push("(");
    let mut any = false;
    let ci = matches!(f.mode, Some(QueryMode::Insensitive));

    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if ci {
            qb.push(format!("LOWER({col}) = LOWER("));
            qb.push_bind(value.clone());
            qb.push(")");
        } else {
            qb.push(format!("{col} = "));
            qb.push_bind(value.clone());
        }
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(v.clone());
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(v.clone());
            }
            qb.push(")");
        }
    }
    if let Some(value) = &f.lt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} < "));
        qb.push_bind(value.clone());
    }
    if let Some(value) = &f.lte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} <= "));
        qb.push_bind(value.clone());
    }
    if let Some(value) = &f.gt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} > "));
        qb.push_bind(value.clone());
    }
    if let Some(value) = &f.gte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} >= "));
        qb.push_bind(value.clone());
    }
    if let Some(value) = &f.contains {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if ci {
            qb.push(format!("LOWER({col}) LIKE LOWER("));
            qb.push_bind(format!("%{value}%"));
            qb.push(")");
        } else {
            qb.push(format!("{col} LIKE "));
            qb.push_bind(format!("%{value}%"));
        }
    }
    if let Some(value) = &f.starts_with {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if ci {
            qb.push(format!("LOWER({col}) LIKE LOWER("));
            qb.push_bind(format!("{value}%"));
            qb.push(")");
        } else {
            qb.push(format!("{col} LIKE "));
            qb.push_bind(format!("{value}%"));
        }
    }
    if let Some(value) = &f.ends_with {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if ci {
            qb.push(format!("LOWER({col}) LIKE LOWER("));
            qb.push_bind(format!("%{value}"));
            qb.push(")");
        } else {
            qb.push(format!("{col} LIKE "));
            qb.push_bind(format!("%{value}"));
        }
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_string_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_string_nullable_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::StringNullableFilter,
) -> bool {
    qb.push("(");
    let mut any = false;
    let ci = matches!(f.mode, Some(QueryMode::Insensitive));

    if let Some(want_null) = f.is_null {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if want_null {
            qb.push(format!("{col} IS NULL"));
        } else {
            qb.push(format!("{col} IS NOT NULL"));
        }
    }
    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if ci {
            qb.push(format!("LOWER({col}) = LOWER("));
            qb.push_bind(value.clone());
            qb.push(")");
        } else {
            qb.push(format!("{col} = "));
            qb.push_bind(value.clone());
        }
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(v.clone());
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(v.clone());
            }
            qb.push(")");
        }
    }
    if let Some(value) = &f.lt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} < "));
        qb.push_bind(value.clone());
    }
    if let Some(value) = &f.lte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} <= "));
        qb.push_bind(value.clone());
    }
    if let Some(value) = &f.gt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} > "));
        qb.push_bind(value.clone());
    }
    if let Some(value) = &f.gte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} >= "));
        qb.push_bind(value.clone());
    }
    if let Some(value) = &f.contains {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if ci {
            qb.push(format!("LOWER({col}) LIKE LOWER("));
            qb.push_bind(format!("%{value}%"));
            qb.push(")");
        } else {
            qb.push(format!("{col} LIKE "));
            qb.push_bind(format!("%{value}%"));
        }
    }
    if let Some(value) = &f.starts_with {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if ci {
            qb.push(format!("LOWER({col}) LIKE LOWER("));
            qb.push_bind(format!("{value}%"));
            qb.push(")");
        } else {
            qb.push(format!("{col} LIKE "));
            qb.push_bind(format!("{value}%"));
        }
    }
    if let Some(value) = &f.ends_with {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if ci {
            qb.push(format!("LOWER({col}) LIKE LOWER("));
            qb.push_bind(format!("%{value}"));
            qb.push(")");
        } else {
            qb.push(format!("{col} LIKE "));
            qb.push_bind(format!("%{value}"));
        }
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_string_nullable_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_int_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::IntFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(*value);
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(value) = &f.lt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} < "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.lte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} <= "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} > "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} >= "));
        qb.push_bind(*value);
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_int_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_int_nullable_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::IntNullableFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(want_null) = f.is_null {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if want_null {
            qb.push(format!("{col} IS NULL"));
        } else {
            qb.push(format!("{col} IS NOT NULL"));
        }
    }
    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(*value);
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(value) = &f.lt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} < "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.lte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} <= "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} > "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} >= "));
        qb.push_bind(*value);
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_int_nullable_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_bigint_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::BigIntFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(*value);
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(value) = &f.lt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} < "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.lte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} <= "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} > "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} >= "));
        qb.push_bind(*value);
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_bigint_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_bigint_nullable_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::BigIntNullableFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(want_null) = f.is_null {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if want_null {
            qb.push(format!("{col} IS NULL"));
        } else {
            qb.push(format!("{col} IS NOT NULL"));
        }
    }
    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(*value);
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(value) = &f.lt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} < "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.lte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} <= "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} > "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} >= "));
        qb.push_bind(*value);
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_bigint_nullable_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_float_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::FloatFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(*value);
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(value) = &f.lt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} < "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.lte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} <= "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} > "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} >= "));
        qb.push_bind(*value);
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_float_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_float_nullable_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::FloatNullableFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(want_null) = f.is_null {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if want_null {
            qb.push(format!("{col} IS NULL"));
        } else {
            qb.push(format!("{col} IS NOT NULL"));
        }
    }
    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(*value);
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(value) = &f.lt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} < "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.lte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} <= "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gt {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} > "));
        qb.push_bind(*value);
    }
    if let Some(value) = &f.gte {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} >= "));
        qb.push_bind(*value);
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_float_nullable_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_bool_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::BoolFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(*value);
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_bool_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_bool_nullable_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::BoolNullableFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(want_null) = f.is_null {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if want_null {
            qb.push(format!("{col} IS NULL"));
        } else {
            qb.push(format!("{col} IS NOT NULL"));
        }
    }
    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(*value);
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(*v);
            }
            qb.push(")");
        }
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_bool_nullable_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_bytes_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::BytesFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(value.clone());
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(v.clone());
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(v.clone());
            }
            qb.push(")");
        }
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_bytes_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn push_bytes_nullable_filter(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Any>,
    col: &str,
    f: &filters::BytesNullableFilter,
) -> bool {
    qb.push("(");
    let mut any = false;

    if let Some(want_null) = f.is_null {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if want_null {
            qb.push(format!("{col} IS NULL"));
        } else {
            qb.push(format!("{col} IS NOT NULL"));
        }
    }
    if let Some(value) = &f.equals {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push(format!("{col} = "));
        qb.push_bind(value.clone());
    }
    if let Some(values) = &f.r#in {
        if any {
            qb.push(" AND ");
        }
        any = true;
        if values.is_empty() {
            qb.push("FALSE");
        } else {
            qb.push(format!("{col} IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(v.clone());
            }
            qb.push(")");
        }
    }
    if let Some(values) = &f.not_in {
        if !values.is_empty() {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push(format!("{col} NOT IN ("));
            let mut sep = qb.separated(", ");
            for v in values {
                sep.push_bind(v.clone());
            }
            qb.push(")");
        }
    }
    if let Some(inner) = &f.not {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("NOT ");
        push_bytes_nullable_filter(qb, col, inner);
    }

    if !any {
        qb.push("TRUE");
    }
    qb.push(")");
    any
}

pub(crate) fn sort_order_sql(o: crate::shared::filters::SortOrder) -> &'static str {
    match o {
        crate::shared::filters::SortOrder::Asc => "ASC",
        crate::shared::filters::SortOrder::Desc => "DESC",
        crate::shared::filters::SortOrder::AscNullsFirst => "ASC NULLS FIRST",
        crate::shared::filters::SortOrder::AscNullsLast => "ASC NULLS LAST",
        crate::shared::filters::SortOrder::DescNullsFirst => "DESC NULLS FIRST",
        crate::shared::filters::SortOrder::DescNullsLast => "DESC NULLS LAST",
    }
}
