// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ExternalPlatform {
    #[serde(rename = "ADVITA")]
    Advita,
    #[serde(rename = "CLIO")]
    Clio,
    #[serde(rename = "FILEVINE")]
    Filevine,
    #[serde(rename = "LITIFY")]
    Litify,
    #[serde(rename = "SALESFORCE")]
    Salesforce,
    #[serde(rename = "OTHER")]
    Other,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformFieldUpdateOperationsInput {
    pub set: Option<ExternalPlatform>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NullableExternalPlatformFieldUpdateOperationsInput {
    pub set: Option<Option<ExternalPlatform>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformFilter {
    pub equals: Option<crate::external_platforms::ExternalPlatform>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::external_platforms::ExternalPlatform>>,
    pub not_in: Option<Vec<crate::external_platforms::ExternalPlatform>>,
    pub not: Option<Box<ExternalPlatformFilter>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformNullableFilter {
    pub equals: Option<crate::external_platforms::ExternalPlatform>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::external_platforms::ExternalPlatform>>,
    pub not_in: Option<Vec<crate::external_platforms::ExternalPlatform>>,
    pub is_null: Option<bool>,
    pub not: Option<Box<ExternalPlatformNullableFilter>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ExternalSyncStatus {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "SYNCING")]
    Syncing,
    #[serde(rename = "SYNCED")]
    Synced,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "DISABLED")]
    Disabled,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalSyncStatusFieldUpdateOperationsInput {
    pub set: Option<ExternalSyncStatus>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NullableExternalSyncStatusFieldUpdateOperationsInput {
    pub set: Option<Option<ExternalSyncStatus>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalSyncStatusFilter {
    pub equals: Option<crate::external_platforms::ExternalSyncStatus>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::external_platforms::ExternalSyncStatus>>,
    pub not_in: Option<Vec<crate::external_platforms::ExternalSyncStatus>>,
    pub not: Option<Box<ExternalSyncStatusFilter>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalSyncStatusNullableFilter {
    pub equals: Option<crate::external_platforms::ExternalSyncStatus>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::external_platforms::ExternalSyncStatus>>,
    pub not_in: Option<Vec<crate::external_platforms::ExternalSyncStatus>>,
    pub is_null: Option<bool>,
    pub not: Option<Box<ExternalSyncStatusNullableFilter>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ExternalSyncFrequency {
    #[serde(rename = "MANUAL")]
    Manual,
    #[serde(rename = "HOURLY")]
    Hourly,
    #[serde(rename = "DAILY")]
    Daily,
    #[serde(rename = "WEEKLY")]
    Weekly,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalSyncFrequencyFieldUpdateOperationsInput {
    pub set: Option<ExternalSyncFrequency>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NullableExternalSyncFrequencyFieldUpdateOperationsInput {
    pub set: Option<Option<ExternalSyncFrequency>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalSyncFrequencyFilter {
    pub equals: Option<crate::external_platforms::ExternalSyncFrequency>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::external_platforms::ExternalSyncFrequency>>,
    pub not_in: Option<Vec<crate::external_platforms::ExternalSyncFrequency>>,
    pub not: Option<Box<ExternalSyncFrequencyFilter>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalSyncFrequencyNullableFilter {
    pub equals: Option<crate::external_platforms::ExternalSyncFrequency>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::external_platforms::ExternalSyncFrequency>>,
    pub not_in: Option<Vec<crate::external_platforms::ExternalSyncFrequency>>,
    pub is_null: Option<bool>,
    pub not: Option<Box<ExternalSyncFrequencyNullableFilter>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegration {
    pub id: i32,
    pub client_id: String,
    /// Ciphertext produced by the backend's envelope encryption. Consumers
    /// MUST NEVER write plaintext. Same pattern as
    /// `AdvitaConnection.apiKeyEncrypted`.
    pub api_key_encrypted: String,
    pub return_url: Option<String>,
    pub integration_type: String,
    /// @ent.json object
    pub credentials: Option<serde_json::Value>,
    pub ocr: bool,
    pub docrio_aws_prefix: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationWhereInput {
    pub id: Option<crate::shared::filters::IntFilter>,
    pub client_id: Option<crate::shared::filters::StringFilter>,
    pub api_key_encrypted: Option<crate::shared::filters::StringFilter>,
    pub return_url: Option<crate::shared::filters::StringNullableFilter>,
    pub integration_type: Option<crate::shared::filters::StringFilter>,
    pub credentials: Option<crate::shared::filters::JsonNullableFilter>,
    pub ocr: Option<crate::shared::filters::BoolFilter>,
    pub docrio_aws_prefix: Option<crate::shared::filters::StringNullableFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<ApiIntegrationWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<ApiIntegrationWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<ApiIntegrationWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationRelationFilter {
    pub is: Option<Box<crate::external_platforms::ApiIntegrationWhereInput>>,
    pub is_not: Option<Box<crate::external_platforms::ApiIntegrationWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationListRelationFilter {
    pub some: Option<Box<crate::external_platforms::ApiIntegrationWhereInput>>,
    pub every: Option<Box<crate::external_platforms::ApiIntegrationWhereInput>>,
    pub none: Option<Box<crate::external_platforms::ApiIntegrationWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationWhereUniqueInput {
    pub id: Option<i32>,
    pub client_id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationOrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub client_id: Option<crate::shared::filters::SortOrder>,
    pub api_key_encrypted: Option<crate::shared::filters::SortOrder>,
    pub return_url: Option<crate::shared::filters::SortOrder>,
    pub integration_type: Option<crate::shared::filters::SortOrder>,
    pub credentials: Option<crate::shared::filters::SortOrder>,
    pub ocr: Option<crate::shared::filters::SortOrder>,
    pub docrio_aws_prefix: Option<crate::shared::filters::SortOrder>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationSelect {
    pub id: Option<bool>,
    pub client_id: Option<bool>,
    pub api_key_encrypted: Option<bool>,
    pub return_url: Option<bool>,
    pub integration_type: Option<bool>,
    pub credentials: Option<bool>,
    pub ocr: Option<bool>,
    pub docrio_aws_prefix: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationInclude {}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationCreateInput {
    pub client_id: String,
    pub api_key_encrypted: String,
    pub return_url: Option<String>,
    pub credentials: Option<serde_json::Value>,
    pub docrio_aws_prefix: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationUncheckedCreateInput {
    pub client_id: String,
    pub api_key_encrypted: String,
    pub return_url: Option<String>,
    pub credentials: Option<serde_json::Value>,
    pub docrio_aws_prefix: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationCreateManyInput {
    pub client_id: String,
    pub api_key_encrypted: String,
    pub return_url: Option<String>,
    pub credentials: Option<serde_json::Value>,
    pub docrio_aws_prefix: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationUpdateInput {
    pub id: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub client_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub api_key_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub return_url: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub integration_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub credentials: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub ocr: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub docrio_aws_prefix: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationUncheckedUpdateInput {
    pub id: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub client_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub api_key_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub return_url: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub integration_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub credentials: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub ocr: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub docrio_aws_prefix: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationUpdateManyMutationInput {
    pub id: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub client_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub api_key_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub return_url: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub integration_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub credentials: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub ocr: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub docrio_aws_prefix: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationUncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub client_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub api_key_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub return_url: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub integration_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub credentials: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub ocr: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub docrio_aws_prefix: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationScalarWhereInput {
    pub id: Option<crate::shared::filters::IntFilter>,
    pub client_id: Option<crate::shared::filters::StringFilter>,
    pub api_key_encrypted: Option<crate::shared::filters::StringFilter>,
    pub return_url: Option<crate::shared::filters::StringNullableFilter>,
    pub integration_type: Option<crate::shared::filters::StringFilter>,
    pub credentials: Option<crate::shared::filters::JsonNullableFilter>,
    pub ocr: Option<crate::shared::filters::BoolFilter>,
    pub docrio_aws_prefix: Option<crate::shared::filters::StringNullableFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<ApiIntegrationScalarWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<ApiIntegrationScalarWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<ApiIntegrationScalarWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationCountAggregateInput {
    pub id: Option<bool>,
    pub client_id: Option<bool>,
    pub api_key_encrypted: Option<bool>,
    pub return_url: Option<bool>,
    pub integration_type: Option<bool>,
    pub credentials: Option<bool>,
    pub ocr: Option<bool>,
    pub docrio_aws_prefix: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationAvgAggregateInput {
    pub id: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationSumAggregateInput {
    pub id: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationMinAggregateInput {
    pub id: Option<bool>,
    pub client_id: Option<bool>,
    pub api_key_encrypted: Option<bool>,
    pub return_url: Option<bool>,
    pub integration_type: Option<bool>,
    pub ocr: Option<bool>,
    pub docrio_aws_prefix: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationMaxAggregateInput {
    pub id: Option<bool>,
    pub client_id: Option<bool>,
    pub api_key_encrypted: Option<bool>,
    pub return_url: Option<bool>,
    pub integration_type: Option<bool>,
    pub ocr: Option<bool>,
    pub docrio_aws_prefix: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationOrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub client_id: Option<crate::shared::filters::SortOrder>,
    pub api_key_encrypted: Option<crate::shared::filters::SortOrder>,
    pub return_url: Option<crate::shared::filters::SortOrder>,
    pub integration_type: Option<crate::shared::filters::SortOrder>,
    pub credentials: Option<crate::shared::filters::SortOrder>,
    pub ocr: Option<crate::shared::filters::SortOrder>,
    pub docrio_aws_prefix: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<ApiIntegrationCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<ApiIntegrationAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<ApiIntegrationSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<ApiIntegrationMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<ApiIntegrationMaxAggregateInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiIntegrationAggregateInput {
    #[serde(rename = "where")]
    pub r#where: Option<ApiIntegrationWhereInput>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<ApiIntegrationCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<ApiIntegrationAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<ApiIntegrationSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<ApiIntegrationMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<ApiIntegrationMaxAggregateInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnection {
    pub id: String,
    pub firm_id: String,
    pub platform: crate::external_platforms::ExternalPlatform,
    /// Optional label for custom integrations when platform is OTHER.
    pub platform_label: Option<String>,
    /// AES-256-GCM encrypted blob from backend crypto wrapper.
    /// Never store plaintext API keys/tokens in this column.
    pub credentials_encrypted: String,
    pub sync_status: crate::external_platforms::ExternalSyncStatus,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
    pub last_sync_error: Option<String>,
    pub sync_frequency: crate::external_platforms::ExternalSyncFrequency,
    /// @ent.json object
    /// Expected contract: { externalFieldKey: internalFieldKey }.
    pub field_mapping: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub firm: Option<Box<crate::firms::Firm>>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub entity_mappings: Vec<crate::external_platforms::ExternalEntityMapping>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub firm_id: Option<crate::shared::filters::StringFilter>,
    pub platform: Option<crate::external_platforms::ExternalPlatformFilter>,
    pub platform_label: Option<crate::shared::filters::StringNullableFilter>,
    pub credentials_encrypted: Option<crate::shared::filters::StringFilter>,
    pub sync_status: Option<crate::external_platforms::ExternalSyncStatusFilter>,
    pub last_sync_at: Option<crate::shared::filters::DateTimeNullableFilter>,
    pub last_sync_error: Option<crate::shared::filters::StringNullableFilter>,
    pub sync_frequency: Option<crate::external_platforms::ExternalSyncFrequencyFilter>,
    pub field_mapping: Option<crate::shared::filters::JsonNullableFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub updated_at: Option<crate::shared::filters::DateTimeFilter>,
    pub firm: Option<crate::firms::FirmRelationFilter>,
    pub entity_mappings: Option<crate::external_platforms::ExternalEntityMappingListRelationFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<ExternalPlatformConnectionWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<ExternalPlatformConnectionWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<ExternalPlatformConnectionWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionRelationFilter {
    pub is: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereInput>>,
    pub is_not: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionListRelationFilter {
    pub some: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereInput>>,
    pub every: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereInput>>,
    pub none: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionWhereUniqueInput {
    pub id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionOrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub firm_id: Option<crate::shared::filters::SortOrder>,
    pub platform: Option<crate::shared::filters::SortOrder>,
    pub platform_label: Option<crate::shared::filters::SortOrder>,
    pub credentials_encrypted: Option<crate::shared::filters::SortOrder>,
    pub sync_status: Option<crate::shared::filters::SortOrder>,
    pub last_sync_at: Option<crate::shared::filters::SortOrder>,
    pub last_sync_error: Option<crate::shared::filters::SortOrder>,
    pub sync_frequency: Option<crate::shared::filters::SortOrder>,
    pub field_mapping: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub updated_at: Option<crate::shared::filters::SortOrder>,
    pub firm: Option<Box<crate::firms::FirmOrderByWithRelationInput>>,
    pub entity_mappings:
        Option<Box<crate::external_platforms::ExternalEntityMappingOrderByWithRelationInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionSelect {
    pub id: Option<bool>,
    pub firm_id: Option<bool>,
    pub platform: Option<bool>,
    pub platform_label: Option<bool>,
    pub credentials_encrypted: Option<bool>,
    pub sync_status: Option<bool>,
    pub last_sync_at: Option<bool>,
    pub last_sync_error: Option<bool>,
    pub sync_frequency: Option<bool>,
    pub field_mapping: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
    pub firm: Option<bool>,
    pub entity_mappings: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionInclude {
    pub firm: Option<bool>,
    pub entity_mappings: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionCreateInput {
    pub platform: crate::external_platforms::ExternalPlatform,
    pub platform_label: Option<String>,
    pub credentials_encrypted: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
    pub last_sync_error: Option<String>,
    pub field_mapping: Option<serde_json::Value>,
    pub firm: Option<Box<crate::external_platforms::FirmCreateNestedOneWithoutExternalPlatformConnectionFirmInput>>,
    pub entity_mappings: Option<Box<crate::external_platforms::ExternalEntityMappingCreateNestedManyWithoutExternalPlatformConnectionEntityMappingsInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUncheckedCreateInput {
    pub firm_id: String,
    pub platform: crate::external_platforms::ExternalPlatform,
    pub platform_label: Option<String>,
    pub credentials_encrypted: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
    pub last_sync_error: Option<String>,
    pub field_mapping: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionCreateManyInput {
    pub firm_id: String,
    pub platform: crate::external_platforms::ExternalPlatform,
    pub platform_label: Option<String>,
    pub credentials_encrypted: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
    pub last_sync_error: Option<String>,
    pub field_mapping: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub platform: Option<crate::external_platforms::ExternalPlatformFieldUpdateOperationsInput>,
    pub platform_label: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub credentials_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub sync_status: Option<crate::external_platforms::ExternalSyncStatusFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub last_sync_error: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub sync_frequency: Option<crate::external_platforms::ExternalSyncFrequencyFieldUpdateOperationsInput>,
    pub field_mapping: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub firm: Option<Box<crate::external_platforms::FirmUpdateOneRequiredWithoutExternalPlatformConnectionFirmNestedInput>>,
    pub entity_mappings: Option<Box<crate::external_platforms::ExternalEntityMappingUpdateManyWithoutExternalPlatformConnectionEntityMappingsNestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUncheckedUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub firm_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub platform: Option<crate::external_platforms::ExternalPlatformFieldUpdateOperationsInput>,
    pub platform_label: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub credentials_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub sync_status:
        Option<crate::external_platforms::ExternalSyncStatusFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub last_sync_error: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub sync_frequency:
        Option<crate::external_platforms::ExternalSyncFrequencyFieldUpdateOperationsInput>,
    pub field_mapping: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUpdateManyMutationInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub platform: Option<crate::external_platforms::ExternalPlatformFieldUpdateOperationsInput>,
    pub platform_label: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub credentials_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub sync_status:
        Option<crate::external_platforms::ExternalSyncStatusFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub last_sync_error: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub sync_frequency:
        Option<crate::external_platforms::ExternalSyncFrequencyFieldUpdateOperationsInput>,
    pub field_mapping: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub firm_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub platform: Option<crate::external_platforms::ExternalPlatformFieldUpdateOperationsInput>,
    pub platform_label: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub credentials_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub sync_status:
        Option<crate::external_platforms::ExternalSyncStatusFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub last_sync_error: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub sync_frequency:
        Option<crate::external_platforms::ExternalSyncFrequencyFieldUpdateOperationsInput>,
    pub field_mapping: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCreateWithoutExternalPlatformConnectionFirmInput {
    pub name: String,
    pub phone_number: Option<String>,
    pub fax_number: Option<String>,
    pub address: Option<Box<crate::firms::AddressCreateNestedOneWithoutFirmAddressInput>>,
    pub users: Option<Box<crate::firms::UserCreateNestedManyWithoutFirmUsersInput>>,
    pub owner: Option<Box<crate::firms::UserCreateNestedOneWithoutFirmOwnerInput>>,
    pub documents: Option<Box<crate::firms::DocumentCreateNestedManyWithoutFirmDocumentsInput>>,
    pub cases: Option<Box<crate::firms::CaseCreateNestedManyWithoutFirmCasesInput>>,
    pub demand_letters: Option<Box<crate::firms::DemandLetterCreateNestedManyWithoutFirmDemandLettersInput>>,
    pub search_processings: Option<Box<crate::firms::SearchProcessingCreateNestedManyWithoutFirmSearchProcessingsInput>>,
    pub search_templates: Option<Box<crate::firms::DocumentSearchTemplateCreateNestedManyWithoutFirmSearchTemplatesInput>>,
    pub sso_configs: Option<Box<crate::firms::FirmSSOConfigCreateNestedManyWithoutFirmSsoConfigsInput>>,
    pub invoices: Option<Box<crate::firms::InvoiceCreateNestedManyWithoutFirmInvoicesInput>>,
    pub initial_case_evaluations: Option<Box<crate::firms::InitialCaseEvaluationProcessingCreateNestedManyWithoutFirmInitialCaseEvaluationsInput>>,
    pub demand_letter_processings: Option<Box<crate::firms::DemandLetterProcessingCreateNestedManyWithoutFirmDemandLetterProcessingsInput>>,
    pub case_review_processings: Option<Box<crate::firms::CaseReviewProcessingCreateNestedManyWithoutFirmCaseReviewProcessingsInput>>,
    pub form_templates: Option<Box<crate::firms::FormTemplateCreateNestedManyWithoutFirmFormTemplatesInput>>,
    pub form_distributions: Option<Box<crate::firms::FormDistributionCreateNestedManyWithoutFirmFormDistributionsInput>>,
    pub form_submissions: Option<Box<crate::firms::FormSubmissionCreateNestedManyWithoutFirmFormSubmissionsInput>>,
    pub pdf_uploads: Option<Box<crate::firms::PdfUploadCreateNestedManyWithoutFirmPdfUploadsInput>>,
    pub notifications: Option<Box<crate::firms::NotificationCreateNestedManyWithoutFirmNotificationsInput>>,
    pub email_deliveries: Option<Box<crate::firms::EmailDeliveryCreateNestedManyWithoutFirmEmailDeliveriesInput>>,
    pub firm_roles: Option<Box<crate::firms::FirmRoleCreateNestedManyWithoutFirmFirmRolesInput>>,
    pub default_role: Option<Box<crate::firms::FirmRoleCreateNestedOneWithoutFirmDefaultRoleInput>>,
    pub advita_connection: Option<Box<crate::firms::AdvitaConnectionCreateNestedOneWithoutFirmAdvitaConnectionInput>>,
    pub advita_case_mappings: Option<Box<crate::firms::AdvitaCaseMappingCreateNestedManyWithoutFirmAdvitaCaseMappingsInput>>,
    pub advita_tracking_mappings: Option<Box<crate::firms::AdvitaTrackingMappingCreateNestedManyWithoutFirmAdvitaTrackingMappingsInput>>,
    pub qualification_criteria: Option<Box<crate::firms::QualificationCriteriaCreateNestedManyWithoutFirmQualificationCriteriaInput>>,
    pub case_qualifications: Option<Box<crate::firms::CaseQualificationCreateNestedManyWithoutFirmCaseQualificationsInput>>,
    pub tort_templates: Option<Box<crate::firms::TortTemplateCreateNestedManyWithoutFirmTortTemplatesInput>>,
    pub qualify_ai_processing: Option<Box<crate::firms::QualifyAiProcessingCreateNestedManyWithoutFirmQualifyAiProcessingInput>>,
    pub qualify_ai_qualifier_documents: Option<Box<crate::firms::QualifyAiQualifierDocumentCreateNestedManyWithoutFirmQualifyAiQualifierDocumentsInput>>,
    pub firm_invitations: Option<Box<crate::firms::FirmInvitationCreateNestedManyWithoutFirmFirmInvitationsInput>>,
    pub firm_document_types: Option<Box<crate::firms::FirmDocumentTypeCreateNestedManyWithoutFirmFirmDocumentTypesInput>>,
    pub case_notes: Option<Box<crate::firms::CaseNoteCreateNestedManyWithoutFirmCaseNotesInput>>,
    pub case_tasks: Option<Box<crate::firms::CaseTaskCreateNestedManyWithoutFirmCaseTasksInput>>,
    pub case_calendar_entries: Option<Box<crate::firms::CaseCalendarEntryCreateNestedManyWithoutFirmCaseCalendarEntriesInput>>,
    pub case_contacts: Option<Box<crate::firms::CaseContactCreateNestedManyWithoutFirmCaseContactsInput>>,
    pub case_billing_time_entries: Option<Box<crate::firms::CaseBillingTimeEntryCreateNestedManyWithoutFirmCaseBillingTimeEntriesInput>>,
    pub case_billing_expenses: Option<Box<crate::firms::CaseBillingExpenseCreateNestedManyWithoutFirmCaseBillingExpensesInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUncheckedCreateWithoutExternalPlatformConnectionFirmInput {
    pub name: String,
    pub phone_number: Option<String>,
    pub fax_number: Option<String>,
    pub address_id: Option<String>,
    pub owner_id: Option<String>,
    pub default_role_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCreateOrConnectWithoutExternalPlatformConnectionFirmInput {
    pub r#where: Box<crate::firms::FirmWhereUniqueInput>,
    pub create:
        Box<crate::external_platforms::FirmCreateWithoutExternalPlatformConnectionFirmInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpdateWithoutExternalPlatformConnectionFirmInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub phone_number: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub fax_number: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub tier: Option<crate::users::SubscriptionTierFieldUpdateOperationsInput>,
    pub has_free_demo_ocr: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub has_free_demo_identification: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub require_mfa: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub qualify_ai_demo_used: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub address: Option<Box<crate::firms::AddressUpdateOneWithoutFirmAddressNestedInput>>,
    pub users: Option<Box<crate::firms::UserUpdateManyWithoutFirmUsersNestedInput>>,
    pub owner: Option<Box<crate::firms::UserUpdateOneWithoutFirmOwnerNestedInput>>,
    pub documents: Option<Box<crate::firms::DocumentUpdateManyWithoutFirmDocumentsNestedInput>>,
    pub cases: Option<Box<crate::firms::CaseUpdateManyWithoutFirmCasesNestedInput>>,
    pub demand_letters: Option<Box<crate::firms::DemandLetterUpdateManyWithoutFirmDemandLettersNestedInput>>,
    pub search_processings: Option<Box<crate::firms::SearchProcessingUpdateManyWithoutFirmSearchProcessingsNestedInput>>,
    pub search_templates: Option<Box<crate::firms::DocumentSearchTemplateUpdateManyWithoutFirmSearchTemplatesNestedInput>>,
    pub sso_configs: Option<Box<crate::firms::FirmSSOConfigUpdateManyWithoutFirmSsoConfigsNestedInput>>,
    pub invoices: Option<Box<crate::firms::InvoiceUpdateManyWithoutFirmInvoicesNestedInput>>,
    pub initial_case_evaluations: Option<Box<crate::firms::InitialCaseEvaluationProcessingUpdateManyWithoutFirmInitialCaseEvaluationsNestedInput>>,
    pub demand_letter_processings: Option<Box<crate::firms::DemandLetterProcessingUpdateManyWithoutFirmDemandLetterProcessingsNestedInput>>,
    pub case_review_processings: Option<Box<crate::firms::CaseReviewProcessingUpdateManyWithoutFirmCaseReviewProcessingsNestedInput>>,
    pub form_templates: Option<Box<crate::firms::FormTemplateUpdateManyWithoutFirmFormTemplatesNestedInput>>,
    pub form_distributions: Option<Box<crate::firms::FormDistributionUpdateManyWithoutFirmFormDistributionsNestedInput>>,
    pub form_submissions: Option<Box<crate::firms::FormSubmissionUpdateManyWithoutFirmFormSubmissionsNestedInput>>,
    pub pdf_uploads: Option<Box<crate::firms::PdfUploadUpdateManyWithoutFirmPdfUploadsNestedInput>>,
    pub notifications: Option<Box<crate::firms::NotificationUpdateManyWithoutFirmNotificationsNestedInput>>,
    pub email_deliveries: Option<Box<crate::firms::EmailDeliveryUpdateManyWithoutFirmEmailDeliveriesNestedInput>>,
    pub firm_roles: Option<Box<crate::firms::FirmRoleUpdateManyWithoutFirmFirmRolesNestedInput>>,
    pub default_role: Option<Box<crate::firms::FirmRoleUpdateOneWithoutFirmDefaultRoleNestedInput>>,
    pub advita_connection: Option<Box<crate::firms::AdvitaConnectionUpdateOneWithoutFirmAdvitaConnectionNestedInput>>,
    pub advita_case_mappings: Option<Box<crate::firms::AdvitaCaseMappingUpdateManyWithoutFirmAdvitaCaseMappingsNestedInput>>,
    pub advita_tracking_mappings: Option<Box<crate::firms::AdvitaTrackingMappingUpdateManyWithoutFirmAdvitaTrackingMappingsNestedInput>>,
    pub qualification_criteria: Option<Box<crate::firms::QualificationCriteriaUpdateManyWithoutFirmQualificationCriteriaNestedInput>>,
    pub case_qualifications: Option<Box<crate::firms::CaseQualificationUpdateManyWithoutFirmCaseQualificationsNestedInput>>,
    pub tort_templates: Option<Box<crate::firms::TortTemplateUpdateManyWithoutFirmTortTemplatesNestedInput>>,
    pub qualify_ai_processing: Option<Box<crate::firms::QualifyAiProcessingUpdateManyWithoutFirmQualifyAiProcessingNestedInput>>,
    pub qualify_ai_qualifier_documents: Option<Box<crate::firms::QualifyAiQualifierDocumentUpdateManyWithoutFirmQualifyAiQualifierDocumentsNestedInput>>,
    pub firm_invitations: Option<Box<crate::firms::FirmInvitationUpdateManyWithoutFirmFirmInvitationsNestedInput>>,
    pub firm_document_types: Option<Box<crate::firms::FirmDocumentTypeUpdateManyWithoutFirmFirmDocumentTypesNestedInput>>,
    pub case_notes: Option<Box<crate::firms::CaseNoteUpdateManyWithoutFirmCaseNotesNestedInput>>,
    pub case_tasks: Option<Box<crate::firms::CaseTaskUpdateManyWithoutFirmCaseTasksNestedInput>>,
    pub case_calendar_entries: Option<Box<crate::firms::CaseCalendarEntryUpdateManyWithoutFirmCaseCalendarEntriesNestedInput>>,
    pub case_contacts: Option<Box<crate::firms::CaseContactUpdateManyWithoutFirmCaseContactsNestedInput>>,
    pub case_billing_time_entries: Option<Box<crate::firms::CaseBillingTimeEntryUpdateManyWithoutFirmCaseBillingTimeEntriesNestedInput>>,
    pub case_billing_expenses: Option<Box<crate::firms::CaseBillingExpenseUpdateManyWithoutFirmCaseBillingExpensesNestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUncheckedUpdateWithoutExternalPlatformConnectionFirmInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub phone_number: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub fax_number: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub address_id: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub owner_id: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub tier: Option<crate::users::SubscriptionTierFieldUpdateOperationsInput>,
    pub has_free_demo_ocr: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub has_free_demo_identification:
        Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub require_mfa: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub default_role_id: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub qualify_ai_demo_used: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCreateNestedOneWithoutExternalPlatformConnectionFirmInput {
    pub create: Option<Box<crate::external_platforms::FirmCreateWithoutExternalPlatformConnectionFirmInput>>,
    pub connect_or_create: Option<Box<crate::external_platforms::FirmCreateOrConnectWithoutExternalPlatformConnectionFirmInput>>,
    pub connect: Option<Box<crate::firms::FirmWhereUniqueInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpsertWithoutExternalPlatformConnectionFirmInput {
    pub update:
        Box<crate::external_platforms::FirmUpdateWithoutExternalPlatformConnectionFirmInput>,
    pub create:
        Box<crate::external_platforms::FirmCreateWithoutExternalPlatformConnectionFirmInput>,
    pub r#where: Option<Box<crate::firms::FirmWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpdateOneRequiredWithoutExternalPlatformConnectionFirmNestedInput {
    pub create: Option<Box<crate::external_platforms::FirmCreateWithoutExternalPlatformConnectionFirmInput>>,
    pub connect_or_create: Option<Box<crate::external_platforms::FirmCreateOrConnectWithoutExternalPlatformConnectionFirmInput>>,
    pub upsert: Option<Box<crate::external_platforms::FirmUpsertWithoutExternalPlatformConnectionFirmInput>>,
    pub connect: Option<Box<crate::firms::FirmWhereUniqueInput>>,
    pub update: Option<Box<crate::external_platforms::FirmUpdateToOneWithWhereWithoutExternalPlatformConnectionFirmInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpdateToOneWithWhereWithoutExternalPlatformConnectionFirmInput {
    pub r#where: Option<Box<crate::firms::FirmWhereInput>>,
    pub data: Box<crate::external_platforms::FirmUpdateWithoutExternalPlatformConnectionFirmInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingCreateWithoutExternalPlatformConnectionEntityMappingsInput {
    pub external_entity_type: String,
    pub external_entity_id: String,
    pub internal_entity_type: String,
    pub internal_entity_id: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUncheckedCreateWithoutExternalPlatformConnectionEntityMappingsInput
{
    pub connection_id: String,
    pub external_entity_type: String,
    pub external_entity_id: String,
    pub internal_entity_type: String,
    pub internal_entity_id: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingCreateOrConnectWithoutExternalPlatformConnectionEntityMappingsInput {
    pub r#where: Box<crate::external_platforms::ExternalEntityMappingWhereUniqueInput>,
    pub create: Box<crate::external_platforms::ExternalEntityMappingCreateWithoutExternalPlatformConnectionEntityMappingsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUpdateWithoutExternalPlatformConnectionEntityMappingsInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUncheckedUpdateWithoutExternalPlatformConnectionEntityMappingsInput
{
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub connection_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingCreateNestedManyWithoutExternalPlatformConnectionEntityMappingsInput {
    pub create: Option<crate::shared::filters::OneOrMany<crate::external_platforms::ExternalEntityMappingCreateWithoutExternalPlatformConnectionEntityMappingsInput>>,
    pub connect_or_create: Option<Vec<crate::external_platforms::ExternalEntityMappingCreateOrConnectWithoutExternalPlatformConnectionEntityMappingsInput>>,
    pub create_many: Option<Box<crate::external_platforms::ExternalEntityMappingCreateManyExternalPlatformConnectionEntityMappingsInputEnvelope>>,
    pub connect: Option<crate::shared::filters::OneOrMany<crate::external_platforms::ExternalEntityMappingWhereUniqueInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingCreateManyExternalPlatformConnectionEntityMappingsInputEnvelope {
    pub data: Vec<crate::external_platforms::ExternalEntityMappingCreateManyExternalPlatformConnectionEntityMappingsInput>,
    pub skip_duplicates: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingCreateManyExternalPlatformConnectionEntityMappingsInput {
    pub connection_id: String,
    pub external_entity_type: String,
    pub external_entity_id: String,
    pub internal_entity_type: String,
    pub internal_entity_id: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUpdateManyWithoutExternalPlatformConnectionEntityMappingsNestedInput {
    pub create: Option<crate::shared::filters::OneOrMany<crate::external_platforms::ExternalEntityMappingCreateWithoutExternalPlatformConnectionEntityMappingsInput>>,
    pub connect_or_create: Option<Vec<crate::external_platforms::ExternalEntityMappingCreateOrConnectWithoutExternalPlatformConnectionEntityMappingsInput>>,
    pub upsert: Option<Vec<crate::external_platforms::ExternalEntityMappingUpsertWithWhereUniqueWithoutExternalPlatformConnectionEntityMappingsInput>>,
    pub create_many: Option<Box<crate::external_platforms::ExternalEntityMappingCreateManyExternalPlatformConnectionEntityMappingsInputEnvelope>>,
    pub set: Option<Vec<crate::external_platforms::ExternalEntityMappingWhereUniqueInput>>,
    pub disconnect: Option<Vec<crate::external_platforms::ExternalEntityMappingWhereUniqueInput>>,
    pub delete: Option<Vec<crate::external_platforms::ExternalEntityMappingWhereUniqueInput>>,
    pub connect: Option<Vec<crate::external_platforms::ExternalEntityMappingWhereUniqueInput>>,
    pub update: Option<Vec<crate::external_platforms::ExternalEntityMappingUpdateWithWhereUniqueWithoutExternalPlatformConnectionEntityMappingsInput>>,
    pub update_many: Option<Vec<crate::external_platforms::ExternalEntityMappingUpdateManyWithWhereWithoutExternalPlatformConnectionEntityMappingsInput>>,
    pub delete_many: Option<Vec<crate::external_platforms::ExternalEntityMappingScalarWhereInput>>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUpsertWithWhereUniqueWithoutExternalPlatformConnectionEntityMappingsInput {
    pub r#where: Box<crate::external_platforms::ExternalEntityMappingWhereUniqueInput>,
    pub update: Box<crate::external_platforms::ExternalEntityMappingUpdateWithoutExternalPlatformConnectionEntityMappingsInput>,
    pub create: Box<crate::external_platforms::ExternalEntityMappingCreateWithoutExternalPlatformConnectionEntityMappingsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUpdateWithWhereUniqueWithoutExternalPlatformConnectionEntityMappingsInput {
    pub r#where: Box<crate::external_platforms::ExternalEntityMappingWhereUniqueInput>,
    pub data: Box<crate::external_platforms::ExternalEntityMappingUpdateWithoutExternalPlatformConnectionEntityMappingsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUpdateManyWithWhereWithoutExternalPlatformConnectionEntityMappingsInput
{
    pub r#where: Box<crate::external_platforms::ExternalEntityMappingScalarWhereInput>,
    pub data: Box<crate::external_platforms::ExternalEntityMappingUpdateManyMutationInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionScalarWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub firm_id: Option<crate::shared::filters::StringFilter>,
    pub platform: Option<crate::external_platforms::ExternalPlatformFilter>,
    pub platform_label: Option<crate::shared::filters::StringNullableFilter>,
    pub credentials_encrypted: Option<crate::shared::filters::StringFilter>,
    pub sync_status: Option<crate::external_platforms::ExternalSyncStatusFilter>,
    pub last_sync_at: Option<crate::shared::filters::DateTimeNullableFilter>,
    pub last_sync_error: Option<crate::shared::filters::StringNullableFilter>,
    pub sync_frequency: Option<crate::external_platforms::ExternalSyncFrequencyFilter>,
    pub field_mapping: Option<crate::shared::filters::JsonNullableFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub updated_at: Option<crate::shared::filters::DateTimeFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<ExternalPlatformConnectionScalarWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<ExternalPlatformConnectionScalarWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<ExternalPlatformConnectionScalarWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionCountAggregateInput {
    pub id: Option<bool>,
    pub firm_id: Option<bool>,
    pub platform: Option<bool>,
    pub platform_label: Option<bool>,
    pub credentials_encrypted: Option<bool>,
    pub sync_status: Option<bool>,
    pub last_sync_at: Option<bool>,
    pub last_sync_error: Option<bool>,
    pub sync_frequency: Option<bool>,
    pub field_mapping: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionAvgAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionSumAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionMinAggregateInput {
    pub id: Option<bool>,
    pub firm_id: Option<bool>,
    pub platform_label: Option<bool>,
    pub credentials_encrypted: Option<bool>,
    pub last_sync_at: Option<bool>,
    pub last_sync_error: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionMaxAggregateInput {
    pub id: Option<bool>,
    pub firm_id: Option<bool>,
    pub platform_label: Option<bool>,
    pub credentials_encrypted: Option<bool>,
    pub last_sync_at: Option<bool>,
    pub last_sync_error: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionOrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub firm_id: Option<crate::shared::filters::SortOrder>,
    pub platform: Option<crate::shared::filters::SortOrder>,
    pub platform_label: Option<crate::shared::filters::SortOrder>,
    pub credentials_encrypted: Option<crate::shared::filters::SortOrder>,
    pub sync_status: Option<crate::shared::filters::SortOrder>,
    pub last_sync_at: Option<crate::shared::filters::SortOrder>,
    pub last_sync_error: Option<crate::shared::filters::SortOrder>,
    pub sync_frequency: Option<crate::shared::filters::SortOrder>,
    pub field_mapping: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub updated_at: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<ExternalPlatformConnectionCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<ExternalPlatformConnectionAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<ExternalPlatformConnectionSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<ExternalPlatformConnectionMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<ExternalPlatformConnectionMaxAggregateInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionAggregateInput {
    #[serde(rename = "where")]
    pub r#where: Option<ExternalPlatformConnectionWhereInput>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<ExternalPlatformConnectionCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<ExternalPlatformConnectionAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<ExternalPlatformConnectionSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<ExternalPlatformConnectionMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<ExternalPlatformConnectionMaxAggregateInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMapping {
    pub id: String,
    pub connection_id: String,
    pub external_entity_type: String,
    pub external_entity_id: String,
    pub internal_entity_type: String,
    pub internal_entity_id: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connection: Option<Box<crate::external_platforms::ExternalPlatformConnection>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub connection_id: Option<crate::shared::filters::StringFilter>,
    pub external_entity_type: Option<crate::shared::filters::StringFilter>,
    pub external_entity_id: Option<crate::shared::filters::StringFilter>,
    pub internal_entity_type: Option<crate::shared::filters::StringFilter>,
    pub internal_entity_id: Option<crate::shared::filters::StringFilter>,
    pub last_sync_at: Option<crate::shared::filters::DateTimeNullableFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub updated_at: Option<crate::shared::filters::DateTimeFilter>,
    pub connection: Option<crate::external_platforms::ExternalPlatformConnectionRelationFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<ExternalEntityMappingWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<ExternalEntityMappingWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<ExternalEntityMappingWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingRelationFilter {
    pub is: Option<Box<crate::external_platforms::ExternalEntityMappingWhereInput>>,
    pub is_not: Option<Box<crate::external_platforms::ExternalEntityMappingWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingListRelationFilter {
    pub some: Option<Box<crate::external_platforms::ExternalEntityMappingWhereInput>>,
    pub every: Option<Box<crate::external_platforms::ExternalEntityMappingWhereInput>>,
    pub none: Option<Box<crate::external_platforms::ExternalEntityMappingWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingWhereUniqueInput {
    pub id: Option<String>,
    pub connection_id: Option<String>,
    pub external_entity_type: Option<String>,
    pub external_entity_id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingOrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub connection_id: Option<crate::shared::filters::SortOrder>,
    pub external_entity_type: Option<crate::shared::filters::SortOrder>,
    pub external_entity_id: Option<crate::shared::filters::SortOrder>,
    pub internal_entity_type: Option<crate::shared::filters::SortOrder>,
    pub internal_entity_id: Option<crate::shared::filters::SortOrder>,
    pub last_sync_at: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub updated_at: Option<crate::shared::filters::SortOrder>,
    pub connection:
        Option<Box<crate::external_platforms::ExternalPlatformConnectionOrderByWithRelationInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingSelect {
    pub id: Option<bool>,
    pub connection_id: Option<bool>,
    pub external_entity_type: Option<bool>,
    pub external_entity_id: Option<bool>,
    pub internal_entity_type: Option<bool>,
    pub internal_entity_id: Option<bool>,
    pub last_sync_at: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
    pub connection: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingInclude {
    pub connection: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingCreateInput {
    pub external_entity_type: String,
    pub external_entity_id: String,
    pub internal_entity_type: String,
    pub internal_entity_id: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
    pub connection: Option<Box<crate::external_platforms::ExternalPlatformConnectionCreateNestedOneWithoutExternalEntityMappingConnectionInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUncheckedCreateInput {
    pub connection_id: String,
    pub external_entity_type: String,
    pub external_entity_id: String,
    pub internal_entity_type: String,
    pub internal_entity_id: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingCreateManyInput {
    pub connection_id: String,
    pub external_entity_type: String,
    pub external_entity_id: String,
    pub internal_entity_type: String,
    pub internal_entity_id: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub connection: Option<Box<crate::external_platforms::ExternalPlatformConnectionUpdateOneRequiredWithoutExternalEntityMappingConnectionNestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUncheckedUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub connection_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUpdateManyMutationInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingUncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub connection_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub external_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_type: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub internal_entity_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionCreateWithoutExternalEntityMappingConnectionInput {
    pub platform: crate::external_platforms::ExternalPlatform,
    pub platform_label: Option<String>,
    pub credentials_encrypted: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
    pub last_sync_error: Option<String>,
    pub field_mapping: Option<serde_json::Value>,
    pub firm: Option<Box<crate::external_platforms::FirmCreateNestedOneWithoutExternalPlatformConnectionFirmInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUncheckedCreateWithoutExternalEntityMappingConnectionInput {
    pub firm_id: String,
    pub platform: crate::external_platforms::ExternalPlatform,
    pub platform_label: Option<String>,
    pub credentials_encrypted: String,
    pub last_sync_at: Option<chrono::DateTime<chrono::Utc>>,
    pub last_sync_error: Option<String>,
    pub field_mapping: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionCreateOrConnectWithoutExternalEntityMappingConnectionInput {
    pub r#where: Box<crate::external_platforms::ExternalPlatformConnectionWhereUniqueInput>,
    pub create: Box<crate::external_platforms::ExternalPlatformConnectionCreateWithoutExternalEntityMappingConnectionInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUpdateWithoutExternalEntityMappingConnectionInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub platform: Option<crate::external_platforms::ExternalPlatformFieldUpdateOperationsInput>,
    pub platform_label: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub credentials_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub sync_status: Option<crate::external_platforms::ExternalSyncStatusFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub last_sync_error: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub sync_frequency: Option<crate::external_platforms::ExternalSyncFrequencyFieldUpdateOperationsInput>,
    pub field_mapping: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub firm: Option<Box<crate::external_platforms::FirmUpdateOneRequiredWithoutExternalPlatformConnectionFirmNestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUncheckedUpdateWithoutExternalEntityMappingConnectionInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub firm_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub platform: Option<crate::external_platforms::ExternalPlatformFieldUpdateOperationsInput>,
    pub platform_label: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub credentials_encrypted: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub sync_status:
        Option<crate::external_platforms::ExternalSyncStatusFieldUpdateOperationsInput>,
    pub last_sync_at: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub last_sync_error: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub sync_frequency:
        Option<crate::external_platforms::ExternalSyncFrequencyFieldUpdateOperationsInput>,
    pub field_mapping: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionCreateNestedOneWithoutExternalEntityMappingConnectionInput {
    pub create: Option<Box<crate::external_platforms::ExternalPlatformConnectionCreateWithoutExternalEntityMappingConnectionInput>>,
    pub connect_or_create: Option<Box<crate::external_platforms::ExternalPlatformConnectionCreateOrConnectWithoutExternalEntityMappingConnectionInput>>,
    pub connect: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereUniqueInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUpsertWithoutExternalEntityMappingConnectionInput {
    pub update: Box<crate::external_platforms::ExternalPlatformConnectionUpdateWithoutExternalEntityMappingConnectionInput>,
    pub create: Box<crate::external_platforms::ExternalPlatformConnectionCreateWithoutExternalEntityMappingConnectionInput>,
    pub r#where: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUpdateOneRequiredWithoutExternalEntityMappingConnectionNestedInput {
    pub create: Option<Box<crate::external_platforms::ExternalPlatformConnectionCreateWithoutExternalEntityMappingConnectionInput>>,
    pub connect_or_create: Option<Box<crate::external_platforms::ExternalPlatformConnectionCreateOrConnectWithoutExternalEntityMappingConnectionInput>>,
    pub upsert: Option<Box<crate::external_platforms::ExternalPlatformConnectionUpsertWithoutExternalEntityMappingConnectionInput>>,
    pub connect: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereUniqueInput>>,
    pub update: Option<Box<crate::external_platforms::ExternalPlatformConnectionUpdateToOneWithWhereWithoutExternalEntityMappingConnectionInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalPlatformConnectionUpdateToOneWithWhereWithoutExternalEntityMappingConnectionInput {
    pub r#where: Option<Box<crate::external_platforms::ExternalPlatformConnectionWhereInput>>,
    pub data: Box<crate::external_platforms::ExternalPlatformConnectionUpdateWithoutExternalEntityMappingConnectionInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingScalarWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub connection_id: Option<crate::shared::filters::StringFilter>,
    pub external_entity_type: Option<crate::shared::filters::StringFilter>,
    pub external_entity_id: Option<crate::shared::filters::StringFilter>,
    pub internal_entity_type: Option<crate::shared::filters::StringFilter>,
    pub internal_entity_id: Option<crate::shared::filters::StringFilter>,
    pub last_sync_at: Option<crate::shared::filters::DateTimeNullableFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub updated_at: Option<crate::shared::filters::DateTimeFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<ExternalEntityMappingScalarWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<ExternalEntityMappingScalarWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<ExternalEntityMappingScalarWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingCountAggregateInput {
    pub id: Option<bool>,
    pub connection_id: Option<bool>,
    pub external_entity_type: Option<bool>,
    pub external_entity_id: Option<bool>,
    pub internal_entity_type: Option<bool>,
    pub internal_entity_id: Option<bool>,
    pub last_sync_at: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingAvgAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingSumAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingMinAggregateInput {
    pub id: Option<bool>,
    pub connection_id: Option<bool>,
    pub external_entity_type: Option<bool>,
    pub external_entity_id: Option<bool>,
    pub internal_entity_type: Option<bool>,
    pub internal_entity_id: Option<bool>,
    pub last_sync_at: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingMaxAggregateInput {
    pub id: Option<bool>,
    pub connection_id: Option<bool>,
    pub external_entity_type: Option<bool>,
    pub external_entity_id: Option<bool>,
    pub internal_entity_type: Option<bool>,
    pub internal_entity_id: Option<bool>,
    pub last_sync_at: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingOrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub connection_id: Option<crate::shared::filters::SortOrder>,
    pub external_entity_type: Option<crate::shared::filters::SortOrder>,
    pub external_entity_id: Option<crate::shared::filters::SortOrder>,
    pub internal_entity_type: Option<crate::shared::filters::SortOrder>,
    pub internal_entity_id: Option<crate::shared::filters::SortOrder>,
    pub last_sync_at: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub updated_at: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<ExternalEntityMappingCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<ExternalEntityMappingAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<ExternalEntityMappingSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<ExternalEntityMappingMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<ExternalEntityMappingMaxAggregateInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExternalEntityMappingAggregateInput {
    #[serde(rename = "where")]
    pub r#where: Option<ExternalEntityMappingWhereInput>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<ExternalEntityMappingCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<ExternalEntityMappingAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<ExternalEntityMappingSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<ExternalEntityMappingMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<ExternalEntityMappingMaxAggregateInput>,
}
