// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Firm {
    pub id: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub users: Vec<crate::models::user::User>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub name: Option<crate::shared::filters::StringFilter>,
    pub users: Option<crate::models::user::UserListRelationFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<FirmWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<FirmWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<FirmWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmRelationFilter {
    pub is: Option<Box<crate::models::firm::FirmWhereInput>>,
    pub is_not: Option<Box<crate::models::firm::FirmWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmListRelationFilter {
    pub some: Option<Box<crate::models::firm::FirmWhereInput>>,
    pub every: Option<Box<crate::models::firm::FirmWhereInput>>,
    pub none: Option<Box<crate::models::firm::FirmWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmWhereUniqueInput {
    pub id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmOrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub name: Option<crate::shared::filters::SortOrder>,
    pub users: Option<Box<crate::models::user::UserOrderByWithRelationInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmSelect {
    pub id: Option<bool>,
    pub name: Option<bool>,
    pub users: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmInclude {
    pub users: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCreateInput {
    pub name: String,
    pub users: Option<Box<crate::models::firm::UserCreateNestedManyWithoutFirmUsersInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUncheckedCreateInput {
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCreateManyInput {
    pub name: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub users: Option<Box<crate::models::firm::UserUpdateManyWithoutFirmUsersNestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUncheckedUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpdateManyMutationInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserCreateWithoutFirmUsersInput {
    pub email: String,
    pub posts: Option<Box<crate::models::user::PostCreateNestedManyWithoutUserPostsInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUncheckedCreateWithoutFirmUsersInput {
    pub email: String,
    pub firm_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserCreateOrConnectWithoutFirmUsersInput {
    pub r#where: Box<crate::models::user::UserWhereUniqueInput>,
    pub create: Box<crate::models::firm::UserCreateWithoutFirmUsersInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUpdateWithoutFirmUsersInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub role: Option<crate::enums::role::RoleFieldUpdateOperationsInput>,
    pub posts: Option<Box<crate::models::user::PostUpdateManyWithoutUserPostsNestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUncheckedUpdateWithoutFirmUsersInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub role: Option<crate::enums::role::RoleFieldUpdateOperationsInput>,
    pub firm_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserCreateNestedManyWithoutFirmUsersInput {
    pub create: Option<
        crate::shared::filters::OneOrMany<crate::models::firm::UserCreateWithoutFirmUsersInput>,
    >,
    pub connect_or_create:
        Option<Vec<crate::models::firm::UserCreateOrConnectWithoutFirmUsersInput>>,
    pub create_many: Option<Box<crate::models::firm::UserCreateManyFirmUsersInputEnvelope>>,
    pub connect:
        Option<crate::shared::filters::OneOrMany<crate::models::user::UserWhereUniqueInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserCreateManyFirmUsersInputEnvelope {
    pub data: Vec<crate::models::firm::UserCreateManyFirmUsersInput>,
    pub skip_duplicates: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserCreateManyFirmUsersInput {
    pub email: String,
    pub firm_id: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUpdateManyWithoutFirmUsersNestedInput {
    pub create: Option<
        crate::shared::filters::OneOrMany<crate::models::firm::UserCreateWithoutFirmUsersInput>,
    >,
    pub connect_or_create:
        Option<Vec<crate::models::firm::UserCreateOrConnectWithoutFirmUsersInput>>,
    pub upsert: Option<Vec<crate::models::firm::UserUpsertWithWhereUniqueWithoutFirmUsersInput>>,
    pub create_many: Option<Box<crate::models::firm::UserCreateManyFirmUsersInputEnvelope>>,
    pub set: Option<Vec<crate::models::user::UserWhereUniqueInput>>,
    pub disconnect: Option<Vec<crate::models::user::UserWhereUniqueInput>>,
    pub delete: Option<Vec<crate::models::user::UserWhereUniqueInput>>,
    pub connect: Option<Vec<crate::models::user::UserWhereUniqueInput>>,
    pub update: Option<Vec<crate::models::firm::UserUpdateWithWhereUniqueWithoutFirmUsersInput>>,
    pub update_many: Option<Vec<crate::models::firm::UserUpdateManyWithWhereWithoutFirmUsersInput>>,
    pub delete_many: Option<Vec<crate::models::user::UserScalarWhereInput>>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUpsertWithWhereUniqueWithoutFirmUsersInput {
    pub r#where: Box<crate::models::user::UserWhereUniqueInput>,
    pub update: Box<crate::models::firm::UserUpdateWithoutFirmUsersInput>,
    pub create: Box<crate::models::firm::UserCreateWithoutFirmUsersInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUpdateWithWhereUniqueWithoutFirmUsersInput {
    pub r#where: Box<crate::models::user::UserWhereUniqueInput>,
    pub data: Box<crate::models::firm::UserUpdateWithoutFirmUsersInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUpdateManyWithWhereWithoutFirmUsersInput {
    pub r#where: Box<crate::models::user::UserScalarWhereInput>,
    pub data: Box<crate::models::user::UserUpdateManyMutationInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmScalarWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub name: Option<crate::shared::filters::StringFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<FirmScalarWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<FirmScalarWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<FirmScalarWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCountAggregateInput {
    pub id: Option<bool>,
    pub name: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmAvgAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmSumAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmMinAggregateInput {
    pub id: Option<bool>,
    pub name: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmMaxAggregateInput {
    pub id: Option<bool>,
    pub name: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmOrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub name: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<FirmCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<FirmAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<FirmSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<FirmMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<FirmMaxAggregateInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmAggregateInput {
    #[serde(rename = "where")]
    pub r#where: Option<FirmWhereInput>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<FirmCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<FirmAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<FirmSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<FirmMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<FirmMaxAggregateInput>,
}
