// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct User {
    pub id: String,
    pub email: String,
    pub role: crate::enums::role::Role,
    pub firm_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub firm: Option<Box<crate::models::firm::Firm>>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub posts: Vec<crate::models::post::Post>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub email: Option<crate::shared::filters::StringFilter>,
    pub role: Option<crate::enums::role::RoleFilter>,
    pub firm_id: Option<crate::shared::filters::StringFilter>,
    pub firm: Option<crate::models::firm::FirmRelationFilter>,
    pub posts: Option<crate::models::post::PostListRelationFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<UserWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<UserWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<UserWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserRelationFilter {
    pub is: Option<Box<crate::models::user::UserWhereInput>>,
    pub is_not: Option<Box<crate::models::user::UserWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserListRelationFilter {
    pub some: Option<Box<crate::models::user::UserWhereInput>>,
    pub every: Option<Box<crate::models::user::UserWhereInput>>,
    pub none: Option<Box<crate::models::user::UserWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserWhereUniqueInput {
    pub id: Option<String>,
    pub email: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserOrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub email: Option<crate::shared::filters::SortOrder>,
    pub role: Option<crate::shared::filters::SortOrder>,
    pub firm_id: Option<crate::shared::filters::SortOrder>,
    pub firm: Option<Box<crate::models::firm::FirmOrderByWithRelationInput>>,
    pub posts: Option<Box<crate::models::post::PostOrderByWithRelationInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserSelect {
    pub id: Option<bool>,
    pub email: Option<bool>,
    pub role: Option<bool>,
    pub firm_id: Option<bool>,
    pub firm: Option<bool>,
    pub posts: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserInclude {
    pub firm: Option<bool>,
    pub posts: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserCreateInput {
    pub email: String,
    pub firm: Option<Box<crate::models::user::FirmCreateNestedOneWithoutUserFirmInput>>,
    pub posts: Option<Box<crate::models::user::PostCreateNestedManyWithoutUserPostsInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUncheckedCreateInput {
    pub email: String,
    pub firm_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserCreateManyInput {
    pub email: String,
    pub firm_id: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub role: Option<crate::enums::role::RoleFieldUpdateOperationsInput>,
    pub firm: Option<Box<crate::models::user::FirmUpdateOneRequiredWithoutUserFirmNestedInput>>,
    pub posts: Option<Box<crate::models::user::PostUpdateManyWithoutUserPostsNestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUncheckedUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub role: Option<crate::enums::role::RoleFieldUpdateOperationsInput>,
    pub firm_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUpdateManyMutationInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub role: Option<crate::enums::role::RoleFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserUncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub role: Option<crate::enums::role::RoleFieldUpdateOperationsInput>,
    pub firm_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCreateWithoutUserFirmInput {
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUncheckedCreateWithoutUserFirmInput {
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCreateOrConnectWithoutUserFirmInput {
    pub r#where: Box<crate::models::firm::FirmWhereUniqueInput>,
    pub create: Box<crate::models::user::FirmCreateWithoutUserFirmInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpdateWithoutUserFirmInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUncheckedUpdateWithoutUserFirmInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmCreateNestedOneWithoutUserFirmInput {
    pub create: Option<Box<crate::models::user::FirmCreateWithoutUserFirmInput>>,
    pub connect_or_create:
        Option<Box<crate::models::user::FirmCreateOrConnectWithoutUserFirmInput>>,
    pub connect: Option<Box<crate::models::firm::FirmWhereUniqueInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpsertWithoutUserFirmInput {
    pub update: Box<crate::models::user::FirmUpdateWithoutUserFirmInput>,
    pub create: Box<crate::models::user::FirmCreateWithoutUserFirmInput>,
    pub r#where: Option<Box<crate::models::firm::FirmWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpdateOneRequiredWithoutUserFirmNestedInput {
    pub create: Option<Box<crate::models::user::FirmCreateWithoutUserFirmInput>>,
    pub connect_or_create:
        Option<Box<crate::models::user::FirmCreateOrConnectWithoutUserFirmInput>>,
    pub upsert: Option<Box<crate::models::user::FirmUpsertWithoutUserFirmInput>>,
    pub connect: Option<Box<crate::models::firm::FirmWhereUniqueInput>>,
    pub update: Option<Box<crate::models::user::FirmUpdateToOneWithWhereWithoutUserFirmInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FirmUpdateToOneWithWhereWithoutUserFirmInput {
    pub r#where: Option<Box<crate::models::firm::FirmWhereInput>>,
    pub data: Box<crate::models::user::FirmUpdateWithoutUserFirmInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostCreateWithoutUserPostsInput {
    pub title: String,
    pub body: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostUncheckedCreateWithoutUserPostsInput {
    pub title: String,
    pub body: Option<String>,
    pub author_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostCreateOrConnectWithoutUserPostsInput {
    pub r#where: Box<crate::models::post::PostWhereUniqueInput>,
    pub create: Box<crate::models::user::PostCreateWithoutUserPostsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostUpdateWithoutUserPostsInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub title: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub body: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostUncheckedUpdateWithoutUserPostsInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub title: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub body: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub author_id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostCreateNestedManyWithoutUserPostsInput {
    pub create: Option<
        crate::shared::filters::OneOrMany<crate::models::user::PostCreateWithoutUserPostsInput>,
    >,
    pub connect_or_create:
        Option<Vec<crate::models::user::PostCreateOrConnectWithoutUserPostsInput>>,
    pub create_many: Option<Box<crate::models::user::PostCreateManyUserPostsInputEnvelope>>,
    pub connect:
        Option<crate::shared::filters::OneOrMany<crate::models::post::PostWhereUniqueInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostCreateManyUserPostsInputEnvelope {
    pub data: Vec<crate::models::user::PostCreateManyUserPostsInput>,
    pub skip_duplicates: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostCreateManyUserPostsInput {
    pub title: String,
    pub body: Option<String>,
    pub author_id: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostUpdateManyWithoutUserPostsNestedInput {
    pub create: Option<
        crate::shared::filters::OneOrMany<crate::models::user::PostCreateWithoutUserPostsInput>,
    >,
    pub connect_or_create:
        Option<Vec<crate::models::user::PostCreateOrConnectWithoutUserPostsInput>>,
    pub upsert: Option<Vec<crate::models::user::PostUpsertWithWhereUniqueWithoutUserPostsInput>>,
    pub create_many: Option<Box<crate::models::user::PostCreateManyUserPostsInputEnvelope>>,
    pub set: Option<Vec<crate::models::post::PostWhereUniqueInput>>,
    pub disconnect: Option<Vec<crate::models::post::PostWhereUniqueInput>>,
    pub delete: Option<Vec<crate::models::post::PostWhereUniqueInput>>,
    pub connect: Option<Vec<crate::models::post::PostWhereUniqueInput>>,
    pub update: Option<Vec<crate::models::user::PostUpdateWithWhereUniqueWithoutUserPostsInput>>,
    pub update_many: Option<Vec<crate::models::user::PostUpdateManyWithWhereWithoutUserPostsInput>>,
    pub delete_many: Option<Vec<crate::models::post::PostScalarWhereInput>>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostUpsertWithWhereUniqueWithoutUserPostsInput {
    pub r#where: Box<crate::models::post::PostWhereUniqueInput>,
    pub update: Box<crate::models::user::PostUpdateWithoutUserPostsInput>,
    pub create: Box<crate::models::user::PostCreateWithoutUserPostsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostUpdateWithWhereUniqueWithoutUserPostsInput {
    pub r#where: Box<crate::models::post::PostWhereUniqueInput>,
    pub data: Box<crate::models::user::PostUpdateWithoutUserPostsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostUpdateManyWithWhereWithoutUserPostsInput {
    pub r#where: Box<crate::models::post::PostScalarWhereInput>,
    pub data: Box<crate::models::post::PostUpdateManyMutationInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserScalarWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub email: Option<crate::shared::filters::StringFilter>,
    pub role: Option<crate::enums::role::RoleFilter>,
    pub firm_id: Option<crate::shared::filters::StringFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<UserScalarWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<UserScalarWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<UserScalarWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserCountAggregateInput {
    pub id: Option<bool>,
    pub email: Option<bool>,
    pub role: Option<bool>,
    pub firm_id: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserAvgAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserSumAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserMinAggregateInput {
    pub id: Option<bool>,
    pub email: Option<bool>,
    pub firm_id: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserMaxAggregateInput {
    pub id: Option<bool>,
    pub email: Option<bool>,
    pub firm_id: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserOrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub email: Option<crate::shared::filters::SortOrder>,
    pub role: Option<crate::shared::filters::SortOrder>,
    pub firm_id: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<UserCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<UserAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<UserSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<UserMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<UserMaxAggregateInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserAggregateInput {
    #[serde(rename = "where")]
    pub r#where: Option<UserWhereInput>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<UserCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<UserAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<UserSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<UserMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<UserMaxAggregateInput>,
}
