// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use sqlx::Row as _;

impl sqlx::FromRow<'_, sqlx::postgres::PgRow> for crate::demand_letters::DemandLetter {
    fn from_row(row: &sqlx::postgres::PgRow) -> sqlx::Result<Self> {
        Ok(crate::demand_letters::DemandLetter {
            id: row.try_get("id")?,
            firm_id: row.try_get("firm_id")?,
            upload_form: row.try_get("upload_form")?,
            case_id: row.try_get("case_id")?,
            processing_status: row.try_get("processing_status")?,
            created_at: row.try_get("created_at")?,
            updated_at: row.try_get("updated_at")?,
            firm: None,
            documents: Vec::new(),
            case: None,
            line_items: Vec::new(),
            processing: None,
        })
    }
}

pub(crate) fn push_demand_letter_where(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Postgres>,
    w: &crate::demand_letters::DemandLetterWhereInput,
) -> bool {
    let mut any = false;
    if let Some(f) = &w.id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "id", f);
    }
    if let Some(f) = &w.firm_id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "firm_id", f);
    }
    if let Some(f) = &w.upload_form {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_json_filter(qb, "upload_form", f);
    }
    if let Some(f) = &w.case_id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "case_id", f);
    }
    if let Some(f) = &w.processing_status {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_processing_status_filter(
            qb,
            "processing_status",
            f,
        );
    }
    if let Some(f) = &w.created_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_filter(qb, "created_at", f);
    }
    if let Some(f) = &w.updated_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_filter(qb, "updated_at", f);
    }
    if let Some(rel) = &w.firm {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"firms\" t WHERE t.\"id\" = \"demand_letters\".\"firm_id\" AND (");
            if !crate::engine::sqlx_postgres::firms::push_firm_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"firms\" t WHERE t.\"id\" = \"demand_letters\".\"firm_id\" AND (");
            if !crate::engine::sqlx_postgres::firms::push_firm_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.documents {
        if let Some(sub) = &rel.every {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"documents\" t WHERE t.\"demand_letter_id\" = \"demand_letters\".\"id\" AND NOT (");
            if !crate::engine::sqlx_postgres::documents::push_document_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.some {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"documents\" t WHERE t.\"demand_letter_id\" = \"demand_letters\".\"id\" AND (");
            if !crate::engine::sqlx_postgres::documents::push_document_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.none {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"documents\" t WHERE t.\"demand_letter_id\" = \"demand_letters\".\"id\" AND (");
            if !crate::engine::sqlx_postgres::documents::push_document_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.case {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"cases\" t WHERE t.\"id\" = \"demand_letters\".\"case_id\" AND (");
            if !crate::engine::sqlx_postgres::cases::push_case_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"cases\" t WHERE t.\"id\" = \"demand_letters\".\"case_id\" AND (");
            if !crate::engine::sqlx_postgres::cases::push_case_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.line_items {
        if let Some(sub) = &rel.every {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"line_items\" t WHERE t.\"demand_letter_id\" = \"demand_letters\".\"id\" AND NOT (");
            if !crate::engine::sqlx_postgres::billing::push_line_item_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.some {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"line_items\" t WHERE t.\"demand_letter_id\" = \"demand_letters\".\"id\" AND (");
            if !crate::engine::sqlx_postgres::billing::push_line_item_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.none {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"line_items\" t WHERE t.\"demand_letter_id\" = \"demand_letters\".\"id\" AND (");
            if !crate::engine::sqlx_postgres::billing::push_line_item_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    // TODO(prisma-rust-generator): multi-FK to-one relation `processing` on `DemandLetter` skipped
    // (composite FK relation filters not yet supported by sqlx-postgres engine).
    let _ = &w.processing;
    if let Some(group) = &w.and {
        for sub in group {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("(");
            if !push_demand_letter_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
    }
    if let Some(group) = &w.or {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("(");
        let mut first = true;
        for sub in group {
            if !first {
                qb.push(" OR ");
            }
            first = false;
            qb.push("(");
            if !push_demand_letter_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
        qb.push(")");
    }
    if let Some(group) = &w.not {
        for sub in group {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT (");
            if !push_demand_letter_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
    }
    any
}

impl crate::demand_letters::DemandLetter {
    pub async fn find_unique<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterWhereUniqueInput,
    ) -> sqlx::Result<Option<Self>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let cols = "\"id\", \"firm_id\", \"upload_form\", \"case_id\", \"processing_status\", \"created_at\", \"updated_at\"";
        let mut qb =
            sqlx::QueryBuilder::new(format!(r#"SELECT {} FROM "demand_letters" WHERE "#, cols,));
        // For v1, support only the @id field. Composite uniques are out of scope.
        // The WhereUniqueInput has Option<T> per @id/@unique field; we pick the
        // first Some(). Multi-Some inputs cover composite uniques — TODO Task v2.
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(value.clone());
        } else {
            return Ok(None);
        }
        qb.build_query_as::<Self>().fetch_optional(executor).await
    }
}

impl crate::demand_letters::DemandLetter {
    pub async fn find_first<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterWhereInput,
    ) -> sqlx::Result<Option<Self>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT "id", "firm_id", "upload_form", "case_id", "processing_status", "created_at", "updated_at" FROM "demand_letters" WHERE "#,
        );
        if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_where(&mut qb, w) {
            qb.push("TRUE");
        }
        qb.push(" LIMIT 1");
        qb.build_query_as::<Self>().fetch_optional(executor).await
    }
}

pub struct DemandLetterFindManyBuilder<'a, E> {
    executor: E,
    where_input: &'a crate::demand_letters::DemandLetterWhereInput,
    order_by: Vec<crate::demand_letters::DemandLetterOrderByWithRelationInput>,
    take: Option<i64>,
    skip: Option<i64>,
}

impl<'a, E> DemandLetterFindManyBuilder<'a, E> {
    pub fn order_by(
        mut self,
        order_by: &[crate::demand_letters::DemandLetterOrderByWithRelationInput],
    ) -> Self {
        self.order_by = order_by.to_vec();
        self
    }

    pub fn take(mut self, n: i64) -> Self {
        self.take = Some(n);
        self
    }

    pub fn skip(mut self, n: i64) -> Self {
        self.skip = Some(n);
        self
    }

    pub async fn exec<'e>(self) -> sqlx::Result<Vec<crate::demand_letters::DemandLetter>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT "id", "firm_id", "upload_form", "case_id", "processing_status", "created_at", "updated_at" FROM "demand_letters" WHERE "#,
        );
        if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_where(
            &mut qb,
            self.where_input,
        ) {
            qb.push("TRUE");
        }
        if !self.order_by.is_empty() {
            qb.push(" ORDER BY ");
            let mut first = true;
            for ob in &self.order_by {
                if let Some(o) = ob.id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.firm_id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"firm_id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.upload_form {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"upload_form\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.case_id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"case_id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.processing_status {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"processing_status\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.created_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"created_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.updated_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"updated_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                // TODO(prisma-rust-generator): sorting by relation `firm` not yet supported.
                let _ = &ob.firm;
                // TODO(prisma-rust-generator): sorting by relation `documents` not yet supported.
                let _ = &ob.documents;
                // TODO(prisma-rust-generator): sorting by relation `case` not yet supported.
                let _ = &ob.case;
                // TODO(prisma-rust-generator): sorting by relation `lineItems` not yet supported.
                let _ = &ob.line_items;
                // TODO(prisma-rust-generator): sorting by relation `processing` not yet supported.
                let _ = &ob.processing;
            }
        }
        if let Some(n) = self.take {
            qb.push(" LIMIT ");
            qb.push_bind(n);
        }
        if let Some(n) = self.skip {
            qb.push(" OFFSET ");
            qb.push_bind(n);
        }
        qb.build_query_as::<crate::demand_letters::DemandLetter>()
            .fetch_all(self.executor)
            .await
    }
}

impl crate::demand_letters::DemandLetter {
    pub fn find_many<'a, E>(
        executor: E,
        w: &'a crate::demand_letters::DemandLetterWhereInput,
    ) -> DemandLetterFindManyBuilder<'a, E> {
        DemandLetterFindManyBuilder {
            executor,
            where_input: w,
            order_by: Vec::new(),
            take: None,
            skip: None,
        }
    }
}

impl crate::demand_letters::DemandLetter {
    pub async fn count<'e, E>(
        executor: E,
        w: Option<&crate::demand_letters::DemandLetterWhereInput>,
    ) -> sqlx::Result<i64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"SELECT COUNT(*) FROM "demand_letters" WHERE "#);
        if let Some(w) = w {
            if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_where(&mut qb, w) {
                qb.push("TRUE");
            }
        } else {
            qb.push("TRUE");
        }
        let row = qb.build_query_as::<(i64,)>().fetch_one(executor).await?;
        Ok(row.0)
    }
}

impl crate::demand_letters::DemandLetter {
    pub async fn create<'e, E>(
        executor: E,
        input: crate::demand_letters::DemandLetterUncheckedCreateInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut cols = String::new();
        cols.push_str("\"firm_id\"");
        cols.push_str(", ");
        cols.push_str("\"upload_form\"");
        cols.push_str(", ");
        cols.push_str("\"case_id\"");
        let mut qb = sqlx::QueryBuilder::new(format!(
            r#"INSERT INTO "demand_letters" ({}) VALUES ("#,
            cols,
        ));
        qb.push_bind(input.firm_id);
        qb.push(", ");
        qb.push_bind(input.upload_form);
        qb.push(", ");
        qb.push_bind(input.case_id);
        qb.push(r#") RETURNING "id", "firm_id", "upload_form", "case_id", "processing_status", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::demand_letters::DemandLetter {
    pub async fn create_many<'e, E>(
        executor: E,
        inputs: &[crate::demand_letters::DemandLetterUncheckedCreateInput],
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        if inputs.is_empty() {
            return Ok(0);
        }
        let mut qb = sqlx::QueryBuilder::new(
            r#"INSERT INTO "demand_letters" ("firm_id", "upload_form", "case_id") "#,
        );
        qb.push_values(inputs, |mut row, input| {
            row.push_bind(input.firm_id.clone());
            row.push_bind(input.upload_form.clone());
            row.push_bind(input.case_id.clone());
        });
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

impl crate::demand_letters::DemandLetter {
    pub async fn update<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterWhereUniqueInput,
        input: crate::demand_letters::DemandLetterUncheckedUpdateInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"UPDATE "demand_letters" SET "#);
        let mut first = true;
        if let Some(op) = input.id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.firm_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"firm_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.upload_form {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"upload_form\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.case_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"case_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.processing_status {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"processing_status\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.created_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"created_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.updated_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"updated_at\" = ");
                qb.push_bind(v);
            }
        }
        if first {
            // Nothing to update — fall back to a plain find_unique so the
            // caller still gets the row back (or RowNotFound if absent).
            return Self::find_unique(executor, w)
                .await?
                .ok_or(sqlx::Error::RowNotFound);
        }
        qb.push(" WHERE ");
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(value.clone());
        } else {
            return Err(sqlx::Error::RowNotFound);
        }
        qb.push(r#" RETURNING "id", "firm_id", "upload_form", "case_id", "processing_status", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::demand_letters::DemandLetter {
    pub async fn update_many<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterWhereInput,
        input: crate::demand_letters::DemandLetterUncheckedUpdateManyInput,
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"UPDATE "demand_letters" SET "#);
        let mut first = true;
        if let Some(op) = input.id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.firm_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"firm_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.upload_form {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"upload_form\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.case_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"case_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.processing_status {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"processing_status\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.created_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"created_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.updated_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"updated_at\" = ");
                qb.push_bind(v);
            }
        }
        if first {
            // No-op update — return 0 rows affected without issuing SQL.
            return Ok(0);
        }
        qb.push(" WHERE ");
        if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_where(&mut qb, w) {
            qb.push("TRUE");
        }
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

impl crate::demand_letters::DemandLetter {
    pub async fn delete<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterWhereUniqueInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"DELETE FROM "demand_letters" WHERE "#);
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(value.clone());
        } else {
            return Err(sqlx::Error::RowNotFound);
        }
        qb.push(r#" RETURNING "id", "firm_id", "upload_form", "case_id", "processing_status", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::demand_letters::DemandLetter {
    pub async fn delete_many<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterWhereInput,
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"DELETE FROM "demand_letters" WHERE "#);
        if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_where(&mut qb, w) {
            qb.push("TRUE");
        }
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterCountAggregateResult {
    pub id: Option<i64>,
    pub firm_id: Option<i64>,
    pub upload_form: Option<i64>,
    pub case_id: Option<i64>,
    pub processing_status: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<i64>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterAvgAggregateResult {}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterSumAggregateResult {}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterMinAggregateResult {
    pub id: Option<String>,
    pub firm_id: Option<String>,
    pub case_id: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterMaxAggregateResult {
    pub id: Option<String>,
    pub firm_id: Option<String>,
    pub case_id: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterAggregateResult {
    #[serde(rename = "_count")]
    pub aggregate_count: Option<DemandLetterCountAggregateResult>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<DemandLetterAvgAggregateResult>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<DemandLetterSumAggregateResult>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<DemandLetterMinAggregateResult>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<DemandLetterMaxAggregateResult>,
}

impl crate::demand_letters::DemandLetter {
    pub async fn aggregate<'e, E>(
        executor: E,
        input: &crate::demand_letters::DemandLetterAggregateInput,
    ) -> sqlx::Result<DemandLetterAggregateResult>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT COUNT(*) AS count_all, COUNT("id") AS count_id, COUNT("firm_id") AS count_firm_id, COUNT("upload_form") AS count_upload_form, COUNT("case_id") AS count_case_id, COUNT("processing_status") AS count_processing_status, COUNT("created_at") AS count_created_at, COUNT("updated_at") AS count_updated_at, MIN("id") AS min_id, MAX("id") AS max_id, MIN("firm_id") AS min_firm_id, MAX("firm_id") AS max_firm_id, MIN("case_id") AS min_case_id, MAX("case_id") AS max_case_id, MIN("created_at") AS min_created_at, MAX("created_at") AS max_created_at, MIN("updated_at") AS min_updated_at, MAX("updated_at") AS max_updated_at FROM "demand_letters" WHERE "#,
        );
        if let Some(w) = &input.r#where {
            if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_where(&mut qb, w) {
                qb.push("TRUE");
            }
        } else {
            qb.push("TRUE");
        }
        let row = qb.build().fetch_one(executor).await?;
        use sqlx::Row;
        Ok(DemandLetterAggregateResult {
            aggregate_count: input
                .aggregate_count
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(DemandLetterCountAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_id")?
                        } else {
                            None
                        },
                        firm_id: if req.firm_id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_firm_id")?
                        } else {
                            None
                        },
                        upload_form: if req.upload_form.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_upload_form")?
                        } else {
                            None
                        },
                        case_id: if req.case_id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_case_id")?
                        } else {
                            None
                        },
                        processing_status: if req.processing_status.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_processing_status")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_created_at")?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_updated_at")?
                        } else {
                            None
                        },
                        aggregate_all: if req.aggregate_all.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_all")?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_avg: input
                .aggregate_avg
                .as_ref()
                .map(|_req| -> sqlx::Result<_> { Ok(DemandLetterAvgAggregateResult {}) })
                .transpose()?,
            aggregate_sum: input
                .aggregate_sum
                .as_ref()
                .map(|_req| -> sqlx::Result<_> { Ok(DemandLetterSumAggregateResult {}) })
                .transpose()?,
            aggregate_min: input
                .aggregate_min
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(DemandLetterMinAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_id")?
                        } else {
                            None
                        },
                        firm_id: if req.firm_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_firm_id")?
                        } else {
                            None
                        },
                        case_id: if req.case_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_case_id")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_created_at",
                            )?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_updated_at",
                            )?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_max: input
                .aggregate_max
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(DemandLetterMaxAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_id")?
                        } else {
                            None
                        },
                        firm_id: if req.firm_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_firm_id")?
                        } else {
                            None
                        },
                        case_id: if req.case_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_case_id")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_created_at",
                            )?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_updated_at",
                            )?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
        })
    }
}

impl sqlx::FromRow<'_, sqlx::postgres::PgRow> for crate::demand_letters::DemandLetterProcessing {
    fn from_row(row: &sqlx::postgres::PgRow) -> sqlx::Result<Self> {
        Ok(crate::demand_letters::DemandLetterProcessing {
            id: row.try_get("id")?,
            demand_letter_id: row.try_get("demand_letter_id")?,
            case_id: row.try_get("case_id")?,
            firm_id: row.try_get("firm_id")?,
            processing_status: row.try_get("processing_status")?,
            started_at: row.try_get("started_at")?,
            completed_at: row.try_get("completed_at")?,
            processing_status_message: row.try_get("processing_status_message")?,
            created_at: row.try_get("created_at")?,
            updated_at: row.try_get("updated_at")?,
            demand_letter: None,
            case: None,
            firm: None,
        })
    }
}

pub(crate) fn push_demand_letter_processing_where(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Postgres>,
    w: &crate::demand_letters::DemandLetterProcessingWhereInput,
) -> bool {
    let mut any = false;
    if let Some(f) = &w.id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_int_filter(qb, "id", f);
    }
    if let Some(f) = &w.demand_letter_id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "demand_letter_id", f);
    }
    if let Some(f) = &w.case_id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "case_id", f);
    }
    if let Some(f) = &w.firm_id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "firm_id", f);
    }
    if let Some(f) = &w.processing_status {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_processing_status_filter(
            qb,
            "processing_status",
            f,
        );
    }
    if let Some(f) = &w.started_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_nullable_filter(qb, "started_at", f);
    }
    if let Some(f) = &w.completed_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_nullable_filter(qb, "completed_at", f);
    }
    if let Some(f) = &w.processing_status_message {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_nullable_filter(
            qb,
            "processing_status_message",
            f,
        );
    }
    if let Some(f) = &w.created_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_filter(qb, "created_at", f);
    }
    if let Some(f) = &w.updated_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_filter(qb, "updated_at", f);
    }
    if let Some(rel) = &w.demand_letter {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"demand_letters\" t WHERE t.\"id\" = \"demand_letter_processings\".\"demand_letter_id\" AND (");
            if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"demand_letters\" t WHERE t.\"id\" = \"demand_letter_processings\".\"demand_letter_id\" AND (");
            if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.case {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"cases\" t WHERE t.\"id\" = \"demand_letter_processings\".\"case_id\" AND (");
            if !crate::engine::sqlx_postgres::cases::push_case_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"cases\" t WHERE t.\"id\" = \"demand_letter_processings\".\"case_id\" AND (");
            if !crate::engine::sqlx_postgres::cases::push_case_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.firm {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"firms\" t WHERE t.\"id\" = \"demand_letter_processings\".\"firm_id\" AND (");
            if !crate::engine::sqlx_postgres::firms::push_firm_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"firms\" t WHERE t.\"id\" = \"demand_letter_processings\".\"firm_id\" AND (");
            if !crate::engine::sqlx_postgres::firms::push_firm_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(group) = &w.and {
        for sub in group {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("(");
            if !push_demand_letter_processing_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
    }
    if let Some(group) = &w.or {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("(");
        let mut first = true;
        for sub in group {
            if !first {
                qb.push(" OR ");
            }
            first = false;
            qb.push("(");
            if !push_demand_letter_processing_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
        qb.push(")");
    }
    if let Some(group) = &w.not {
        for sub in group {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT (");
            if !push_demand_letter_processing_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
    }
    any
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn find_unique<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterProcessingWhereUniqueInput,
    ) -> sqlx::Result<Option<Self>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let cols = "\"id\", \"demand_letter_id\", \"case_id\", \"firm_id\", \"processing_status\", \"started_at\", \"completed_at\", \"processing_status_message\", \"created_at\", \"updated_at\"";
        let mut qb = sqlx::QueryBuilder::new(format!(
            r#"SELECT {} FROM "demand_letter_processings" WHERE "#,
            cols,
        ));
        // For v1, support only the @id field. Composite uniques are out of scope.
        // The WhereUniqueInput has Option<T> per @id/@unique field; we pick the
        // first Some(). Multi-Some inputs cover composite uniques — TODO Task v2.
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(*value);
        } else {
            return Ok(None);
        }
        qb.build_query_as::<Self>().fetch_optional(executor).await
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn find_first<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterProcessingWhereInput,
    ) -> sqlx::Result<Option<Self>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT "id", "demand_letter_id", "case_id", "firm_id", "processing_status", "started_at", "completed_at", "processing_status_message", "created_at", "updated_at" FROM "demand_letter_processings" WHERE "#,
        );
        if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_processing_where(
            &mut qb, w,
        ) {
            qb.push("TRUE");
        }
        qb.push(" LIMIT 1");
        qb.build_query_as::<Self>().fetch_optional(executor).await
    }
}

pub struct DemandLetterProcessingFindManyBuilder<'a, E> {
    executor: E,
    where_input: &'a crate::demand_letters::DemandLetterProcessingWhereInput,
    order_by: Vec<crate::demand_letters::DemandLetterProcessingOrderByWithRelationInput>,
    take: Option<i64>,
    skip: Option<i64>,
}

impl<'a, E> DemandLetterProcessingFindManyBuilder<'a, E> {
    pub fn order_by(
        mut self,
        order_by: &[crate::demand_letters::DemandLetterProcessingOrderByWithRelationInput],
    ) -> Self {
        self.order_by = order_by.to_vec();
        self
    }

    pub fn take(mut self, n: i64) -> Self {
        self.take = Some(n);
        self
    }

    pub fn skip(mut self, n: i64) -> Self {
        self.skip = Some(n);
        self
    }

    pub async fn exec<'e>(self) -> sqlx::Result<Vec<crate::demand_letters::DemandLetterProcessing>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT "id", "demand_letter_id", "case_id", "firm_id", "processing_status", "started_at", "completed_at", "processing_status_message", "created_at", "updated_at" FROM "demand_letter_processings" WHERE "#,
        );
        if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_processing_where(
            &mut qb,
            self.where_input,
        ) {
            qb.push("TRUE");
        }
        if !self.order_by.is_empty() {
            qb.push(" ORDER BY ");
            let mut first = true;
            for ob in &self.order_by {
                if let Some(o) = ob.id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.demand_letter_id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"demand_letter_id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.case_id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"case_id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.firm_id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"firm_id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.processing_status {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"processing_status\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.started_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"started_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.completed_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"completed_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.processing_status_message {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"processing_status_message\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.created_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"created_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.updated_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"updated_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                // TODO(prisma-rust-generator): sorting by relation `demandLetter` not yet supported.
                let _ = &ob.demand_letter;
                // TODO(prisma-rust-generator): sorting by relation `case` not yet supported.
                let _ = &ob.case;
                // TODO(prisma-rust-generator): sorting by relation `firm` not yet supported.
                let _ = &ob.firm;
            }
        }
        if let Some(n) = self.take {
            qb.push(" LIMIT ");
            qb.push_bind(n);
        }
        if let Some(n) = self.skip {
            qb.push(" OFFSET ");
            qb.push_bind(n);
        }
        qb.build_query_as::<crate::demand_letters::DemandLetterProcessing>()
            .fetch_all(self.executor)
            .await
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub fn find_many<'a, E>(
        executor: E,
        w: &'a crate::demand_letters::DemandLetterProcessingWhereInput,
    ) -> DemandLetterProcessingFindManyBuilder<'a, E> {
        DemandLetterProcessingFindManyBuilder {
            executor,
            where_input: w,
            order_by: Vec::new(),
            take: None,
            skip: None,
        }
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn count<'e, E>(
        executor: E,
        w: Option<&crate::demand_letters::DemandLetterProcessingWhereInput>,
    ) -> sqlx::Result<i64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb =
            sqlx::QueryBuilder::new(r#"SELECT COUNT(*) FROM "demand_letter_processings" WHERE "#);
        if let Some(w) = w {
            if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_processing_where(
                &mut qb, w,
            ) {
                qb.push("TRUE");
            }
        } else {
            qb.push("TRUE");
        }
        let row = qb.build_query_as::<(i64,)>().fetch_one(executor).await?;
        Ok(row.0)
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn create<'e, E>(
        executor: E,
        input: crate::demand_letters::DemandLetterProcessingUncheckedCreateInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut cols = String::new();
        cols.push_str("\"demand_letter_id\"");
        cols.push_str(", ");
        cols.push_str("\"case_id\"");
        cols.push_str(", ");
        cols.push_str("\"firm_id\"");
        if input.completed_at.is_some() {
            cols.push_str(", ");
            cols.push_str("\"completed_at\"");
        }
        if input.processing_status_message.is_some() {
            cols.push_str(", ");
            cols.push_str("\"processing_status_message\"");
        }
        let mut qb = sqlx::QueryBuilder::new(format!(
            r#"INSERT INTO "demand_letter_processings" ({}) VALUES ("#,
            cols,
        ));
        qb.push_bind(input.demand_letter_id);
        qb.push(", ");
        qb.push_bind(input.case_id);
        qb.push(", ");
        qb.push_bind(input.firm_id);
        if let Some(v) = input.completed_at {
            qb.push(", ");
            qb.push_bind(v);
        }
        if let Some(v) = input.processing_status_message {
            qb.push(", ");
            qb.push_bind(v);
        }
        qb.push(r#") RETURNING "id", "demand_letter_id", "case_id", "firm_id", "processing_status", "started_at", "completed_at", "processing_status_message", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn create_many<'e, E>(
        executor: E,
        inputs: &[crate::demand_letters::DemandLetterProcessingUncheckedCreateInput],
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        if inputs.is_empty() {
            return Ok(0);
        }
        let mut qb = sqlx::QueryBuilder::new(
            r#"INSERT INTO "demand_letter_processings" ("demand_letter_id", "case_id", "firm_id", "completed_at", "processing_status_message") "#,
        );
        qb.push_values(inputs, |mut row, input| {
            row.push_bind(input.demand_letter_id.clone());
            row.push_bind(input.case_id.clone());
            row.push_bind(input.firm_id.clone());
            row.push_bind(input.completed_at);
            row.push_bind(input.processing_status_message.clone());
        });
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn update<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterProcessingWhereUniqueInput,
        input: crate::demand_letters::DemandLetterProcessingUncheckedUpdateInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"UPDATE "demand_letter_processings" SET "#);
        let mut first = true;
        if let Some(op) = input.id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = ");
                qb.push_bind(v);
            }
            if let Some(v) = op.increment {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" + ");
                qb.push_bind(v);
            }
            if let Some(v) = op.decrement {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" - ");
                qb.push_bind(v);
            }
            if let Some(v) = op.multiply {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" * ");
                qb.push_bind(v);
            }
            if let Some(v) = op.divide {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" / ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.demand_letter_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"demand_letter_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.case_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"case_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.firm_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"firm_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.processing_status {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"processing_status\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.started_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"started_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.completed_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"completed_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.processing_status_message {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"processing_status_message\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.created_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"created_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.updated_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"updated_at\" = ");
                qb.push_bind(v);
            }
        }
        if first {
            // Nothing to update — fall back to a plain find_unique so the
            // caller still gets the row back (or RowNotFound if absent).
            return Self::find_unique(executor, w)
                .await?
                .ok_or(sqlx::Error::RowNotFound);
        }
        qb.push(" WHERE ");
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(*value);
        } else {
            return Err(sqlx::Error::RowNotFound);
        }
        qb.push(r#" RETURNING "id", "demand_letter_id", "case_id", "firm_id", "processing_status", "started_at", "completed_at", "processing_status_message", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn update_many<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterProcessingWhereInput,
        input: crate::demand_letters::DemandLetterProcessingUncheckedUpdateManyInput,
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"UPDATE "demand_letter_processings" SET "#);
        let mut first = true;
        if let Some(op) = input.id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = ");
                qb.push_bind(v);
            }
            if let Some(v) = op.increment {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" + ");
                qb.push_bind(v);
            }
            if let Some(v) = op.decrement {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" - ");
                qb.push_bind(v);
            }
            if let Some(v) = op.multiply {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" * ");
                qb.push_bind(v);
            }
            if let Some(v) = op.divide {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" / ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.demand_letter_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"demand_letter_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.case_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"case_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.firm_id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"firm_id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.processing_status {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"processing_status\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.started_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"started_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.completed_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"completed_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.processing_status_message {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"processing_status_message\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.created_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"created_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.updated_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"updated_at\" = ");
                qb.push_bind(v);
            }
        }
        if first {
            // No-op update — return 0 rows affected without issuing SQL.
            return Ok(0);
        }
        qb.push(" WHERE ");
        if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_processing_where(
            &mut qb, w,
        ) {
            qb.push("TRUE");
        }
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn delete<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterProcessingWhereUniqueInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"DELETE FROM "demand_letter_processings" WHERE "#);
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(*value);
        } else {
            return Err(sqlx::Error::RowNotFound);
        }
        qb.push(r#" RETURNING "id", "demand_letter_id", "case_id", "firm_id", "processing_status", "started_at", "completed_at", "processing_status_message", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn delete_many<'e, E>(
        executor: E,
        w: &crate::demand_letters::DemandLetterProcessingWhereInput,
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"DELETE FROM "demand_letter_processings" WHERE "#);
        if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_processing_where(
            &mut qb, w,
        ) {
            qb.push("TRUE");
        }
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterProcessingCountAggregateResult {
    pub id: Option<i64>,
    pub demand_letter_id: Option<i64>,
    pub case_id: Option<i64>,
    pub firm_id: Option<i64>,
    pub processing_status: Option<i64>,
    pub started_at: Option<i64>,
    pub completed_at: Option<i64>,
    pub processing_status_message: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<i64>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterProcessingAvgAggregateResult {
    pub id: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterProcessingSumAggregateResult {
    pub id: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterProcessingMinAggregateResult {
    pub id: Option<i32>,
    pub demand_letter_id: Option<String>,
    pub case_id: Option<String>,
    pub firm_id: Option<String>,
    pub started_at: Option<chrono::DateTime<chrono::Utc>>,
    pub completed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub processing_status_message: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterProcessingMaxAggregateResult {
    pub id: Option<i32>,
    pub demand_letter_id: Option<String>,
    pub case_id: Option<String>,
    pub firm_id: Option<String>,
    pub started_at: Option<chrono::DateTime<chrono::Utc>>,
    pub completed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub processing_status_message: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DemandLetterProcessingAggregateResult {
    #[serde(rename = "_count")]
    pub aggregate_count: Option<DemandLetterProcessingCountAggregateResult>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<DemandLetterProcessingAvgAggregateResult>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<DemandLetterProcessingSumAggregateResult>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<DemandLetterProcessingMinAggregateResult>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<DemandLetterProcessingMaxAggregateResult>,
}

impl crate::demand_letters::DemandLetterProcessing {
    pub async fn aggregate<'e, E>(
        executor: E,
        input: &crate::demand_letters::DemandLetterProcessingAggregateInput,
    ) -> sqlx::Result<DemandLetterProcessingAggregateResult>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT COUNT(*) AS count_all, COUNT("id") AS count_id, COUNT("demand_letter_id") AS count_demand_letter_id, COUNT("case_id") AS count_case_id, COUNT("firm_id") AS count_firm_id, COUNT("processing_status") AS count_processing_status, COUNT("started_at") AS count_started_at, COUNT("completed_at") AS count_completed_at, COUNT("processing_status_message") AS count_processing_status_message, COUNT("created_at") AS count_created_at, COUNT("updated_at") AS count_updated_at, AVG("id")::double precision AS avg_id, SUM("id")::double precision AS sum_id, MIN("id") AS min_id, MAX("id") AS max_id, MIN("demand_letter_id") AS min_demand_letter_id, MAX("demand_letter_id") AS max_demand_letter_id, MIN("case_id") AS min_case_id, MAX("case_id") AS max_case_id, MIN("firm_id") AS min_firm_id, MAX("firm_id") AS max_firm_id, MIN("started_at") AS min_started_at, MAX("started_at") AS max_started_at, MIN("completed_at") AS min_completed_at, MAX("completed_at") AS max_completed_at, MIN("processing_status_message") AS min_processing_status_message, MAX("processing_status_message") AS max_processing_status_message, MIN("created_at") AS min_created_at, MAX("created_at") AS max_created_at, MIN("updated_at") AS min_updated_at, MAX("updated_at") AS max_updated_at FROM "demand_letter_processings" WHERE "#,
        );
        if let Some(w) = &input.r#where {
            if !crate::engine::sqlx_postgres::demand_letters::push_demand_letter_processing_where(
                &mut qb, w,
            ) {
                qb.push("TRUE");
            }
        } else {
            qb.push("TRUE");
        }
        let row = qb.build().fetch_one(executor).await?;
        use sqlx::Row;
        Ok(DemandLetterProcessingAggregateResult {
            aggregate_count: input
                .aggregate_count
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(DemandLetterProcessingCountAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_id")?
                        } else {
                            None
                        },
                        demand_letter_id: if req.demand_letter_id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_demand_letter_id")?
                        } else {
                            None
                        },
                        case_id: if req.case_id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_case_id")?
                        } else {
                            None
                        },
                        firm_id: if req.firm_id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_firm_id")?
                        } else {
                            None
                        },
                        processing_status: if req.processing_status.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_processing_status")?
                        } else {
                            None
                        },
                        started_at: if req.started_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_started_at")?
                        } else {
                            None
                        },
                        completed_at: if req.completed_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_completed_at")?
                        } else {
                            None
                        },
                        processing_status_message: if req.processing_status_message.unwrap_or(false)
                        {
                            row.try_get::<Option<i64>, _>("count_processing_status_message")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_created_at")?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_updated_at")?
                        } else {
                            None
                        },
                        aggregate_all: if req.aggregate_all.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_all")?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_avg: input
                .aggregate_avg
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(DemandLetterProcessingAvgAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<f64>, _>("avg_id")?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_sum: input
                .aggregate_sum
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(DemandLetterProcessingSumAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<f64>, _>("sum_id")?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_min: input
                .aggregate_min
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(DemandLetterProcessingMinAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<i32>, _>("min_id")?
                        } else {
                            None
                        },
                        demand_letter_id: if req.demand_letter_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_demand_letter_id")?
                        } else {
                            None
                        },
                        case_id: if req.case_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_case_id")?
                        } else {
                            None
                        },
                        firm_id: if req.firm_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_firm_id")?
                        } else {
                            None
                        },
                        started_at: if req.started_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_started_at",
                            )?
                        } else {
                            None
                        },
                        completed_at: if req.completed_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_completed_at",
                            )?
                        } else {
                            None
                        },
                        processing_status_message: if req.processing_status_message.unwrap_or(false)
                        {
                            row.try_get::<Option<String>, _>("min_processing_status_message")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_created_at",
                            )?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_updated_at",
                            )?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_max: input
                .aggregate_max
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(DemandLetterProcessingMaxAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<i32>, _>("max_id")?
                        } else {
                            None
                        },
                        demand_letter_id: if req.demand_letter_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_demand_letter_id")?
                        } else {
                            None
                        },
                        case_id: if req.case_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_case_id")?
                        } else {
                            None
                        },
                        firm_id: if req.firm_id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_firm_id")?
                        } else {
                            None
                        },
                        started_at: if req.started_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_started_at",
                            )?
                        } else {
                            None
                        },
                        completed_at: if req.completed_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_completed_at",
                            )?
                        } else {
                            None
                        },
                        processing_status_message: if req.processing_status_message.unwrap_or(false)
                        {
                            row.try_get::<Option<String>, _>("max_processing_status_message")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_created_at",
                            )?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_updated_at",
                            )?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
        })
    }
}
