// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "ADMIN")]
    Admin,
    #[serde(rename = "USER")]
    User,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RoleFieldUpdateOperationsInput {
    pub set: Option<Role>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NullableRoleFieldUpdateOperationsInput {
    pub set: Option<Option<Role>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RoleFilter {
    pub equals: Option<crate::enums::role::Role>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::enums::role::Role>>,
    pub not_in: Option<Vec<crate::enums::role::Role>>,
    pub not: Option<Box<RoleFilter>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RoleNullableFilter {
    pub equals: Option<crate::enums::role::Role>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::enums::role::Role>>,
    pub not_in: Option<Vec<crate::enums::role::Role>>,
    pub is_null: Option<bool>,
    pub not: Option<Box<RoleNullableFilter>>,
}
