// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Enum29 {
    #[serde(rename = "FORM_LINK_SENT")]
    FormLinkSent,
    #[serde(rename = "FORM_SUBMITTED")]
    FormSubmitted,
    #[serde(rename = "FORM_VERIFIED")]
    FormVerified,
    #[serde(rename = "FORM_REJECTED")]
    FormRejected,
    #[serde(rename = "ASSESSMENT_COMPLETED")]
    AssessmentCompleted,
    #[serde(rename = "LINK_EXPIRING")]
    LinkExpiring,
    #[serde(rename = "LINK_EXPIRED")]
    LinkExpired,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Enum29FieldUpdateOperationsInput {
    pub set: Option<Enum29>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NullableEnum29FieldUpdateOperationsInput {
    pub set: Option<Option<Enum29>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Enum29Filter {
    pub equals: Option<crate::m_11_stress::Enum29>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::m_11_stress::Enum29>>,
    pub not_in: Option<Vec<crate::m_11_stress::Enum29>>,
    pub not: Option<Box<Enum29Filter>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Enum29NullableFilter {
    pub equals: Option<crate::m_11_stress::Enum29>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::m_11_stress::Enum29>>,
    pub not_in: Option<Vec<crate::m_11_stress::Enum29>>,
    pub is_null: Option<bool>,
    pub not: Option<Box<Enum29NullableFilter>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Enum30 {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "SENT")]
    Sent,
    #[serde(rename = "DELIVERED")]
    Delivered,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "BOUNCED")]
    Bounced,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Enum30FieldUpdateOperationsInput {
    pub set: Option<Enum30>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NullableEnum30FieldUpdateOperationsInput {
    pub set: Option<Option<Enum30>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Enum30Filter {
    pub equals: Option<crate::m_11_stress::Enum30>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::m_11_stress::Enum30>>,
    pub not_in: Option<Vec<crate::m_11_stress::Enum30>>,
    pub not: Option<Box<Enum30Filter>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Enum30NullableFilter {
    pub equals: Option<crate::m_11_stress::Enum30>,
    #[serde(rename = "in")]
    pub r#in: Option<Vec<crate::m_11_stress::Enum30>>,
    pub not_in: Option<Vec<crate::m_11_stress::Enum30>>,
    pub is_null: Option<bool>,
    pub not: Option<Box<Enum30NullableFilter>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49 {
    pub id: String,
    pub rel_fk_id_1: String,
    pub rel_fk_id_2: String,
    pub r#type: crate::m_11_stress::Enum29,
    pub field_1: String,
    pub field_2: String,
    pub field_3: Option<String>,
    pub field_4: Option<String>,
    pub field_5: bool,
    pub field_6: Option<chrono::DateTime<chrono::Utc>>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rel_1: Option<Box<crate::m_09_stress::Entity37>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rel_2: Option<Box<crate::m_16_stress::Entity74>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49WhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFilter>,
    pub rel_fk_id_2: Option<crate::shared::filters::StringFilter>,
    pub r#type: Option<crate::m_11_stress::Enum29Filter>,
    pub field_1: Option<crate::shared::filters::StringFilter>,
    pub field_2: Option<crate::shared::filters::StringFilter>,
    pub field_3: Option<crate::shared::filters::StringNullableFilter>,
    pub field_4: Option<crate::shared::filters::StringNullableFilter>,
    pub field_5: Option<crate::shared::filters::BoolFilter>,
    pub field_6: Option<crate::shared::filters::DateTimeNullableFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub rel_1: Option<crate::m_09_stress::Entity37RelationFilter>,
    pub rel_2: Option<crate::m_16_stress::Entity74RelationFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<Entity49WhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<Entity49WhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<Entity49WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49RelationFilter {
    pub is: Option<Box<crate::m_11_stress::Entity49WhereInput>>,
    pub is_not: Option<Box<crate::m_11_stress::Entity49WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49ListRelationFilter {
    pub some: Option<Box<crate::m_11_stress::Entity49WhereInput>>,
    pub every: Option<Box<crate::m_11_stress::Entity49WhereInput>>,
    pub none: Option<Box<crate::m_11_stress::Entity49WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49WhereUniqueInput {
    pub id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49OrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub rel_fk_id_1: Option<crate::shared::filters::SortOrder>,
    pub rel_fk_id_2: Option<crate::shared::filters::SortOrder>,
    pub r#type: Option<crate::shared::filters::SortOrder>,
    pub field_1: Option<crate::shared::filters::SortOrder>,
    pub field_2: Option<crate::shared::filters::SortOrder>,
    pub field_3: Option<crate::shared::filters::SortOrder>,
    pub field_4: Option<crate::shared::filters::SortOrder>,
    pub field_5: Option<crate::shared::filters::SortOrder>,
    pub field_6: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub rel_1: Option<Box<crate::m_09_stress::Entity37OrderByWithRelationInput>>,
    pub rel_2: Option<Box<crate::m_16_stress::Entity74OrderByWithRelationInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49Select {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub rel_fk_id_2: Option<bool>,
    pub r#type: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub field_3: Option<bool>,
    pub field_4: Option<bool>,
    pub field_5: Option<bool>,
    pub field_6: Option<bool>,
    pub created_at: Option<bool>,
    pub rel_1: Option<bool>,
    pub rel_2: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49Include {
    pub rel_1: Option<bool>,
    pub rel_2: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49CreateInput {
    pub r#type: crate::m_11_stress::Enum29,
    pub field_1: String,
    pub field_2: String,
    pub field_3: Option<String>,
    pub field_4: Option<String>,
    pub field_6: Option<chrono::DateTime<chrono::Utc>>,
    pub rel_1: Option<Box<crate::m_11_stress::Entity37CreateNestedOneWithoutEntity49Rel1Input>>,
    pub rel_2: Option<Box<crate::m_11_stress::Entity74CreateNestedOneWithoutEntity49Rel2Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49UncheckedCreateInput {
    pub rel_fk_id_1: String,
    pub rel_fk_id_2: String,
    pub r#type: crate::m_11_stress::Enum29,
    pub field_1: String,
    pub field_2: String,
    pub field_3: Option<String>,
    pub field_4: Option<String>,
    pub field_6: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49CreateManyInput {
    pub rel_fk_id_1: String,
    pub rel_fk_id_2: String,
    pub r#type: crate::m_11_stress::Enum29,
    pub field_1: String,
    pub field_2: String,
    pub field_3: Option<String>,
    pub field_4: Option<String>,
    pub field_6: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49UpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub r#type: Option<crate::m_11_stress::Enum29FieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub rel_1:
        Option<Box<crate::m_11_stress::Entity37UpdateOneRequiredWithoutEntity49Rel1NestedInput>>,
    pub rel_2:
        Option<Box<crate::m_11_stress::Entity74UpdateOneRequiredWithoutEntity49Rel2NestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49UncheckedUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub rel_fk_id_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub r#type: Option<crate::m_11_stress::Enum29FieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49UpdateManyMutationInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub r#type: Option<crate::m_11_stress::Enum29FieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49UncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub rel_fk_id_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub r#type: Option<crate::m_11_stress::Enum29FieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37CreateWithoutEntity49Rel1Input {
    pub name: String,
    pub field_1: Option<String>,
    pub field_2: Option<String>,
    pub rel_1: Option<Box<crate::m_09_stress::Entity66CreateNestedOneWithoutEntity37Rel1Input>>,
    pub rel_2: Option<Box<crate::m_09_stress::Entity74CreateNestedManyWithoutEntity37Rel2Input>>,
    pub rel_3: Option<Box<crate::m_09_stress::Entity74CreateNestedOneWithoutEntity37Rel3Input>>,
    pub rel_4: Option<Box<crate::m_09_stress::Entity29CreateNestedManyWithoutEntity37Rel4Input>>,
    pub rel_5: Option<Box<crate::m_09_stress::Entity19CreateNestedManyWithoutEntity37Rel5Input>>,
    pub rel_6: Option<Box<crate::m_09_stress::Entity26CreateNestedManyWithoutEntity37Rel6Input>>,
    pub rel_7: Option<Box<crate::m_09_stress::Entity13CreateNestedManyWithoutEntity37Rel7Input>>,
    pub rel_8: Option<Box<crate::m_09_stress::Entity30CreateNestedManyWithoutEntity37Rel8Input>>,
    pub rel_9: Option<Box<crate::m_09_stress::Entity41CreateNestedManyWithoutEntity37Rel9Input>>,
    pub rel_10: Option<Box<crate::m_09_stress::Entity10CreateNestedManyWithoutEntity37Rel10Input>>,
    pub rel_11: Option<Box<crate::m_09_stress::Entity14CreateNestedManyWithoutEntity37Rel11Input>>,
    pub rel_12: Option<Box<crate::m_09_stress::Entity27CreateNestedManyWithoutEntity37Rel12Input>>,
    pub rel_13: Option<Box<crate::m_09_stress::Entity15CreateNestedManyWithoutEntity37Rel13Input>>,
    pub rel_14: Option<Box<crate::m_09_stress::Entity44CreateNestedManyWithoutEntity37Rel14Input>>,
    pub rel_15: Option<Box<crate::m_09_stress::Entity46CreateNestedManyWithoutEntity37Rel15Input>>,
    pub rel_16: Option<Box<crate::m_09_stress::Entity47CreateNestedManyWithoutEntity37Rel16Input>>,
    pub rel_17: Option<Box<crate::m_09_stress::Entity60CreateNestedManyWithoutEntity37Rel17Input>>,
    pub rel_19: Option<Box<crate::m_09_stress::Entity51CreateNestedManyWithoutEntity37Rel19Input>>,
    pub rel_20: Option<Box<crate::m_09_stress::Entity38CreateNestedManyWithoutEntity37Rel20Input>>,
    pub rel_21: Option<Box<crate::m_09_stress::Entity38CreateNestedOneWithoutEntity37Rel21Input>>,
    pub rel_22: Option<Box<crate::m_09_stress::Entity1CreateNestedOneWithoutEntity37Rel22Input>>,
    pub rel_23: Option<Box<crate::m_09_stress::Entity2CreateNestedManyWithoutEntity37Rel23Input>>,
    pub rel_24: Option<Box<crate::m_09_stress::Entity3CreateNestedManyWithoutEntity37Rel24Input>>,
    pub rel_25: Option<Box<crate::m_09_stress::Entity63CreateNestedManyWithoutEntity37Rel25Input>>,
    pub rel_26: Option<Box<crate::m_09_stress::Entity64CreateNestedManyWithoutEntity37Rel26Input>>,
    pub rel_27: Option<Box<crate::m_09_stress::Entity65CreateNestedManyWithoutEntity37Rel27Input>>,
    pub rel_28: Option<Box<crate::m_09_stress::Entity16CreateNestedManyWithoutEntity37Rel28Input>>,
    pub rel_29: Option<Box<crate::m_09_stress::Entity18CreateNestedManyWithoutEntity37Rel29Input>>,
    pub rel_30: Option<Box<crate::m_09_stress::Entity42CreateNestedManyWithoutEntity37Rel30Input>>,
    pub rel_31: Option<Box<crate::m_09_stress::Entity43CreateNestedManyWithoutEntity37Rel31Input>>,
    pub rel_32: Option<Box<crate::m_09_stress::Entity20CreateNestedManyWithoutEntity37Rel32Input>>,
    pub rel_33: Option<Box<crate::m_09_stress::Entity21CreateNestedManyWithoutEntity37Rel33Input>>,
    pub rel_34: Option<Box<crate::m_09_stress::Entity22CreateNestedManyWithoutEntity37Rel34Input>>,
    pub rel_35: Option<Box<crate::m_09_stress::Entity23CreateNestedManyWithoutEntity37Rel35Input>>,
    pub rel_36: Option<Box<crate::m_09_stress::Entity24CreateNestedManyWithoutEntity37Rel36Input>>,
    pub rel_37: Option<Box<crate::m_09_stress::Entity25CreateNestedManyWithoutEntity37Rel37Input>>,
    pub rel_38: Option<Box<crate::m_09_stress::Entity35CreateNestedManyWithoutEntity37Rel38Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UncheckedCreateWithoutEntity49Rel1Input {
    pub name: String,
    pub field_1: Option<String>,
    pub field_2: Option<String>,
    pub rel_fk_id_1: Option<String>,
    pub rel_fk_id_3: Option<String>,
    pub rel_fk_id_21: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37CreateOrConnectWithoutEntity49Rel1Input {
    pub r#where: Box<crate::m_09_stress::Entity37WhereUniqueInput>,
    pub create: Box<crate::m_11_stress::Entity37CreateWithoutEntity49Rel1Input>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UpdateWithoutEntity49Rel1Input {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub field_3: Option<crate::m_16_stress::Enum37FieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub rel_1: Option<Box<crate::m_09_stress::Entity66UpdateOneWithoutEntity37Rel1NestedInput>>,
    pub rel_2: Option<Box<crate::m_09_stress::Entity74UpdateManyWithoutEntity37Rel2NestedInput>>,
    pub rel_3: Option<Box<crate::m_09_stress::Entity74UpdateOneWithoutEntity37Rel3NestedInput>>,
    pub rel_4: Option<Box<crate::m_09_stress::Entity29UpdateManyWithoutEntity37Rel4NestedInput>>,
    pub rel_5: Option<Box<crate::m_09_stress::Entity19UpdateManyWithoutEntity37Rel5NestedInput>>,
    pub rel_6: Option<Box<crate::m_09_stress::Entity26UpdateManyWithoutEntity37Rel6NestedInput>>,
    pub rel_7: Option<Box<crate::m_09_stress::Entity13UpdateManyWithoutEntity37Rel7NestedInput>>,
    pub rel_8: Option<Box<crate::m_09_stress::Entity30UpdateManyWithoutEntity37Rel8NestedInput>>,
    pub rel_9: Option<Box<crate::m_09_stress::Entity41UpdateManyWithoutEntity37Rel9NestedInput>>,
    pub rel_10: Option<Box<crate::m_09_stress::Entity10UpdateManyWithoutEntity37Rel10NestedInput>>,
    pub rel_11: Option<Box<crate::m_09_stress::Entity14UpdateManyWithoutEntity37Rel11NestedInput>>,
    pub rel_12: Option<Box<crate::m_09_stress::Entity27UpdateManyWithoutEntity37Rel12NestedInput>>,
    pub rel_13: Option<Box<crate::m_09_stress::Entity15UpdateManyWithoutEntity37Rel13NestedInput>>,
    pub rel_14: Option<Box<crate::m_09_stress::Entity44UpdateManyWithoutEntity37Rel14NestedInput>>,
    pub rel_15: Option<Box<crate::m_09_stress::Entity46UpdateManyWithoutEntity37Rel15NestedInput>>,
    pub rel_16: Option<Box<crate::m_09_stress::Entity47UpdateManyWithoutEntity37Rel16NestedInput>>,
    pub rel_17: Option<Box<crate::m_09_stress::Entity60UpdateManyWithoutEntity37Rel17NestedInput>>,
    pub rel_19: Option<Box<crate::m_09_stress::Entity51UpdateManyWithoutEntity37Rel19NestedInput>>,
    pub rel_20: Option<Box<crate::m_09_stress::Entity38UpdateManyWithoutEntity37Rel20NestedInput>>,
    pub rel_21: Option<Box<crate::m_09_stress::Entity38UpdateOneWithoutEntity37Rel21NestedInput>>,
    pub rel_22: Option<Box<crate::m_09_stress::Entity1UpdateOneWithoutEntity37Rel22NestedInput>>,
    pub rel_23: Option<Box<crate::m_09_stress::Entity2UpdateManyWithoutEntity37Rel23NestedInput>>,
    pub rel_24: Option<Box<crate::m_09_stress::Entity3UpdateManyWithoutEntity37Rel24NestedInput>>,
    pub rel_25: Option<Box<crate::m_09_stress::Entity63UpdateManyWithoutEntity37Rel25NestedInput>>,
    pub rel_26: Option<Box<crate::m_09_stress::Entity64UpdateManyWithoutEntity37Rel26NestedInput>>,
    pub rel_27: Option<Box<crate::m_09_stress::Entity65UpdateManyWithoutEntity37Rel27NestedInput>>,
    pub rel_28: Option<Box<crate::m_09_stress::Entity16UpdateManyWithoutEntity37Rel28NestedInput>>,
    pub rel_29: Option<Box<crate::m_09_stress::Entity18UpdateManyWithoutEntity37Rel29NestedInput>>,
    pub rel_30: Option<Box<crate::m_09_stress::Entity42UpdateManyWithoutEntity37Rel30NestedInput>>,
    pub rel_31: Option<Box<crate::m_09_stress::Entity43UpdateManyWithoutEntity37Rel31NestedInput>>,
    pub rel_32: Option<Box<crate::m_09_stress::Entity20UpdateManyWithoutEntity37Rel32NestedInput>>,
    pub rel_33: Option<Box<crate::m_09_stress::Entity21UpdateManyWithoutEntity37Rel33NestedInput>>,
    pub rel_34: Option<Box<crate::m_09_stress::Entity22UpdateManyWithoutEntity37Rel34NestedInput>>,
    pub rel_35: Option<Box<crate::m_09_stress::Entity23UpdateManyWithoutEntity37Rel35NestedInput>>,
    pub rel_36: Option<Box<crate::m_09_stress::Entity24UpdateManyWithoutEntity37Rel36NestedInput>>,
    pub rel_37: Option<Box<crate::m_09_stress::Entity25UpdateManyWithoutEntity37Rel37NestedInput>>,
    pub rel_38: Option<Box<crate::m_09_stress::Entity35UpdateManyWithoutEntity37Rel38NestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UncheckedUpdateWithoutEntity49Rel1Input {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub rel_fk_id_1: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub rel_fk_id_3: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::m_16_stress::Enum37FieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub rel_fk_id_21: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37CreateNestedOneWithoutEntity49Rel1Input {
    pub create: Option<Box<crate::m_11_stress::Entity37CreateWithoutEntity49Rel1Input>>,
    pub connect_or_create:
        Option<Box<crate::m_11_stress::Entity37CreateOrConnectWithoutEntity49Rel1Input>>,
    pub connect: Option<Box<crate::m_09_stress::Entity37WhereUniqueInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UpsertWithoutEntity49Rel1Input {
    pub update: Box<crate::m_11_stress::Entity37UpdateWithoutEntity49Rel1Input>,
    pub create: Box<crate::m_11_stress::Entity37CreateWithoutEntity49Rel1Input>,
    pub r#where: Option<Box<crate::m_09_stress::Entity37WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UpdateOneRequiredWithoutEntity49Rel1NestedInput {
    pub create: Option<Box<crate::m_11_stress::Entity37CreateWithoutEntity49Rel1Input>>,
    pub connect_or_create:
        Option<Box<crate::m_11_stress::Entity37CreateOrConnectWithoutEntity49Rel1Input>>,
    pub upsert: Option<Box<crate::m_11_stress::Entity37UpsertWithoutEntity49Rel1Input>>,
    pub connect: Option<Box<crate::m_09_stress::Entity37WhereUniqueInput>>,
    pub update:
        Option<Box<crate::m_11_stress::Entity37UpdateToOneWithWhereWithoutEntity49Rel1Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UpdateToOneWithWhereWithoutEntity49Rel1Input {
    pub r#where: Option<Box<crate::m_09_stress::Entity37WhereInput>>,
    pub data: Box<crate::m_11_stress::Entity37UpdateWithoutEntity49Rel1Input>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74CreateWithoutEntity49Rel2Input {
    pub field_1: String,
    pub field_2: String,
    pub field_3: String,
    pub email: String,
    pub field_5: Option<String>,
    pub field_8: Option<i32>,
    pub field_9: Option<chrono::DateTime<chrono::Utc>>,
    pub field_10: Option<String>,
    pub field_14: Option<chrono::DateTime<chrono::Utc>>,
    pub field_16: Option<chrono::DateTime<chrono::Utc>>,
    pub field_17: Option<chrono::DateTime<chrono::Utc>>,
    pub field_18: Option<String>,
    pub rel_1: Option<Box<crate::m_16_stress::Entity59CreateNestedManyWithoutEntity74Rel1Input>>,
    pub rel_2: Option<Box<crate::m_16_stress::Entity29CreateNestedManyWithoutEntity74Rel2Input>>,
    pub rel_3: Option<Box<crate::m_16_stress::Entity30CreateNestedManyWithoutEntity74Rel3Input>>,
    pub rel_4: Option<Box<crate::m_16_stress::Entity32CreateNestedManyWithoutEntity74Rel4Input>>,
    pub rel_5: Option<Box<crate::m_16_stress::Entity37CreateNestedOneWithoutEntity74Rel5Input>>,
    pub rel_6: Option<Box<crate::m_16_stress::Entity38CreateNestedOneWithoutEntity74Rel6Input>>,
    pub rel_7: Option<Box<crate::m_16_stress::Entity37CreateNestedOneWithoutEntity74Rel7Input>>,
    pub rel_8: Option<Box<crate::m_16_stress::Entity10CreateNestedManyWithoutEntity74Rel8Input>>,
    pub rel_9: Option<Box<crate::m_16_stress::Entity5CreateNestedManyWithoutEntity74Rel9Input>>,
    pub rel_10: Option<Box<crate::m_16_stress::Entity14CreateNestedManyWithoutEntity74Rel10Input>>,
    pub rel_11: Option<Box<crate::m_16_stress::Entity75CreateNestedManyWithoutEntity74Rel11Input>>,
    pub rel_12: Option<Box<crate::m_16_stress::Entity6CreateNestedManyWithoutEntity74Rel12Input>>,
    pub rel_13: Option<Box<crate::m_16_stress::Entity44CreateNestedManyWithoutEntity74Rel13Input>>,
    pub rel_14: Option<Box<crate::m_16_stress::Entity46CreateNestedManyWithoutEntity74Rel14Input>>,
    pub rel_15: Option<Box<crate::m_16_stress::Entity47CreateNestedManyWithoutEntity74Rel15Input>>,
    pub rel_16: Option<Box<crate::m_16_stress::Entity48CreateNestedManyWithoutEntity74Rel16Input>>,
    pub rel_17: Option<Box<crate::m_16_stress::Entity62CreateNestedManyWithoutEntity74Rel17Input>>,
    pub rel_19: Option<Box<crate::m_16_stress::Entity50CreateNestedManyWithoutEntity74Rel19Input>>,
    pub rel_20: Option<Box<crate::m_16_stress::Entity7CreateNestedManyWithoutEntity74Rel20Input>>,
    pub rel_21: Option<Box<crate::m_16_stress::Entity16CreateNestedManyWithoutEntity74Rel21Input>>,
    pub rel_22: Option<Box<crate::m_16_stress::Entity18CreateNestedManyWithoutEntity74Rel22Input>>,
    pub rel_23: Option<Box<crate::m_16_stress::Entity42CreateNestedManyWithoutEntity74Rel23Input>>,
    pub rel_24: Option<Box<crate::m_16_stress::Entity42CreateNestedManyWithoutEntity74Rel24Input>>,
    pub rel_25: Option<Box<crate::m_16_stress::Entity19CreateNestedManyWithoutEntity74Rel25Input>>,
    pub rel_26: Option<Box<crate::m_16_stress::Entity20CreateNestedManyWithoutEntity74Rel26Input>>,
    pub rel_27: Option<Box<crate::m_16_stress::Entity21CreateNestedManyWithoutEntity74Rel27Input>>,
    pub rel_28: Option<Box<crate::m_16_stress::Entity21CreateNestedManyWithoutEntity74Rel28Input>>,
    pub rel_29: Option<Box<crate::m_16_stress::Entity24CreateNestedManyWithoutEntity74Rel29Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UncheckedCreateWithoutEntity49Rel2Input {
    pub field_1: String,
    pub field_2: String,
    pub field_3: String,
    pub email: String,
    pub field_5: Option<String>,
    pub field_8: Option<i32>,
    pub field_9: Option<chrono::DateTime<chrono::Utc>>,
    pub field_10: Option<String>,
    pub field_14: Option<chrono::DateTime<chrono::Utc>>,
    pub field_16: Option<chrono::DateTime<chrono::Utc>>,
    pub field_17: Option<chrono::DateTime<chrono::Utc>>,
    pub field_18: Option<String>,
    pub rel_fk_id_5: Option<String>,
    pub rel_fk_id_6: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74CreateOrConnectWithoutEntity49Rel2Input {
    pub r#where: Box<crate::m_16_stress::Entity74WhereUniqueInput>,
    pub create: Box<crate::m_11_stress::Entity74CreateWithoutEntity49Rel2Input>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UpdateWithoutEntity49Rel2Input {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::NullableIntFieldUpdateOperationsInput>,
    pub field_8: Option<crate::shared::filters::NullableIntFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub field_9: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_10: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_11: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub field_12: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_13: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_14: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_15: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_16: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_17: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_18: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub rel_1: Option<Box<crate::m_16_stress::Entity59UpdateManyWithoutEntity74Rel1NestedInput>>,
    pub rel_2: Option<Box<crate::m_16_stress::Entity29UpdateManyWithoutEntity74Rel2NestedInput>>,
    pub rel_3: Option<Box<crate::m_16_stress::Entity30UpdateManyWithoutEntity74Rel3NestedInput>>,
    pub rel_4: Option<Box<crate::m_16_stress::Entity32UpdateManyWithoutEntity74Rel4NestedInput>>,
    pub rel_5: Option<Box<crate::m_16_stress::Entity37UpdateOneWithoutEntity74Rel5NestedInput>>,
    pub rel_6: Option<Box<crate::m_16_stress::Entity38UpdateOneWithoutEntity74Rel6NestedInput>>,
    pub rel_7: Option<Box<crate::m_16_stress::Entity37UpdateOneWithoutEntity74Rel7NestedInput>>,
    pub rel_8: Option<Box<crate::m_16_stress::Entity10UpdateManyWithoutEntity74Rel8NestedInput>>,
    pub rel_9: Option<Box<crate::m_16_stress::Entity5UpdateManyWithoutEntity74Rel9NestedInput>>,
    pub rel_10: Option<Box<crate::m_16_stress::Entity14UpdateManyWithoutEntity74Rel10NestedInput>>,
    pub rel_11: Option<Box<crate::m_16_stress::Entity75UpdateManyWithoutEntity74Rel11NestedInput>>,
    pub rel_12: Option<Box<crate::m_16_stress::Entity6UpdateManyWithoutEntity74Rel12NestedInput>>,
    pub rel_13: Option<Box<crate::m_16_stress::Entity44UpdateManyWithoutEntity74Rel13NestedInput>>,
    pub rel_14: Option<Box<crate::m_16_stress::Entity46UpdateManyWithoutEntity74Rel14NestedInput>>,
    pub rel_15: Option<Box<crate::m_16_stress::Entity47UpdateManyWithoutEntity74Rel15NestedInput>>,
    pub rel_16: Option<Box<crate::m_16_stress::Entity48UpdateManyWithoutEntity74Rel16NestedInput>>,
    pub rel_17: Option<Box<crate::m_16_stress::Entity62UpdateManyWithoutEntity74Rel17NestedInput>>,
    pub rel_19: Option<Box<crate::m_16_stress::Entity50UpdateManyWithoutEntity74Rel19NestedInput>>,
    pub rel_20: Option<Box<crate::m_16_stress::Entity7UpdateManyWithoutEntity74Rel20NestedInput>>,
    pub rel_21: Option<Box<crate::m_16_stress::Entity16UpdateManyWithoutEntity74Rel21NestedInput>>,
    pub rel_22: Option<Box<crate::m_16_stress::Entity18UpdateManyWithoutEntity74Rel22NestedInput>>,
    pub rel_23: Option<Box<crate::m_16_stress::Entity42UpdateManyWithoutEntity74Rel23NestedInput>>,
    pub rel_24: Option<Box<crate::m_16_stress::Entity42UpdateManyWithoutEntity74Rel24NestedInput>>,
    pub rel_25: Option<Box<crate::m_16_stress::Entity19UpdateManyWithoutEntity74Rel25NestedInput>>,
    pub rel_26: Option<Box<crate::m_16_stress::Entity20UpdateManyWithoutEntity74Rel26NestedInput>>,
    pub rel_27: Option<Box<crate::m_16_stress::Entity21UpdateManyWithoutEntity74Rel27NestedInput>>,
    pub rel_28: Option<Box<crate::m_16_stress::Entity21UpdateManyWithoutEntity74Rel28NestedInput>>,
    pub rel_29: Option<Box<crate::m_16_stress::Entity24UpdateManyWithoutEntity74Rel29NestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UncheckedUpdateWithoutEntity49Rel2Input {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::NullableIntFieldUpdateOperationsInput>,
    pub field_8: Option<crate::shared::filters::NullableIntFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub field_9: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_10: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_11: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub field_12: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_13: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_14: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_15: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_16: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_17: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_18: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub rel_fk_id_5: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub rel_fk_id_6: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74CreateNestedOneWithoutEntity49Rel2Input {
    pub create: Option<Box<crate::m_11_stress::Entity74CreateWithoutEntity49Rel2Input>>,
    pub connect_or_create:
        Option<Box<crate::m_11_stress::Entity74CreateOrConnectWithoutEntity49Rel2Input>>,
    pub connect: Option<Box<crate::m_16_stress::Entity74WhereUniqueInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UpsertWithoutEntity49Rel2Input {
    pub update: Box<crate::m_11_stress::Entity74UpdateWithoutEntity49Rel2Input>,
    pub create: Box<crate::m_11_stress::Entity74CreateWithoutEntity49Rel2Input>,
    pub r#where: Option<Box<crate::m_16_stress::Entity74WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UpdateOneRequiredWithoutEntity49Rel2NestedInput {
    pub create: Option<Box<crate::m_11_stress::Entity74CreateWithoutEntity49Rel2Input>>,
    pub connect_or_create:
        Option<Box<crate::m_11_stress::Entity74CreateOrConnectWithoutEntity49Rel2Input>>,
    pub upsert: Option<Box<crate::m_11_stress::Entity74UpsertWithoutEntity49Rel2Input>>,
    pub connect: Option<Box<crate::m_16_stress::Entity74WhereUniqueInput>>,
    pub update:
        Option<Box<crate::m_11_stress::Entity74UpdateToOneWithWhereWithoutEntity49Rel2Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UpdateToOneWithWhereWithoutEntity49Rel2Input {
    pub r#where: Option<Box<crate::m_16_stress::Entity74WhereInput>>,
    pub data: Box<crate::m_11_stress::Entity74UpdateWithoutEntity49Rel2Input>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49ScalarWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFilter>,
    pub rel_fk_id_2: Option<crate::shared::filters::StringFilter>,
    pub r#type: Option<crate::m_11_stress::Enum29Filter>,
    pub field_1: Option<crate::shared::filters::StringFilter>,
    pub field_2: Option<crate::shared::filters::StringFilter>,
    pub field_3: Option<crate::shared::filters::StringNullableFilter>,
    pub field_4: Option<crate::shared::filters::StringNullableFilter>,
    pub field_5: Option<crate::shared::filters::BoolFilter>,
    pub field_6: Option<crate::shared::filters::DateTimeNullableFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<Entity49ScalarWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<Entity49ScalarWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<Entity49ScalarWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49CountAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub rel_fk_id_2: Option<bool>,
    pub r#type: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub field_3: Option<bool>,
    pub field_4: Option<bool>,
    pub field_5: Option<bool>,
    pub field_6: Option<bool>,
    pub created_at: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49AvgAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49SumAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49MinAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub rel_fk_id_2: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub field_3: Option<bool>,
    pub field_4: Option<bool>,
    pub field_5: Option<bool>,
    pub field_6: Option<bool>,
    pub created_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49MaxAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub rel_fk_id_2: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub field_3: Option<bool>,
    pub field_4: Option<bool>,
    pub field_5: Option<bool>,
    pub field_6: Option<bool>,
    pub created_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49OrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub rel_fk_id_1: Option<crate::shared::filters::SortOrder>,
    pub rel_fk_id_2: Option<crate::shared::filters::SortOrder>,
    pub r#type: Option<crate::shared::filters::SortOrder>,
    pub field_1: Option<crate::shared::filters::SortOrder>,
    pub field_2: Option<crate::shared::filters::SortOrder>,
    pub field_3: Option<crate::shared::filters::SortOrder>,
    pub field_4: Option<crate::shared::filters::SortOrder>,
    pub field_5: Option<crate::shared::filters::SortOrder>,
    pub field_6: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<Entity49CountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<Entity49AvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<Entity49SumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<Entity49MinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<Entity49MaxAggregateInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity49AggregateInput {
    #[serde(rename = "where")]
    pub r#where: Option<Entity49WhereInput>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<Entity49CountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<Entity49AvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<Entity49SumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<Entity49MinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<Entity49MaxAggregateInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50 {
    pub id: String,
    pub rel_fk_id_1: String,
    pub r#type: crate::m_11_stress::Enum29,
    pub field_1: bool,
    pub field_2: bool,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rel_1: Option<Box<crate::m_16_stress::Entity74>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50WhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFilter>,
    pub r#type: Option<crate::m_11_stress::Enum29Filter>,
    pub field_1: Option<crate::shared::filters::BoolFilter>,
    pub field_2: Option<crate::shared::filters::BoolFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub updated_at: Option<crate::shared::filters::DateTimeFilter>,
    pub rel_1: Option<crate::m_16_stress::Entity74RelationFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<Entity50WhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<Entity50WhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<Entity50WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50RelationFilter {
    pub is: Option<Box<crate::m_11_stress::Entity50WhereInput>>,
    pub is_not: Option<Box<crate::m_11_stress::Entity50WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50ListRelationFilter {
    pub some: Option<Box<crate::m_11_stress::Entity50WhereInput>>,
    pub every: Option<Box<crate::m_11_stress::Entity50WhereInput>>,
    pub none: Option<Box<crate::m_11_stress::Entity50WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50WhereUniqueInput {
    pub id: Option<String>,
    pub rel_fk_id_1: Option<String>,
    pub r#type: Option<crate::m_11_stress::Enum29>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50OrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub rel_fk_id_1: Option<crate::shared::filters::SortOrder>,
    pub r#type: Option<crate::shared::filters::SortOrder>,
    pub field_1: Option<crate::shared::filters::SortOrder>,
    pub field_2: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub updated_at: Option<crate::shared::filters::SortOrder>,
    pub rel_1: Option<Box<crate::m_16_stress::Entity74OrderByWithRelationInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50Select {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub r#type: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
    pub rel_1: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50Include {
    pub rel_1: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50CreateInput {
    pub r#type: crate::m_11_stress::Enum29,
    pub rel_1: Option<Box<crate::m_11_stress::Entity74CreateNestedOneWithoutEntity50Rel1Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50UncheckedCreateInput {
    pub rel_fk_id_1: String,
    pub r#type: crate::m_11_stress::Enum29,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50CreateManyInput {
    pub rel_fk_id_1: String,
    pub r#type: crate::m_11_stress::Enum29,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50UpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub r#type: Option<crate::m_11_stress::Enum29FieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub rel_1:
        Option<Box<crate::m_11_stress::Entity74UpdateOneRequiredWithoutEntity50Rel1NestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50UncheckedUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub r#type: Option<crate::m_11_stress::Enum29FieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50UpdateManyMutationInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub r#type: Option<crate::m_11_stress::Enum29FieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50UncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub r#type: Option<crate::m_11_stress::Enum29FieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74CreateWithoutEntity50Rel1Input {
    pub field_1: String,
    pub field_2: String,
    pub field_3: String,
    pub email: String,
    pub field_5: Option<String>,
    pub field_8: Option<i32>,
    pub field_9: Option<chrono::DateTime<chrono::Utc>>,
    pub field_10: Option<String>,
    pub field_14: Option<chrono::DateTime<chrono::Utc>>,
    pub field_16: Option<chrono::DateTime<chrono::Utc>>,
    pub field_17: Option<chrono::DateTime<chrono::Utc>>,
    pub field_18: Option<String>,
    pub rel_1: Option<Box<crate::m_16_stress::Entity59CreateNestedManyWithoutEntity74Rel1Input>>,
    pub rel_2: Option<Box<crate::m_16_stress::Entity29CreateNestedManyWithoutEntity74Rel2Input>>,
    pub rel_3: Option<Box<crate::m_16_stress::Entity30CreateNestedManyWithoutEntity74Rel3Input>>,
    pub rel_4: Option<Box<crate::m_16_stress::Entity32CreateNestedManyWithoutEntity74Rel4Input>>,
    pub rel_5: Option<Box<crate::m_16_stress::Entity37CreateNestedOneWithoutEntity74Rel5Input>>,
    pub rel_6: Option<Box<crate::m_16_stress::Entity38CreateNestedOneWithoutEntity74Rel6Input>>,
    pub rel_7: Option<Box<crate::m_16_stress::Entity37CreateNestedOneWithoutEntity74Rel7Input>>,
    pub rel_8: Option<Box<crate::m_16_stress::Entity10CreateNestedManyWithoutEntity74Rel8Input>>,
    pub rel_9: Option<Box<crate::m_16_stress::Entity5CreateNestedManyWithoutEntity74Rel9Input>>,
    pub rel_10: Option<Box<crate::m_16_stress::Entity14CreateNestedManyWithoutEntity74Rel10Input>>,
    pub rel_11: Option<Box<crate::m_16_stress::Entity75CreateNestedManyWithoutEntity74Rel11Input>>,
    pub rel_12: Option<Box<crate::m_16_stress::Entity6CreateNestedManyWithoutEntity74Rel12Input>>,
    pub rel_13: Option<Box<crate::m_16_stress::Entity44CreateNestedManyWithoutEntity74Rel13Input>>,
    pub rel_14: Option<Box<crate::m_16_stress::Entity46CreateNestedManyWithoutEntity74Rel14Input>>,
    pub rel_15: Option<Box<crate::m_16_stress::Entity47CreateNestedManyWithoutEntity74Rel15Input>>,
    pub rel_16: Option<Box<crate::m_16_stress::Entity48CreateNestedManyWithoutEntity74Rel16Input>>,
    pub rel_17: Option<Box<crate::m_16_stress::Entity62CreateNestedManyWithoutEntity74Rel17Input>>,
    pub rel_18: Option<Box<crate::m_16_stress::Entity49CreateNestedManyWithoutEntity74Rel18Input>>,
    pub rel_20: Option<Box<crate::m_16_stress::Entity7CreateNestedManyWithoutEntity74Rel20Input>>,
    pub rel_21: Option<Box<crate::m_16_stress::Entity16CreateNestedManyWithoutEntity74Rel21Input>>,
    pub rel_22: Option<Box<crate::m_16_stress::Entity18CreateNestedManyWithoutEntity74Rel22Input>>,
    pub rel_23: Option<Box<crate::m_16_stress::Entity42CreateNestedManyWithoutEntity74Rel23Input>>,
    pub rel_24: Option<Box<crate::m_16_stress::Entity42CreateNestedManyWithoutEntity74Rel24Input>>,
    pub rel_25: Option<Box<crate::m_16_stress::Entity19CreateNestedManyWithoutEntity74Rel25Input>>,
    pub rel_26: Option<Box<crate::m_16_stress::Entity20CreateNestedManyWithoutEntity74Rel26Input>>,
    pub rel_27: Option<Box<crate::m_16_stress::Entity21CreateNestedManyWithoutEntity74Rel27Input>>,
    pub rel_28: Option<Box<crate::m_16_stress::Entity21CreateNestedManyWithoutEntity74Rel28Input>>,
    pub rel_29: Option<Box<crate::m_16_stress::Entity24CreateNestedManyWithoutEntity74Rel29Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UncheckedCreateWithoutEntity50Rel1Input {
    pub field_1: String,
    pub field_2: String,
    pub field_3: String,
    pub email: String,
    pub field_5: Option<String>,
    pub field_8: Option<i32>,
    pub field_9: Option<chrono::DateTime<chrono::Utc>>,
    pub field_10: Option<String>,
    pub field_14: Option<chrono::DateTime<chrono::Utc>>,
    pub field_16: Option<chrono::DateTime<chrono::Utc>>,
    pub field_17: Option<chrono::DateTime<chrono::Utc>>,
    pub field_18: Option<String>,
    pub rel_fk_id_5: Option<String>,
    pub rel_fk_id_6: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74CreateOrConnectWithoutEntity50Rel1Input {
    pub r#where: Box<crate::m_16_stress::Entity74WhereUniqueInput>,
    pub create: Box<crate::m_11_stress::Entity74CreateWithoutEntity50Rel1Input>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UpdateWithoutEntity50Rel1Input {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::NullableIntFieldUpdateOperationsInput>,
    pub field_8: Option<crate::shared::filters::NullableIntFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub field_9: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_10: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_11: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub field_12: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_13: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_14: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_15: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_16: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_17: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_18: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub rel_1: Option<Box<crate::m_16_stress::Entity59UpdateManyWithoutEntity74Rel1NestedInput>>,
    pub rel_2: Option<Box<crate::m_16_stress::Entity29UpdateManyWithoutEntity74Rel2NestedInput>>,
    pub rel_3: Option<Box<crate::m_16_stress::Entity30UpdateManyWithoutEntity74Rel3NestedInput>>,
    pub rel_4: Option<Box<crate::m_16_stress::Entity32UpdateManyWithoutEntity74Rel4NestedInput>>,
    pub rel_5: Option<Box<crate::m_16_stress::Entity37UpdateOneWithoutEntity74Rel5NestedInput>>,
    pub rel_6: Option<Box<crate::m_16_stress::Entity38UpdateOneWithoutEntity74Rel6NestedInput>>,
    pub rel_7: Option<Box<crate::m_16_stress::Entity37UpdateOneWithoutEntity74Rel7NestedInput>>,
    pub rel_8: Option<Box<crate::m_16_stress::Entity10UpdateManyWithoutEntity74Rel8NestedInput>>,
    pub rel_9: Option<Box<crate::m_16_stress::Entity5UpdateManyWithoutEntity74Rel9NestedInput>>,
    pub rel_10: Option<Box<crate::m_16_stress::Entity14UpdateManyWithoutEntity74Rel10NestedInput>>,
    pub rel_11: Option<Box<crate::m_16_stress::Entity75UpdateManyWithoutEntity74Rel11NestedInput>>,
    pub rel_12: Option<Box<crate::m_16_stress::Entity6UpdateManyWithoutEntity74Rel12NestedInput>>,
    pub rel_13: Option<Box<crate::m_16_stress::Entity44UpdateManyWithoutEntity74Rel13NestedInput>>,
    pub rel_14: Option<Box<crate::m_16_stress::Entity46UpdateManyWithoutEntity74Rel14NestedInput>>,
    pub rel_15: Option<Box<crate::m_16_stress::Entity47UpdateManyWithoutEntity74Rel15NestedInput>>,
    pub rel_16: Option<Box<crate::m_16_stress::Entity48UpdateManyWithoutEntity74Rel16NestedInput>>,
    pub rel_17: Option<Box<crate::m_16_stress::Entity62UpdateManyWithoutEntity74Rel17NestedInput>>,
    pub rel_18: Option<Box<crate::m_16_stress::Entity49UpdateManyWithoutEntity74Rel18NestedInput>>,
    pub rel_20: Option<Box<crate::m_16_stress::Entity7UpdateManyWithoutEntity74Rel20NestedInput>>,
    pub rel_21: Option<Box<crate::m_16_stress::Entity16UpdateManyWithoutEntity74Rel21NestedInput>>,
    pub rel_22: Option<Box<crate::m_16_stress::Entity18UpdateManyWithoutEntity74Rel22NestedInput>>,
    pub rel_23: Option<Box<crate::m_16_stress::Entity42UpdateManyWithoutEntity74Rel23NestedInput>>,
    pub rel_24: Option<Box<crate::m_16_stress::Entity42UpdateManyWithoutEntity74Rel24NestedInput>>,
    pub rel_25: Option<Box<crate::m_16_stress::Entity19UpdateManyWithoutEntity74Rel25NestedInput>>,
    pub rel_26: Option<Box<crate::m_16_stress::Entity20UpdateManyWithoutEntity74Rel26NestedInput>>,
    pub rel_27: Option<Box<crate::m_16_stress::Entity21UpdateManyWithoutEntity74Rel27NestedInput>>,
    pub rel_28: Option<Box<crate::m_16_stress::Entity21UpdateManyWithoutEntity74Rel28NestedInput>>,
    pub rel_29: Option<Box<crate::m_16_stress::Entity24UpdateManyWithoutEntity74Rel29NestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UncheckedUpdateWithoutEntity50Rel1Input {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub email: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::NullableIntFieldUpdateOperationsInput>,
    pub field_8: Option<crate::shared::filters::NullableIntFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub field_9: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_10: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_11: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub field_12: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_13: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_14: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_15: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_16: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_17: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_18: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub rel_fk_id_5: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub rel_fk_id_6: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74CreateNestedOneWithoutEntity50Rel1Input {
    pub create: Option<Box<crate::m_11_stress::Entity74CreateWithoutEntity50Rel1Input>>,
    pub connect_or_create:
        Option<Box<crate::m_11_stress::Entity74CreateOrConnectWithoutEntity50Rel1Input>>,
    pub connect: Option<Box<crate::m_16_stress::Entity74WhereUniqueInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UpsertWithoutEntity50Rel1Input {
    pub update: Box<crate::m_11_stress::Entity74UpdateWithoutEntity50Rel1Input>,
    pub create: Box<crate::m_11_stress::Entity74CreateWithoutEntity50Rel1Input>,
    pub r#where: Option<Box<crate::m_16_stress::Entity74WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UpdateOneRequiredWithoutEntity50Rel1NestedInput {
    pub create: Option<Box<crate::m_11_stress::Entity74CreateWithoutEntity50Rel1Input>>,
    pub connect_or_create:
        Option<Box<crate::m_11_stress::Entity74CreateOrConnectWithoutEntity50Rel1Input>>,
    pub upsert: Option<Box<crate::m_11_stress::Entity74UpsertWithoutEntity50Rel1Input>>,
    pub connect: Option<Box<crate::m_16_stress::Entity74WhereUniqueInput>>,
    pub update:
        Option<Box<crate::m_11_stress::Entity74UpdateToOneWithWhereWithoutEntity50Rel1Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity74UpdateToOneWithWhereWithoutEntity50Rel1Input {
    pub r#where: Option<Box<crate::m_16_stress::Entity74WhereInput>>,
    pub data: Box<crate::m_11_stress::Entity74UpdateWithoutEntity50Rel1Input>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50ScalarWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFilter>,
    pub r#type: Option<crate::m_11_stress::Enum29Filter>,
    pub field_1: Option<crate::shared::filters::BoolFilter>,
    pub field_2: Option<crate::shared::filters::BoolFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub updated_at: Option<crate::shared::filters::DateTimeFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<Entity50ScalarWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<Entity50ScalarWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<Entity50ScalarWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50CountAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub r#type: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50AvgAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50SumAggregateInput {}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50MinAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50MaxAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub created_at: Option<bool>,
    pub updated_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50OrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub rel_fk_id_1: Option<crate::shared::filters::SortOrder>,
    pub r#type: Option<crate::shared::filters::SortOrder>,
    pub field_1: Option<crate::shared::filters::SortOrder>,
    pub field_2: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub updated_at: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<Entity50CountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<Entity50AvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<Entity50SumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<Entity50MinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<Entity50MaxAggregateInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity50AggregateInput {
    #[serde(rename = "where")]
    pub r#where: Option<Entity50WhereInput>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<Entity50CountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<Entity50AvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<Entity50SumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<Entity50MinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<Entity50MaxAggregateInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51 {
    pub id: String,
    pub rel_fk_id_1: String,
    pub field_1: String,
    pub field_2: String,
    pub field_3: String,
    pub field_4: Option<serde_json::Value>,
    pub status: crate::m_11_stress::Enum30,
    pub field_5: Option<chrono::DateTime<chrono::Utc>>,
    pub field_6: Option<String>,
    pub field_7: i32,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rel_1: Option<Box<crate::m_09_stress::Entity37>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51WhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFilter>,
    pub field_1: Option<crate::shared::filters::StringFilter>,
    pub field_2: Option<crate::shared::filters::StringFilter>,
    pub field_3: Option<crate::shared::filters::StringFilter>,
    pub field_4: Option<crate::shared::filters::JsonNullableFilter>,
    pub status: Option<crate::m_11_stress::Enum30Filter>,
    pub field_5: Option<crate::shared::filters::DateTimeNullableFilter>,
    pub field_6: Option<crate::shared::filters::StringNullableFilter>,
    pub field_7: Option<crate::shared::filters::IntFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub rel_1: Option<crate::m_09_stress::Entity37RelationFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<Entity51WhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<Entity51WhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<Entity51WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51RelationFilter {
    pub is: Option<Box<crate::m_11_stress::Entity51WhereInput>>,
    pub is_not: Option<Box<crate::m_11_stress::Entity51WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51ListRelationFilter {
    pub some: Option<Box<crate::m_11_stress::Entity51WhereInput>>,
    pub every: Option<Box<crate::m_11_stress::Entity51WhereInput>>,
    pub none: Option<Box<crate::m_11_stress::Entity51WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51WhereUniqueInput {
    pub id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51OrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub rel_fk_id_1: Option<crate::shared::filters::SortOrder>,
    pub field_1: Option<crate::shared::filters::SortOrder>,
    pub field_2: Option<crate::shared::filters::SortOrder>,
    pub field_3: Option<crate::shared::filters::SortOrder>,
    pub field_4: Option<crate::shared::filters::SortOrder>,
    pub status: Option<crate::shared::filters::SortOrder>,
    pub field_5: Option<crate::shared::filters::SortOrder>,
    pub field_6: Option<crate::shared::filters::SortOrder>,
    pub field_7: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub rel_1: Option<Box<crate::m_09_stress::Entity37OrderByWithRelationInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51Select {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub field_3: Option<bool>,
    pub field_4: Option<bool>,
    pub status: Option<bool>,
    pub field_5: Option<bool>,
    pub field_6: Option<bool>,
    pub field_7: Option<bool>,
    pub created_at: Option<bool>,
    pub rel_1: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51Include {
    pub rel_1: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51CreateInput {
    pub field_1: String,
    pub field_2: String,
    pub field_3: String,
    pub field_4: Option<serde_json::Value>,
    pub field_5: Option<chrono::DateTime<chrono::Utc>>,
    pub field_6: Option<String>,
    pub rel_1: Option<Box<crate::m_11_stress::Entity37CreateNestedOneWithoutEntity51Rel1Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51UncheckedCreateInput {
    pub rel_fk_id_1: String,
    pub field_1: String,
    pub field_2: String,
    pub field_3: String,
    pub field_4: Option<serde_json::Value>,
    pub field_5: Option<chrono::DateTime<chrono::Utc>>,
    pub field_6: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51CreateManyInput {
    pub rel_fk_id_1: String,
    pub field_1: String,
    pub field_2: String,
    pub field_3: String,
    pub field_4: Option<serde_json::Value>,
    pub field_5: Option<chrono::DateTime<chrono::Utc>>,
    pub field_6: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51UpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub status: Option<crate::m_11_stress::Enum30FieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub rel_1:
        Option<Box<crate::m_11_stress::Entity37UpdateOneRequiredWithoutEntity51Rel1NestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51UncheckedUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub status: Option<crate::m_11_stress::Enum30FieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51UpdateManyMutationInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub status: Option<crate::m_11_stress::Enum30FieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51UncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::NullableJsonFieldUpdateOperationsInput>,
    pub status: Option<crate::m_11_stress::Enum30FieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::NullableDateTimeFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37CreateWithoutEntity51Rel1Input {
    pub name: String,
    pub field_1: Option<String>,
    pub field_2: Option<String>,
    pub rel_1: Option<Box<crate::m_09_stress::Entity66CreateNestedOneWithoutEntity37Rel1Input>>,
    pub rel_2: Option<Box<crate::m_09_stress::Entity74CreateNestedManyWithoutEntity37Rel2Input>>,
    pub rel_3: Option<Box<crate::m_09_stress::Entity74CreateNestedOneWithoutEntity37Rel3Input>>,
    pub rel_4: Option<Box<crate::m_09_stress::Entity29CreateNestedManyWithoutEntity37Rel4Input>>,
    pub rel_5: Option<Box<crate::m_09_stress::Entity19CreateNestedManyWithoutEntity37Rel5Input>>,
    pub rel_6: Option<Box<crate::m_09_stress::Entity26CreateNestedManyWithoutEntity37Rel6Input>>,
    pub rel_7: Option<Box<crate::m_09_stress::Entity13CreateNestedManyWithoutEntity37Rel7Input>>,
    pub rel_8: Option<Box<crate::m_09_stress::Entity30CreateNestedManyWithoutEntity37Rel8Input>>,
    pub rel_9: Option<Box<crate::m_09_stress::Entity41CreateNestedManyWithoutEntity37Rel9Input>>,
    pub rel_10: Option<Box<crate::m_09_stress::Entity10CreateNestedManyWithoutEntity37Rel10Input>>,
    pub rel_11: Option<Box<crate::m_09_stress::Entity14CreateNestedManyWithoutEntity37Rel11Input>>,
    pub rel_12: Option<Box<crate::m_09_stress::Entity27CreateNestedManyWithoutEntity37Rel12Input>>,
    pub rel_13: Option<Box<crate::m_09_stress::Entity15CreateNestedManyWithoutEntity37Rel13Input>>,
    pub rel_14: Option<Box<crate::m_09_stress::Entity44CreateNestedManyWithoutEntity37Rel14Input>>,
    pub rel_15: Option<Box<crate::m_09_stress::Entity46CreateNestedManyWithoutEntity37Rel15Input>>,
    pub rel_16: Option<Box<crate::m_09_stress::Entity47CreateNestedManyWithoutEntity37Rel16Input>>,
    pub rel_17: Option<Box<crate::m_09_stress::Entity60CreateNestedManyWithoutEntity37Rel17Input>>,
    pub rel_18: Option<Box<crate::m_09_stress::Entity49CreateNestedManyWithoutEntity37Rel18Input>>,
    pub rel_20: Option<Box<crate::m_09_stress::Entity38CreateNestedManyWithoutEntity37Rel20Input>>,
    pub rel_21: Option<Box<crate::m_09_stress::Entity38CreateNestedOneWithoutEntity37Rel21Input>>,
    pub rel_22: Option<Box<crate::m_09_stress::Entity1CreateNestedOneWithoutEntity37Rel22Input>>,
    pub rel_23: Option<Box<crate::m_09_stress::Entity2CreateNestedManyWithoutEntity37Rel23Input>>,
    pub rel_24: Option<Box<crate::m_09_stress::Entity3CreateNestedManyWithoutEntity37Rel24Input>>,
    pub rel_25: Option<Box<crate::m_09_stress::Entity63CreateNestedManyWithoutEntity37Rel25Input>>,
    pub rel_26: Option<Box<crate::m_09_stress::Entity64CreateNestedManyWithoutEntity37Rel26Input>>,
    pub rel_27: Option<Box<crate::m_09_stress::Entity65CreateNestedManyWithoutEntity37Rel27Input>>,
    pub rel_28: Option<Box<crate::m_09_stress::Entity16CreateNestedManyWithoutEntity37Rel28Input>>,
    pub rel_29: Option<Box<crate::m_09_stress::Entity18CreateNestedManyWithoutEntity37Rel29Input>>,
    pub rel_30: Option<Box<crate::m_09_stress::Entity42CreateNestedManyWithoutEntity37Rel30Input>>,
    pub rel_31: Option<Box<crate::m_09_stress::Entity43CreateNestedManyWithoutEntity37Rel31Input>>,
    pub rel_32: Option<Box<crate::m_09_stress::Entity20CreateNestedManyWithoutEntity37Rel32Input>>,
    pub rel_33: Option<Box<crate::m_09_stress::Entity21CreateNestedManyWithoutEntity37Rel33Input>>,
    pub rel_34: Option<Box<crate::m_09_stress::Entity22CreateNestedManyWithoutEntity37Rel34Input>>,
    pub rel_35: Option<Box<crate::m_09_stress::Entity23CreateNestedManyWithoutEntity37Rel35Input>>,
    pub rel_36: Option<Box<crate::m_09_stress::Entity24CreateNestedManyWithoutEntity37Rel36Input>>,
    pub rel_37: Option<Box<crate::m_09_stress::Entity25CreateNestedManyWithoutEntity37Rel37Input>>,
    pub rel_38: Option<Box<crate::m_09_stress::Entity35CreateNestedManyWithoutEntity37Rel38Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UncheckedCreateWithoutEntity51Rel1Input {
    pub name: String,
    pub field_1: Option<String>,
    pub field_2: Option<String>,
    pub rel_fk_id_1: Option<String>,
    pub rel_fk_id_3: Option<String>,
    pub rel_fk_id_21: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37CreateOrConnectWithoutEntity51Rel1Input {
    pub r#where: Box<crate::m_09_stress::Entity37WhereUniqueInput>,
    pub create: Box<crate::m_11_stress::Entity37CreateWithoutEntity51Rel1Input>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UpdateWithoutEntity51Rel1Input {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub field_3: Option<crate::m_16_stress::Enum37FieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub rel_1: Option<Box<crate::m_09_stress::Entity66UpdateOneWithoutEntity37Rel1NestedInput>>,
    pub rel_2: Option<Box<crate::m_09_stress::Entity74UpdateManyWithoutEntity37Rel2NestedInput>>,
    pub rel_3: Option<Box<crate::m_09_stress::Entity74UpdateOneWithoutEntity37Rel3NestedInput>>,
    pub rel_4: Option<Box<crate::m_09_stress::Entity29UpdateManyWithoutEntity37Rel4NestedInput>>,
    pub rel_5: Option<Box<crate::m_09_stress::Entity19UpdateManyWithoutEntity37Rel5NestedInput>>,
    pub rel_6: Option<Box<crate::m_09_stress::Entity26UpdateManyWithoutEntity37Rel6NestedInput>>,
    pub rel_7: Option<Box<crate::m_09_stress::Entity13UpdateManyWithoutEntity37Rel7NestedInput>>,
    pub rel_8: Option<Box<crate::m_09_stress::Entity30UpdateManyWithoutEntity37Rel8NestedInput>>,
    pub rel_9: Option<Box<crate::m_09_stress::Entity41UpdateManyWithoutEntity37Rel9NestedInput>>,
    pub rel_10: Option<Box<crate::m_09_stress::Entity10UpdateManyWithoutEntity37Rel10NestedInput>>,
    pub rel_11: Option<Box<crate::m_09_stress::Entity14UpdateManyWithoutEntity37Rel11NestedInput>>,
    pub rel_12: Option<Box<crate::m_09_stress::Entity27UpdateManyWithoutEntity37Rel12NestedInput>>,
    pub rel_13: Option<Box<crate::m_09_stress::Entity15UpdateManyWithoutEntity37Rel13NestedInput>>,
    pub rel_14: Option<Box<crate::m_09_stress::Entity44UpdateManyWithoutEntity37Rel14NestedInput>>,
    pub rel_15: Option<Box<crate::m_09_stress::Entity46UpdateManyWithoutEntity37Rel15NestedInput>>,
    pub rel_16: Option<Box<crate::m_09_stress::Entity47UpdateManyWithoutEntity37Rel16NestedInput>>,
    pub rel_17: Option<Box<crate::m_09_stress::Entity60UpdateManyWithoutEntity37Rel17NestedInput>>,
    pub rel_18: Option<Box<crate::m_09_stress::Entity49UpdateManyWithoutEntity37Rel18NestedInput>>,
    pub rel_20: Option<Box<crate::m_09_stress::Entity38UpdateManyWithoutEntity37Rel20NestedInput>>,
    pub rel_21: Option<Box<crate::m_09_stress::Entity38UpdateOneWithoutEntity37Rel21NestedInput>>,
    pub rel_22: Option<Box<crate::m_09_stress::Entity1UpdateOneWithoutEntity37Rel22NestedInput>>,
    pub rel_23: Option<Box<crate::m_09_stress::Entity2UpdateManyWithoutEntity37Rel23NestedInput>>,
    pub rel_24: Option<Box<crate::m_09_stress::Entity3UpdateManyWithoutEntity37Rel24NestedInput>>,
    pub rel_25: Option<Box<crate::m_09_stress::Entity63UpdateManyWithoutEntity37Rel25NestedInput>>,
    pub rel_26: Option<Box<crate::m_09_stress::Entity64UpdateManyWithoutEntity37Rel26NestedInput>>,
    pub rel_27: Option<Box<crate::m_09_stress::Entity65UpdateManyWithoutEntity37Rel27NestedInput>>,
    pub rel_28: Option<Box<crate::m_09_stress::Entity16UpdateManyWithoutEntity37Rel28NestedInput>>,
    pub rel_29: Option<Box<crate::m_09_stress::Entity18UpdateManyWithoutEntity37Rel29NestedInput>>,
    pub rel_30: Option<Box<crate::m_09_stress::Entity42UpdateManyWithoutEntity37Rel30NestedInput>>,
    pub rel_31: Option<Box<crate::m_09_stress::Entity43UpdateManyWithoutEntity37Rel31NestedInput>>,
    pub rel_32: Option<Box<crate::m_09_stress::Entity20UpdateManyWithoutEntity37Rel32NestedInput>>,
    pub rel_33: Option<Box<crate::m_09_stress::Entity21UpdateManyWithoutEntity37Rel33NestedInput>>,
    pub rel_34: Option<Box<crate::m_09_stress::Entity22UpdateManyWithoutEntity37Rel34NestedInput>>,
    pub rel_35: Option<Box<crate::m_09_stress::Entity23UpdateManyWithoutEntity37Rel35NestedInput>>,
    pub rel_36: Option<Box<crate::m_09_stress::Entity24UpdateManyWithoutEntity37Rel36NestedInput>>,
    pub rel_37: Option<Box<crate::m_09_stress::Entity25UpdateManyWithoutEntity37Rel37NestedInput>>,
    pub rel_38: Option<Box<crate::m_09_stress::Entity35UpdateManyWithoutEntity37Rel38NestedInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UncheckedUpdateWithoutEntity51Rel1Input {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub name: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub field_1: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_2: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub updated_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub rel_fk_id_1: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub rel_fk_id_3: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_3: Option<crate::m_16_stress::Enum37FieldUpdateOperationsInput>,
    pub field_4: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_5: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub field_6: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub rel_fk_id_21: Option<crate::shared::filters::NullableStringFieldUpdateOperationsInput>,
    pub field_7: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37CreateNestedOneWithoutEntity51Rel1Input {
    pub create: Option<Box<crate::m_11_stress::Entity37CreateWithoutEntity51Rel1Input>>,
    pub connect_or_create:
        Option<Box<crate::m_11_stress::Entity37CreateOrConnectWithoutEntity51Rel1Input>>,
    pub connect: Option<Box<crate::m_09_stress::Entity37WhereUniqueInput>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UpsertWithoutEntity51Rel1Input {
    pub update: Box<crate::m_11_stress::Entity37UpdateWithoutEntity51Rel1Input>,
    pub create: Box<crate::m_11_stress::Entity37CreateWithoutEntity51Rel1Input>,
    pub r#where: Option<Box<crate::m_09_stress::Entity37WhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UpdateOneRequiredWithoutEntity51Rel1NestedInput {
    pub create: Option<Box<crate::m_11_stress::Entity37CreateWithoutEntity51Rel1Input>>,
    pub connect_or_create:
        Option<Box<crate::m_11_stress::Entity37CreateOrConnectWithoutEntity51Rel1Input>>,
    pub upsert: Option<Box<crate::m_11_stress::Entity37UpsertWithoutEntity51Rel1Input>>,
    pub connect: Option<Box<crate::m_09_stress::Entity37WhereUniqueInput>>,
    pub update:
        Option<Box<crate::m_11_stress::Entity37UpdateToOneWithWhereWithoutEntity51Rel1Input>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity37UpdateToOneWithWhereWithoutEntity51Rel1Input {
    pub r#where: Option<Box<crate::m_09_stress::Entity37WhereInput>>,
    pub data: Box<crate::m_11_stress::Entity37UpdateWithoutEntity51Rel1Input>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51ScalarWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub rel_fk_id_1: Option<crate::shared::filters::StringFilter>,
    pub field_1: Option<crate::shared::filters::StringFilter>,
    pub field_2: Option<crate::shared::filters::StringFilter>,
    pub field_3: Option<crate::shared::filters::StringFilter>,
    pub field_4: Option<crate::shared::filters::JsonNullableFilter>,
    pub status: Option<crate::m_11_stress::Enum30Filter>,
    pub field_5: Option<crate::shared::filters::DateTimeNullableFilter>,
    pub field_6: Option<crate::shared::filters::StringNullableFilter>,
    pub field_7: Option<crate::shared::filters::IntFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<Entity51ScalarWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<Entity51ScalarWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<Entity51ScalarWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51CountAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub field_3: Option<bool>,
    pub field_4: Option<bool>,
    pub status: Option<bool>,
    pub field_5: Option<bool>,
    pub field_6: Option<bool>,
    pub field_7: Option<bool>,
    pub created_at: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51AvgAggregateInput {
    pub field_7: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51SumAggregateInput {
    pub field_7: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51MinAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub field_3: Option<bool>,
    pub field_5: Option<bool>,
    pub field_6: Option<bool>,
    pub field_7: Option<bool>,
    pub created_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51MaxAggregateInput {
    pub id: Option<bool>,
    pub rel_fk_id_1: Option<bool>,
    pub field_1: Option<bool>,
    pub field_2: Option<bool>,
    pub field_3: Option<bool>,
    pub field_5: Option<bool>,
    pub field_6: Option<bool>,
    pub field_7: Option<bool>,
    pub created_at: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51OrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub rel_fk_id_1: Option<crate::shared::filters::SortOrder>,
    pub field_1: Option<crate::shared::filters::SortOrder>,
    pub field_2: Option<crate::shared::filters::SortOrder>,
    pub field_3: Option<crate::shared::filters::SortOrder>,
    pub field_4: Option<crate::shared::filters::SortOrder>,
    pub status: Option<crate::shared::filters::SortOrder>,
    pub field_5: Option<crate::shared::filters::SortOrder>,
    pub field_6: Option<crate::shared::filters::SortOrder>,
    pub field_7: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<Entity51CountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<Entity51AvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<Entity51SumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<Entity51MinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<Entity51MaxAggregateInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity51AggregateInput {
    #[serde(rename = "where")]
    pub r#where: Option<Entity51WhereInput>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<Entity51CountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<Entity51AvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<Entity51SumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<Entity51MinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<Entity51MaxAggregateInput>,
}
