// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalars {
    pub id: String,
    pub text: String,
    pub var_char: String,
    pub count: i32,
    pub small_count: i32,
    pub big: i64,
    pub ratio: f64,
    pub real: f64,
    pub amount: rust_decimal::Decimal,
    pub active: bool,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub date_only: chrono::DateTime<chrono::Utc>,
    pub time_only: chrono::DateTime<chrono::Utc>,
    pub with_tz: chrono::DateTime<chrono::Utc>,
    pub without_tz: chrono::DateTime<chrono::Utc>,
    pub meta: serde_json::Value,
    pub blob: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub text: Option<crate::shared::filters::StringFilter>,
    pub var_char: Option<crate::shared::filters::StringFilter>,
    pub count: Option<crate::shared::filters::IntFilter>,
    pub small_count: Option<crate::shared::filters::IntFilter>,
    pub big: Option<crate::shared::filters::BigIntFilter>,
    pub ratio: Option<crate::shared::filters::FloatFilter>,
    pub real: Option<crate::shared::filters::FloatFilter>,
    pub amount: Option<crate::shared::filters::DecimalFilter>,
    pub active: Option<crate::shared::filters::BoolFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub date_only: Option<crate::shared::filters::DateTimeFilter>,
    pub time_only: Option<crate::shared::filters::DateTimeFilter>,
    pub with_tz: Option<crate::shared::filters::DateTimeFilter>,
    pub without_tz: Option<crate::shared::filters::DateTimeFilter>,
    pub meta: Option<crate::shared::filters::JsonFilter>,
    pub blob: Option<crate::shared::filters::BytesFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<AllScalarsWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<AllScalarsWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<AllScalarsWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsRelationFilter {
    pub is: Option<Box<crate::schema::AllScalarsWhereInput>>,
    pub is_not: Option<Box<crate::schema::AllScalarsWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsListRelationFilter {
    pub some: Option<Box<crate::schema::AllScalarsWhereInput>>,
    pub every: Option<Box<crate::schema::AllScalarsWhereInput>>,
    pub none: Option<Box<crate::schema::AllScalarsWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsWhereUniqueInput {}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsOrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub text: Option<crate::shared::filters::SortOrder>,
    pub var_char: Option<crate::shared::filters::SortOrder>,
    pub count: Option<crate::shared::filters::SortOrder>,
    pub small_count: Option<crate::shared::filters::SortOrder>,
    pub big: Option<crate::shared::filters::SortOrder>,
    pub ratio: Option<crate::shared::filters::SortOrder>,
    pub real: Option<crate::shared::filters::SortOrder>,
    pub amount: Option<crate::shared::filters::SortOrder>,
    pub active: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub date_only: Option<crate::shared::filters::SortOrder>,
    pub time_only: Option<crate::shared::filters::SortOrder>,
    pub with_tz: Option<crate::shared::filters::SortOrder>,
    pub without_tz: Option<crate::shared::filters::SortOrder>,
    pub meta: Option<crate::shared::filters::SortOrder>,
    pub blob: Option<crate::shared::filters::SortOrder>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsSelect {
    pub id: Option<bool>,
    pub text: Option<bool>,
    pub var_char: Option<bool>,
    pub count: Option<bool>,
    pub small_count: Option<bool>,
    pub big: Option<bool>,
    pub ratio: Option<bool>,
    pub real: Option<bool>,
    pub amount: Option<bool>,
    pub active: Option<bool>,
    pub created_at: Option<bool>,
    pub date_only: Option<bool>,
    pub time_only: Option<bool>,
    pub with_tz: Option<bool>,
    pub without_tz: Option<bool>,
    pub meta: Option<bool>,
    pub blob: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsInclude {}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsCreateInput {
    pub id: String,
    pub text: String,
    pub var_char: String,
    pub count: i32,
    pub small_count: i32,
    pub big: i64,
    pub ratio: f64,
    pub real: f64,
    pub amount: rust_decimal::Decimal,
    pub active: bool,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub date_only: chrono::DateTime<chrono::Utc>,
    pub time_only: chrono::DateTime<chrono::Utc>,
    pub with_tz: chrono::DateTime<chrono::Utc>,
    pub without_tz: chrono::DateTime<chrono::Utc>,
    pub meta: serde_json::Value,
    pub blob: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsUncheckedCreateInput {
    pub id: String,
    pub text: String,
    pub var_char: String,
    pub count: i32,
    pub small_count: i32,
    pub big: i64,
    pub ratio: f64,
    pub real: f64,
    pub amount: rust_decimal::Decimal,
    pub active: bool,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub date_only: chrono::DateTime<chrono::Utc>,
    pub time_only: chrono::DateTime<chrono::Utc>,
    pub with_tz: chrono::DateTime<chrono::Utc>,
    pub without_tz: chrono::DateTime<chrono::Utc>,
    pub meta: serde_json::Value,
    pub blob: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsCreateManyInput {
    pub id: String,
    pub text: String,
    pub var_char: String,
    pub count: i32,
    pub small_count: i32,
    pub big: i64,
    pub ratio: f64,
    pub real: f64,
    pub amount: rust_decimal::Decimal,
    pub active: bool,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub date_only: chrono::DateTime<chrono::Utc>,
    pub time_only: chrono::DateTime<chrono::Utc>,
    pub with_tz: chrono::DateTime<chrono::Utc>,
    pub without_tz: chrono::DateTime<chrono::Utc>,
    pub meta: serde_json::Value,
    pub blob: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub text: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub var_char: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub count: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub small_count: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub big: Option<crate::shared::filters::BigIntFieldUpdateOperationsInput>,
    pub ratio: Option<crate::shared::filters::FloatFieldUpdateOperationsInput>,
    pub real: Option<crate::shared::filters::FloatFieldUpdateOperationsInput>,
    pub amount: Option<crate::shared::filters::DecimalFieldUpdateOperationsInput>,
    pub active: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub date_only: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub time_only: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub with_tz: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub without_tz: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub meta: Option<crate::shared::filters::JsonFieldUpdateOperationsInput>,
    pub blob: Option<crate::shared::filters::BytesFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsUncheckedUpdateInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub text: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub var_char: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub count: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub small_count: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub big: Option<crate::shared::filters::BigIntFieldUpdateOperationsInput>,
    pub ratio: Option<crate::shared::filters::FloatFieldUpdateOperationsInput>,
    pub real: Option<crate::shared::filters::FloatFieldUpdateOperationsInput>,
    pub amount: Option<crate::shared::filters::DecimalFieldUpdateOperationsInput>,
    pub active: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub date_only: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub time_only: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub with_tz: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub without_tz: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub meta: Option<crate::shared::filters::JsonFieldUpdateOperationsInput>,
    pub blob: Option<crate::shared::filters::BytesFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsUpdateManyMutationInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub text: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub var_char: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub count: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub small_count: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub big: Option<crate::shared::filters::BigIntFieldUpdateOperationsInput>,
    pub ratio: Option<crate::shared::filters::FloatFieldUpdateOperationsInput>,
    pub real: Option<crate::shared::filters::FloatFieldUpdateOperationsInput>,
    pub amount: Option<crate::shared::filters::DecimalFieldUpdateOperationsInput>,
    pub active: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub date_only: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub time_only: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub with_tz: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub without_tz: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub meta: Option<crate::shared::filters::JsonFieldUpdateOperationsInput>,
    pub blob: Option<crate::shared::filters::BytesFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsUncheckedUpdateManyInput {
    pub id: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub text: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub var_char: Option<crate::shared::filters::StringFieldUpdateOperationsInput>,
    pub count: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub small_count: Option<crate::shared::filters::IntFieldUpdateOperationsInput>,
    pub big: Option<crate::shared::filters::BigIntFieldUpdateOperationsInput>,
    pub ratio: Option<crate::shared::filters::FloatFieldUpdateOperationsInput>,
    pub real: Option<crate::shared::filters::FloatFieldUpdateOperationsInput>,
    pub amount: Option<crate::shared::filters::DecimalFieldUpdateOperationsInput>,
    pub active: Option<crate::shared::filters::BoolFieldUpdateOperationsInput>,
    pub created_at: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub date_only: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub time_only: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub with_tz: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub without_tz: Option<crate::shared::filters::DateTimeFieldUpdateOperationsInput>,
    pub meta: Option<crate::shared::filters::JsonFieldUpdateOperationsInput>,
    pub blob: Option<crate::shared::filters::BytesFieldUpdateOperationsInput>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsCountAggregateInput {
    pub id: Option<bool>,
    pub text: Option<bool>,
    pub var_char: Option<bool>,
    pub count: Option<bool>,
    pub small_count: Option<bool>,
    pub big: Option<bool>,
    pub ratio: Option<bool>,
    pub real: Option<bool>,
    pub amount: Option<bool>,
    pub active: Option<bool>,
    pub created_at: Option<bool>,
    pub date_only: Option<bool>,
    pub time_only: Option<bool>,
    pub with_tz: Option<bool>,
    pub without_tz: Option<bool>,
    pub meta: Option<bool>,
    pub blob: Option<bool>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsAvgAggregateInput {
    pub count: Option<bool>,
    pub small_count: Option<bool>,
    pub big: Option<bool>,
    pub ratio: Option<bool>,
    pub real: Option<bool>,
    pub amount: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsSumAggregateInput {
    pub count: Option<bool>,
    pub small_count: Option<bool>,
    pub big: Option<bool>,
    pub ratio: Option<bool>,
    pub real: Option<bool>,
    pub amount: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsMinAggregateInput {
    pub id: Option<bool>,
    pub text: Option<bool>,
    pub var_char: Option<bool>,
    pub count: Option<bool>,
    pub small_count: Option<bool>,
    pub big: Option<bool>,
    pub ratio: Option<bool>,
    pub real: Option<bool>,
    pub amount: Option<bool>,
    pub active: Option<bool>,
    pub created_at: Option<bool>,
    pub date_only: Option<bool>,
    pub time_only: Option<bool>,
    pub with_tz: Option<bool>,
    pub without_tz: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsMaxAggregateInput {
    pub id: Option<bool>,
    pub text: Option<bool>,
    pub var_char: Option<bool>,
    pub count: Option<bool>,
    pub small_count: Option<bool>,
    pub big: Option<bool>,
    pub ratio: Option<bool>,
    pub real: Option<bool>,
    pub amount: Option<bool>,
    pub active: Option<bool>,
    pub created_at: Option<bool>,
    pub date_only: Option<bool>,
    pub time_only: Option<bool>,
    pub with_tz: Option<bool>,
    pub without_tz: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsOrderByWithAggregationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub text: Option<crate::shared::filters::SortOrder>,
    pub var_char: Option<crate::shared::filters::SortOrder>,
    pub count: Option<crate::shared::filters::SortOrder>,
    pub small_count: Option<crate::shared::filters::SortOrder>,
    pub big: Option<crate::shared::filters::SortOrder>,
    pub ratio: Option<crate::shared::filters::SortOrder>,
    pub real: Option<crate::shared::filters::SortOrder>,
    pub amount: Option<crate::shared::filters::SortOrder>,
    pub active: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub date_only: Option<crate::shared::filters::SortOrder>,
    pub time_only: Option<crate::shared::filters::SortOrder>,
    pub with_tz: Option<crate::shared::filters::SortOrder>,
    pub without_tz: Option<crate::shared::filters::SortOrder>,
    pub meta: Option<crate::shared::filters::SortOrder>,
    pub blob: Option<crate::shared::filters::SortOrder>,
    #[serde(rename = "_count")]
    pub aggregate_count: Option<AllScalarsCountAggregateInput>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<AllScalarsAvgAggregateInput>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<AllScalarsSumAggregateInput>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<AllScalarsMinAggregateInput>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<AllScalarsMaxAggregateInput>,
}
