// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalars {
    pub id: String,
    pub text: String,
    pub var_char: String,
    pub count: i32,
    pub small_count: i32,
    pub big: i64,
    pub ratio: f64,
    pub real: f64,
    pub amount: rust_decimal::Decimal,
    pub active: bool,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub date_only: chrono::DateTime<chrono::Utc>,
    pub time_only: chrono::DateTime<chrono::Utc>,
    pub with_tz: chrono::DateTime<chrono::Utc>,
    pub without_tz: chrono::DateTime<chrono::Utc>,
    pub meta: serde_json::Value,
    pub blob: Vec<u8>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsWhereInput {
    pub id: Option<crate::shared::filters::StringFilter>,
    pub text: Option<crate::shared::filters::StringFilter>,
    pub var_char: Option<crate::shared::filters::StringFilter>,
    pub count: Option<crate::shared::filters::IntFilter>,
    pub small_count: Option<crate::shared::filters::IntFilter>,
    pub big: Option<crate::shared::filters::BigIntFilter>,
    pub ratio: Option<crate::shared::filters::FloatFilter>,
    pub real: Option<crate::shared::filters::FloatFilter>,
    pub amount: Option<crate::shared::filters::DecimalFilter>,
    pub active: Option<crate::shared::filters::BoolFilter>,
    pub created_at: Option<crate::shared::filters::DateTimeFilter>,
    pub date_only: Option<crate::shared::filters::DateTimeFilter>,
    pub time_only: Option<crate::shared::filters::DateTimeFilter>,
    pub with_tz: Option<crate::shared::filters::DateTimeFilter>,
    pub without_tz: Option<crate::shared::filters::DateTimeFilter>,
    pub meta: Option<crate::shared::filters::JsonFilter>,
    pub blob: Option<crate::shared::filters::BytesFilter>,
    #[serde(rename = "AND")]
    pub and: Option<Vec<AllScalarsWhereInput>>,
    #[serde(rename = "OR")]
    pub or: Option<Vec<AllScalarsWhereInput>>,
    #[serde(rename = "NOT")]
    pub not: Option<Vec<AllScalarsWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsRelationFilter {
    pub is: Option<Box<crate::schema::AllScalarsWhereInput>>,
    pub is_not: Option<Box<crate::schema::AllScalarsWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsListRelationFilter {
    pub some: Option<Box<crate::schema::AllScalarsWhereInput>>,
    pub every: Option<Box<crate::schema::AllScalarsWhereInput>>,
    pub none: Option<Box<crate::schema::AllScalarsWhereInput>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsWhereUniqueInput {}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsOrderByWithRelationInput {
    pub id: Option<crate::shared::filters::SortOrder>,
    pub text: Option<crate::shared::filters::SortOrder>,
    pub var_char: Option<crate::shared::filters::SortOrder>,
    pub count: Option<crate::shared::filters::SortOrder>,
    pub small_count: Option<crate::shared::filters::SortOrder>,
    pub big: Option<crate::shared::filters::SortOrder>,
    pub ratio: Option<crate::shared::filters::SortOrder>,
    pub real: Option<crate::shared::filters::SortOrder>,
    pub amount: Option<crate::shared::filters::SortOrder>,
    pub active: Option<crate::shared::filters::SortOrder>,
    pub created_at: Option<crate::shared::filters::SortOrder>,
    pub date_only: Option<crate::shared::filters::SortOrder>,
    pub time_only: Option<crate::shared::filters::SortOrder>,
    pub with_tz: Option<crate::shared::filters::SortOrder>,
    pub without_tz: Option<crate::shared::filters::SortOrder>,
    pub meta: Option<crate::shared::filters::SortOrder>,
    pub blob: Option<crate::shared::filters::SortOrder>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsSelect {
    pub id: Option<bool>,
    pub text: Option<bool>,
    pub var_char: Option<bool>,
    pub count: Option<bool>,
    pub small_count: Option<bool>,
    pub big: Option<bool>,
    pub ratio: Option<bool>,
    pub real: Option<bool>,
    pub amount: Option<bool>,
    pub active: Option<bool>,
    pub created_at: Option<bool>,
    pub date_only: Option<bool>,
    pub time_only: Option<bool>,
    pub with_tz: Option<bool>,
    pub without_tz: Option<bool>,
    pub meta: Option<bool>,
    pub blob: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AllScalarsInclude {}
