// @generated by prisma-rust-generator — do not edit by hand
#![allow(clippy::upper_case_acronyms, dead_code)]

use sqlx::Row as _;

impl sqlx::FromRow<'_, sqlx::postgres::PgRow> for crate::m_06_stress::Entity26 {
    fn from_row(row: &sqlx::postgres::PgRow) -> sqlx::Result<Self> {
        Ok(crate::m_06_stress::Entity26 {
            id: row.try_get("id")?,
            rel_fk_id_1: row.try_get("rel_fk_id_1")?,
            field_1: row.try_get("field_1")?,
            rel_fk_id_3: row.try_get("rel_fk_id_3")?,
            field_2: row.try_get("field_2")?,
            created_at: row.try_get("created_at")?,
            updated_at: row.try_get("updated_at")?,
            rel_1: None,
            rel_2: Vec::new(),
            rel_3: None,
            rel_4: Vec::new(),
            rel_5: None,
        })
    }
}

pub(crate) fn push_entity26_where(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Postgres>,
    w: &crate::m_06_stress::Entity26WhereInput,
) -> bool {
    let mut any = false;
    if let Some(f) = &w.id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "id", f);
    }
    if let Some(f) = &w.rel_fk_id_1 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "rel_fk_id_1", f);
    }
    if let Some(f) = &w.field_1 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_json_filter(qb, "field_1", f);
    }
    if let Some(f) = &w.rel_fk_id_3 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "rel_fk_id_3", f);
    }
    if let Some(f) = &w.field_2 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_enum6_filter(qb, "field_2", f);
    }
    if let Some(f) = &w.created_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_filter(qb, "created_at", f);
    }
    if let Some(f) = &w.updated_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_filter(qb, "updated_at", f);
    }
    if let Some(rel) = &w.rel_1 {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"table_entity37\" t WHERE t.\"id\" = \"table_entity26\".\"rel_fk_id_1\" AND (");
            if !crate::engine::sqlx_postgres::m_09_stress::push_entity37_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity37\" t WHERE t.\"id\" = \"table_entity26\".\"rel_fk_id_1\" AND (");
            if !crate::engine::sqlx_postgres::m_09_stress::push_entity37_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.rel_2 {
        if let Some(sub) = &rel.every {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity29\" t WHERE t.\"rel_fk_id_3\" = \"table_entity26\".\"id\" AND NOT (");
            if !crate::engine::sqlx_postgres::m_07_stress::push_entity29_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.some {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"table_entity29\" t WHERE t.\"rel_fk_id_3\" = \"table_entity26\".\"id\" AND (");
            if !crate::engine::sqlx_postgres::m_07_stress::push_entity29_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.none {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity29\" t WHERE t.\"rel_fk_id_3\" = \"table_entity26\".\"id\" AND (");
            if !crate::engine::sqlx_postgres::m_07_stress::push_entity29_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.rel_3 {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"table_entity19\" t WHERE t.\"id\" = \"table_entity26\".\"rel_fk_id_3\" AND (");
            if !crate::engine::sqlx_postgres::m_05_stress::push_entity19_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity19\" t WHERE t.\"id\" = \"table_entity26\".\"rel_fk_id_3\" AND (");
            if !crate::engine::sqlx_postgres::m_05_stress::push_entity19_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.rel_4 {
        if let Some(sub) = &rel.every {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity12\" t WHERE t.\"rel_fk_id_2\" = \"table_entity26\".\"id\" AND NOT (");
            if !crate::engine::sqlx_postgres::m_03_stress::push_entity12_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.some {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"table_entity12\" t WHERE t.\"rel_fk_id_2\" = \"table_entity26\".\"id\" AND (");
            if !crate::engine::sqlx_postgres::m_03_stress::push_entity12_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.none {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity12\" t WHERE t.\"rel_fk_id_2\" = \"table_entity26\".\"id\" AND (");
            if !crate::engine::sqlx_postgres::m_03_stress::push_entity12_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    // TODO(prisma-rust-generator): multi-FK to-one relation `rel_5` on `Entity26` skipped
    // (composite FK relation filters not yet supported by sqlx-postgres engine).
    let _ = &w.rel_5;
    if let Some(group) = &w.and {
        for sub in group {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("(");
            if !push_entity26_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
    }
    if let Some(group) = &w.or {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("(");
        let mut first = true;
        for sub in group {
            if !first {
                qb.push(" OR ");
            }
            first = false;
            qb.push("(");
            if !push_entity26_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
        qb.push(")");
    }
    if let Some(group) = &w.not {
        for sub in group {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT (");
            if !push_entity26_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
    }
    any
}

impl crate::m_06_stress::Entity26 {
    pub async fn find_unique<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity26WhereUniqueInput,
    ) -> sqlx::Result<Option<Self>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let cols = "\"id\", \"rel_fk_id_1\", \"field_1\", \"rel_fk_id_3\", \"field_2\", \"created_at\", \"updated_at\"";
        let mut qb =
            sqlx::QueryBuilder::new(format!(r#"SELECT {} FROM "table_entity26" WHERE "#, cols,));
        // For v1, support only the @id field. Composite uniques are out of scope.
        // The WhereUniqueInput has Option<T> per @id/@unique field; we pick the
        // first Some(). Multi-Some inputs cover composite uniques — TODO Task v2.
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(value.clone());
        } else {
            return Ok(None);
        }
        qb.build_query_as::<Self>().fetch_optional(executor).await
    }
}

impl crate::m_06_stress::Entity26 {
    pub async fn find_first<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity26WhereInput,
    ) -> sqlx::Result<Option<Self>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT "id", "rel_fk_id_1", "field_1", "rel_fk_id_3", "field_2", "created_at", "updated_at" FROM "table_entity26" WHERE "#,
        );
        if !crate::engine::sqlx_postgres::m_06_stress::push_entity26_where(&mut qb, w) {
            qb.push("TRUE");
        }
        qb.push(" LIMIT 1");
        qb.build_query_as::<Self>().fetch_optional(executor).await
    }
}

pub struct Entity26FindManyBuilder<'a, E> {
    executor: E,
    where_input: &'a crate::m_06_stress::Entity26WhereInput,
    order_by: Vec<crate::m_06_stress::Entity26OrderByWithRelationInput>,
    take: Option<i64>,
    skip: Option<i64>,
}

impl<'a, E> Entity26FindManyBuilder<'a, E> {
    pub fn order_by(
        mut self,
        order_by: &[crate::m_06_stress::Entity26OrderByWithRelationInput],
    ) -> Self {
        self.order_by = order_by.to_vec();
        self
    }

    pub fn take(mut self, n: i64) -> Self {
        self.take = Some(n);
        self
    }

    pub fn skip(mut self, n: i64) -> Self {
        self.skip = Some(n);
        self
    }

    pub async fn exec<'e>(self) -> sqlx::Result<Vec<crate::m_06_stress::Entity26>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT "id", "rel_fk_id_1", "field_1", "rel_fk_id_3", "field_2", "created_at", "updated_at" FROM "table_entity26" WHERE "#,
        );
        if !crate::engine::sqlx_postgres::m_06_stress::push_entity26_where(
            &mut qb,
            self.where_input,
        ) {
            qb.push("TRUE");
        }
        if !self.order_by.is_empty() {
            qb.push(" ORDER BY ");
            let mut first = true;
            for ob in &self.order_by {
                if let Some(o) = ob.id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.rel_fk_id_1 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"rel_fk_id_1\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.field_1 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"field_1\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.rel_fk_id_3 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"rel_fk_id_3\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.field_2 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"field_2\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.created_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"created_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.updated_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"updated_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                // TODO(prisma-rust-generator): sorting by relation `rel_1` not yet supported.
                let _ = &ob.rel_1;
                // TODO(prisma-rust-generator): sorting by relation `rel_2` not yet supported.
                let _ = &ob.rel_2;
                // TODO(prisma-rust-generator): sorting by relation `rel_3` not yet supported.
                let _ = &ob.rel_3;
                // TODO(prisma-rust-generator): sorting by relation `rel_4` not yet supported.
                let _ = &ob.rel_4;
                // TODO(prisma-rust-generator): sorting by relation `rel_5` not yet supported.
                let _ = &ob.rel_5;
            }
        }
        if let Some(n) = self.take {
            qb.push(" LIMIT ");
            qb.push_bind(n);
        }
        if let Some(n) = self.skip {
            qb.push(" OFFSET ");
            qb.push_bind(n);
        }
        qb.build_query_as::<crate::m_06_stress::Entity26>()
            .fetch_all(self.executor)
            .await
    }
}

impl crate::m_06_stress::Entity26 {
    pub fn find_many<'a, E>(
        executor: E,
        w: &'a crate::m_06_stress::Entity26WhereInput,
    ) -> Entity26FindManyBuilder<'a, E> {
        Entity26FindManyBuilder {
            executor,
            where_input: w,
            order_by: Vec::new(),
            take: None,
            skip: None,
        }
    }
}

impl crate::m_06_stress::Entity26 {
    pub async fn count<'e, E>(
        executor: E,
        w: Option<&crate::m_06_stress::Entity26WhereInput>,
    ) -> sqlx::Result<i64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"SELECT COUNT(*) FROM "table_entity26" WHERE "#);
        if let Some(w) = w {
            if !crate::engine::sqlx_postgres::m_06_stress::push_entity26_where(&mut qb, w) {
                qb.push("TRUE");
            }
        } else {
            qb.push("TRUE");
        }
        let row = qb.build_query_as::<(i64,)>().fetch_one(executor).await?;
        Ok(row.0)
    }
}

impl crate::m_06_stress::Entity26 {
    pub async fn create<'e, E>(
        executor: E,
        input: crate::m_06_stress::Entity26UncheckedCreateInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut cols = String::new();
        cols.push_str("\"rel_fk_id_1\"");
        cols.push_str(", ");
        cols.push_str("\"field_1\"");
        cols.push_str(", ");
        cols.push_str("\"rel_fk_id_3\"");
        let mut qb = sqlx::QueryBuilder::new(format!(
            r#"INSERT INTO "table_entity26" ({}) VALUES ("#,
            cols,
        ));
        qb.push_bind(input.rel_fk_id_1);
        qb.push(", ");
        qb.push_bind(input.field_1);
        qb.push(", ");
        qb.push_bind(input.rel_fk_id_3);
        qb.push(r#") RETURNING "id", "rel_fk_id_1", "field_1", "rel_fk_id_3", "field_2", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::m_06_stress::Entity26 {
    pub async fn create_many<'e, E>(
        executor: E,
        inputs: &[crate::m_06_stress::Entity26UncheckedCreateInput],
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        if inputs.is_empty() {
            return Ok(0);
        }
        let mut qb = sqlx::QueryBuilder::new(
            r#"INSERT INTO "table_entity26" ("rel_fk_id_1", "field_1", "rel_fk_id_3") "#,
        );
        qb.push_values(inputs, |mut row, input| {
            row.push_bind(input.rel_fk_id_1.clone());
            row.push_bind(input.field_1.clone());
            row.push_bind(input.rel_fk_id_3.clone());
        });
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

impl crate::m_06_stress::Entity26 {
    pub async fn update<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity26WhereUniqueInput,
        input: crate::m_06_stress::Entity26UncheckedUpdateInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"UPDATE "table_entity26" SET "#);
        let mut first = true;
        if let Some(op) = input.id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_1 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_1\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_1 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_1\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_3 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_3\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_2 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_2\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.created_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"created_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.updated_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"updated_at\" = ");
                qb.push_bind(v);
            }
        }
        if first {
            // Nothing to update — fall back to a plain find_unique so the
            // caller still gets the row back (or RowNotFound if absent).
            return Self::find_unique(executor, w)
                .await?
                .ok_or(sqlx::Error::RowNotFound);
        }
        qb.push(" WHERE ");
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(value.clone());
        } else {
            return Err(sqlx::Error::RowNotFound);
        }
        qb.push(r#" RETURNING "id", "rel_fk_id_1", "field_1", "rel_fk_id_3", "field_2", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::m_06_stress::Entity26 {
    pub async fn update_many<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity26WhereInput,
        input: crate::m_06_stress::Entity26UncheckedUpdateManyInput,
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"UPDATE "table_entity26" SET "#);
        let mut first = true;
        if let Some(op) = input.id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_1 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_1\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_1 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_1\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_3 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_3\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_2 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_2\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.created_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"created_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.updated_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"updated_at\" = ");
                qb.push_bind(v);
            }
        }
        if first {
            // No-op update — return 0 rows affected without issuing SQL.
            return Ok(0);
        }
        qb.push(" WHERE ");
        if !crate::engine::sqlx_postgres::m_06_stress::push_entity26_where(&mut qb, w) {
            qb.push("TRUE");
        }
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

impl crate::m_06_stress::Entity26 {
    pub async fn delete<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity26WhereUniqueInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"DELETE FROM "table_entity26" WHERE "#);
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(value.clone());
        } else {
            return Err(sqlx::Error::RowNotFound);
        }
        qb.push(r#" RETURNING "id", "rel_fk_id_1", "field_1", "rel_fk_id_3", "field_2", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::m_06_stress::Entity26 {
    pub async fn delete_many<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity26WhereInput,
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"DELETE FROM "table_entity26" WHERE "#);
        if !crate::engine::sqlx_postgres::m_06_stress::push_entity26_where(&mut qb, w) {
            qb.push("TRUE");
        }
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity26CountAggregateResult {
    pub id: Option<i64>,
    pub rel_fk_id_1: Option<i64>,
    pub field_1: Option<i64>,
    pub rel_fk_id_3: Option<i64>,
    pub field_2: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<i64>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity26AvgAggregateResult {}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity26SumAggregateResult {}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity26MinAggregateResult {
    pub id: Option<String>,
    pub rel_fk_id_1: Option<String>,
    pub rel_fk_id_3: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity26MaxAggregateResult {
    pub id: Option<String>,
    pub rel_fk_id_1: Option<String>,
    pub rel_fk_id_3: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity26AggregateResult {
    #[serde(rename = "_count")]
    pub aggregate_count: Option<Entity26CountAggregateResult>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<Entity26AvgAggregateResult>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<Entity26SumAggregateResult>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<Entity26MinAggregateResult>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<Entity26MaxAggregateResult>,
}

impl crate::m_06_stress::Entity26 {
    pub async fn aggregate<'e, E>(
        executor: E,
        input: &crate::m_06_stress::Entity26AggregateInput,
    ) -> sqlx::Result<Entity26AggregateResult>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT COUNT(*) AS count_all, COUNT("id") AS count_id, COUNT("rel_fk_id_1") AS count_rel_fk_id_1, COUNT("field_1") AS count_field_1, COUNT("rel_fk_id_3") AS count_rel_fk_id_3, COUNT("field_2") AS count_field_2, COUNT("created_at") AS count_created_at, COUNT("updated_at") AS count_updated_at, MIN("id") AS min_id, MAX("id") AS max_id, MIN("rel_fk_id_1") AS min_rel_fk_id_1, MAX("rel_fk_id_1") AS max_rel_fk_id_1, MIN("rel_fk_id_3") AS min_rel_fk_id_3, MAX("rel_fk_id_3") AS max_rel_fk_id_3, MIN("created_at") AS min_created_at, MAX("created_at") AS max_created_at, MIN("updated_at") AS min_updated_at, MAX("updated_at") AS max_updated_at FROM "table_entity26" WHERE "#,
        );
        if let Some(w) = &input.r#where {
            if !crate::engine::sqlx_postgres::m_06_stress::push_entity26_where(&mut qb, w) {
                qb.push("TRUE");
            }
        } else {
            qb.push("TRUE");
        }
        let row = qb.build().fetch_one(executor).await?;
        use sqlx::Row;
        Ok(Entity26AggregateResult {
            aggregate_count: input
                .aggregate_count
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(Entity26CountAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_id")?
                        } else {
                            None
                        },
                        rel_fk_id_1: if req.rel_fk_id_1.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_rel_fk_id_1")?
                        } else {
                            None
                        },
                        field_1: if req.field_1.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_field_1")?
                        } else {
                            None
                        },
                        rel_fk_id_3: if req.rel_fk_id_3.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_rel_fk_id_3")?
                        } else {
                            None
                        },
                        field_2: if req.field_2.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_field_2")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_created_at")?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_updated_at")?
                        } else {
                            None
                        },
                        aggregate_all: if req.aggregate_all.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_all")?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_avg: input
                .aggregate_avg
                .as_ref()
                .map(|_req| -> sqlx::Result<_> { Ok(Entity26AvgAggregateResult {}) })
                .transpose()?,
            aggregate_sum: input
                .aggregate_sum
                .as_ref()
                .map(|_req| -> sqlx::Result<_> { Ok(Entity26SumAggregateResult {}) })
                .transpose()?,
            aggregate_min: input
                .aggregate_min
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(Entity26MinAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_id")?
                        } else {
                            None
                        },
                        rel_fk_id_1: if req.rel_fk_id_1.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_rel_fk_id_1")?
                        } else {
                            None
                        },
                        rel_fk_id_3: if req.rel_fk_id_3.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_rel_fk_id_3")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_created_at",
                            )?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_updated_at",
                            )?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_max: input
                .aggregate_max
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(Entity26MaxAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_id")?
                        } else {
                            None
                        },
                        rel_fk_id_1: if req.rel_fk_id_1.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_rel_fk_id_1")?
                        } else {
                            None
                        },
                        rel_fk_id_3: if req.rel_fk_id_3.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_rel_fk_id_3")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_created_at",
                            )?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_updated_at",
                            )?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
        })
    }
}

impl sqlx::FromRow<'_, sqlx::postgres::PgRow> for crate::m_06_stress::Entity27 {
    fn from_row(row: &sqlx::postgres::PgRow) -> sqlx::Result<Self> {
        Ok(crate::m_06_stress::Entity27 {
            id: row.try_get("id")?,
            rel_fk_id_1: row.try_get("rel_fk_id_1")?,
            rel_fk_id_2: row.try_get("rel_fk_id_2")?,
            rel_fk_id_3: row.try_get("rel_fk_id_3")?,
            field_1: row.try_get("field_1")?,
            field_2: row.try_get("field_2")?,
            field_3: row.try_get("field_3")?,
            field_4: row.try_get("field_4")?,
            created_at: row.try_get("created_at")?,
            updated_at: row.try_get("updated_at")?,
            rel_1: None,
            rel_2: None,
            rel_3: None,
        })
    }
}

pub(crate) fn push_entity27_where(
    qb: &mut sqlx::QueryBuilder<'_, sqlx::Postgres>,
    w: &crate::m_06_stress::Entity27WhereInput,
) -> bool {
    let mut any = false;
    if let Some(f) = &w.id {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_int_filter(qb, "id", f);
    }
    if let Some(f) = &w.rel_fk_id_1 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "rel_fk_id_1", f);
    }
    if let Some(f) = &w.rel_fk_id_2 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "rel_fk_id_2", f);
    }
    if let Some(f) = &w.rel_fk_id_3 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_filter(qb, "rel_fk_id_3", f);
    }
    if let Some(f) = &w.field_1 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_enum6_filter(qb, "field_1", f);
    }
    if let Some(f) = &w.field_2 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_nullable_filter(qb, "field_2", f);
    }
    if let Some(f) = &w.field_3 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_nullable_filter(qb, "field_3", f);
    }
    if let Some(f) = &w.field_4 {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_string_nullable_filter(qb, "field_4", f);
    }
    if let Some(f) = &w.created_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_filter(qb, "created_at", f);
    }
    if let Some(f) = &w.updated_at {
        if any {
            qb.push(" AND ");
        }
        any = true;
        crate::engine::sqlx_postgres::filters::push_datetime_filter(qb, "updated_at", f);
    }
    if let Some(rel) = &w.rel_1 {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"table_entity26\" t WHERE t.\"id\" = \"table_entity27\".\"rel_fk_id_1\" AND (");
            if !crate::engine::sqlx_postgres::m_06_stress::push_entity26_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity26\" t WHERE t.\"id\" = \"table_entity27\".\"rel_fk_id_1\" AND (");
            if !crate::engine::sqlx_postgres::m_06_stress::push_entity26_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.rel_2 {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"table_entity19\" t WHERE t.\"id\" = \"table_entity27\".\"rel_fk_id_2\" AND (");
            if !crate::engine::sqlx_postgres::m_05_stress::push_entity19_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity19\" t WHERE t.\"id\" = \"table_entity27\".\"rel_fk_id_2\" AND (");
            if !crate::engine::sqlx_postgres::m_05_stress::push_entity19_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(rel) = &w.rel_3 {
        if let Some(sub) = &rel.is {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("EXISTS (SELECT 1 FROM \"table_entity37\" t WHERE t.\"id\" = \"table_entity27\".\"rel_fk_id_3\" AND (");
            if !crate::engine::sqlx_postgres::m_09_stress::push_entity37_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
        if let Some(sub) = &rel.is_not {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT EXISTS (SELECT 1 FROM \"table_entity37\" t WHERE t.\"id\" = \"table_entity27\".\"rel_fk_id_3\" AND (");
            if !crate::engine::sqlx_postgres::m_09_stress::push_entity37_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push("))");
        }
    }
    if let Some(group) = &w.and {
        for sub in group {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("(");
            if !push_entity27_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
    }
    if let Some(group) = &w.or {
        if any {
            qb.push(" AND ");
        }
        any = true;
        qb.push("(");
        let mut first = true;
        for sub in group {
            if !first {
                qb.push(" OR ");
            }
            first = false;
            qb.push("(");
            if !push_entity27_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
        qb.push(")");
    }
    if let Some(group) = &w.not {
        for sub in group {
            if any {
                qb.push(" AND ");
            }
            any = true;
            qb.push("NOT (");
            if !push_entity27_where(qb, sub) {
                qb.push("TRUE");
            }
            qb.push(")");
        }
    }
    any
}

impl crate::m_06_stress::Entity27 {
    pub async fn find_unique<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity27WhereUniqueInput,
    ) -> sqlx::Result<Option<Self>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let cols = "\"id\", \"rel_fk_id_1\", \"rel_fk_id_2\", \"rel_fk_id_3\", \"field_1\", \"field_2\", \"field_3\", \"field_4\", \"created_at\", \"updated_at\"";
        let mut qb =
            sqlx::QueryBuilder::new(format!(r#"SELECT {} FROM "table_entity27" WHERE "#, cols,));
        // For v1, support only the @id field. Composite uniques are out of scope.
        // The WhereUniqueInput has Option<T> per @id/@unique field; we pick the
        // first Some(). Multi-Some inputs cover composite uniques — TODO Task v2.
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(*value);
        } else {
            return Ok(None);
        }
        qb.build_query_as::<Self>().fetch_optional(executor).await
    }
}

impl crate::m_06_stress::Entity27 {
    pub async fn find_first<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity27WhereInput,
    ) -> sqlx::Result<Option<Self>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT "id", "rel_fk_id_1", "rel_fk_id_2", "rel_fk_id_3", "field_1", "field_2", "field_3", "field_4", "created_at", "updated_at" FROM "table_entity27" WHERE "#,
        );
        if !crate::engine::sqlx_postgres::m_06_stress::push_entity27_where(&mut qb, w) {
            qb.push("TRUE");
        }
        qb.push(" LIMIT 1");
        qb.build_query_as::<Self>().fetch_optional(executor).await
    }
}

pub struct Entity27FindManyBuilder<'a, E> {
    executor: E,
    where_input: &'a crate::m_06_stress::Entity27WhereInput,
    order_by: Vec<crate::m_06_stress::Entity27OrderByWithRelationInput>,
    take: Option<i64>,
    skip: Option<i64>,
}

impl<'a, E> Entity27FindManyBuilder<'a, E> {
    pub fn order_by(
        mut self,
        order_by: &[crate::m_06_stress::Entity27OrderByWithRelationInput],
    ) -> Self {
        self.order_by = order_by.to_vec();
        self
    }

    pub fn take(mut self, n: i64) -> Self {
        self.take = Some(n);
        self
    }

    pub fn skip(mut self, n: i64) -> Self {
        self.skip = Some(n);
        self
    }

    pub async fn exec<'e>(self) -> sqlx::Result<Vec<crate::m_06_stress::Entity27>>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT "id", "rel_fk_id_1", "rel_fk_id_2", "rel_fk_id_3", "field_1", "field_2", "field_3", "field_4", "created_at", "updated_at" FROM "table_entity27" WHERE "#,
        );
        if !crate::engine::sqlx_postgres::m_06_stress::push_entity27_where(
            &mut qb,
            self.where_input,
        ) {
            qb.push("TRUE");
        }
        if !self.order_by.is_empty() {
            qb.push(" ORDER BY ");
            let mut first = true;
            for ob in &self.order_by {
                if let Some(o) = ob.id {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"id\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.rel_fk_id_1 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"rel_fk_id_1\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.rel_fk_id_2 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"rel_fk_id_2\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.rel_fk_id_3 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"rel_fk_id_3\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.field_1 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"field_1\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.field_2 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"field_2\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.field_3 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"field_3\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.field_4 {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"field_4\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.created_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"created_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                if let Some(o) = ob.updated_at {
                    if !first {
                        qb.push(", ");
                    }
                    first = false;
                    qb.push("\"updated_at\" ");
                    qb.push(crate::engine::sqlx_postgres::filters::sort_order_sql(o));
                }
                // TODO(prisma-rust-generator): sorting by relation `rel_1` not yet supported.
                let _ = &ob.rel_1;
                // TODO(prisma-rust-generator): sorting by relation `rel_2` not yet supported.
                let _ = &ob.rel_2;
                // TODO(prisma-rust-generator): sorting by relation `rel_3` not yet supported.
                let _ = &ob.rel_3;
            }
        }
        if let Some(n) = self.take {
            qb.push(" LIMIT ");
            qb.push_bind(n);
        }
        if let Some(n) = self.skip {
            qb.push(" OFFSET ");
            qb.push_bind(n);
        }
        qb.build_query_as::<crate::m_06_stress::Entity27>()
            .fetch_all(self.executor)
            .await
    }
}

impl crate::m_06_stress::Entity27 {
    pub fn find_many<'a, E>(
        executor: E,
        w: &'a crate::m_06_stress::Entity27WhereInput,
    ) -> Entity27FindManyBuilder<'a, E> {
        Entity27FindManyBuilder {
            executor,
            where_input: w,
            order_by: Vec::new(),
            take: None,
            skip: None,
        }
    }
}

impl crate::m_06_stress::Entity27 {
    pub async fn count<'e, E>(
        executor: E,
        w: Option<&crate::m_06_stress::Entity27WhereInput>,
    ) -> sqlx::Result<i64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"SELECT COUNT(*) FROM "table_entity27" WHERE "#);
        if let Some(w) = w {
            if !crate::engine::sqlx_postgres::m_06_stress::push_entity27_where(&mut qb, w) {
                qb.push("TRUE");
            }
        } else {
            qb.push("TRUE");
        }
        let row = qb.build_query_as::<(i64,)>().fetch_one(executor).await?;
        Ok(row.0)
    }
}

impl crate::m_06_stress::Entity27 {
    pub async fn create<'e, E>(
        executor: E,
        input: crate::m_06_stress::Entity27UncheckedCreateInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut cols = String::new();
        cols.push_str("\"rel_fk_id_1\"");
        cols.push_str(", ");
        cols.push_str("\"rel_fk_id_2\"");
        cols.push_str(", ");
        cols.push_str("\"rel_fk_id_3\"");
        if input.field_3.is_some() {
            cols.push_str(", ");
            cols.push_str("\"field_3\"");
        }
        if input.field_4.is_some() {
            cols.push_str(", ");
            cols.push_str("\"field_4\"");
        }
        let mut qb = sqlx::QueryBuilder::new(format!(
            r#"INSERT INTO "table_entity27" ({}) VALUES ("#,
            cols,
        ));
        qb.push_bind(input.rel_fk_id_1);
        qb.push(", ");
        qb.push_bind(input.rel_fk_id_2);
        qb.push(", ");
        qb.push_bind(input.rel_fk_id_3);
        if let Some(v) = input.field_3 {
            qb.push(", ");
            qb.push_bind(v);
        }
        if let Some(v) = input.field_4 {
            qb.push(", ");
            qb.push_bind(v);
        }
        qb.push(r#") RETURNING "id", "rel_fk_id_1", "rel_fk_id_2", "rel_fk_id_3", "field_1", "field_2", "field_3", "field_4", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::m_06_stress::Entity27 {
    pub async fn create_many<'e, E>(
        executor: E,
        inputs: &[crate::m_06_stress::Entity27UncheckedCreateInput],
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        if inputs.is_empty() {
            return Ok(0);
        }
        let mut qb = sqlx::QueryBuilder::new(
            r#"INSERT INTO "table_entity27" ("rel_fk_id_1", "rel_fk_id_2", "rel_fk_id_3", "field_3", "field_4") "#,
        );
        qb.push_values(inputs, |mut row, input| {
            row.push_bind(input.rel_fk_id_1.clone());
            row.push_bind(input.rel_fk_id_2.clone());
            row.push_bind(input.rel_fk_id_3.clone());
            row.push_bind(input.field_3);
            row.push_bind(input.field_4.clone());
        });
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

impl crate::m_06_stress::Entity27 {
    pub async fn update<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity27WhereUniqueInput,
        input: crate::m_06_stress::Entity27UncheckedUpdateInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"UPDATE "table_entity27" SET "#);
        let mut first = true;
        if let Some(op) = input.id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = ");
                qb.push_bind(v);
            }
            if let Some(v) = op.increment {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" + ");
                qb.push_bind(v);
            }
            if let Some(v) = op.decrement {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" - ");
                qb.push_bind(v);
            }
            if let Some(v) = op.multiply {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" * ");
                qb.push_bind(v);
            }
            if let Some(v) = op.divide {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" / ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_1 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_1\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_2 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_2\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_3 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_3\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_1 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_1\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_2 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_2\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_3 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_3\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_4 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_4\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.created_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"created_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.updated_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"updated_at\" = ");
                qb.push_bind(v);
            }
        }
        if first {
            // Nothing to update — fall back to a plain find_unique so the
            // caller still gets the row back (or RowNotFound if absent).
            return Self::find_unique(executor, w)
                .await?
                .ok_or(sqlx::Error::RowNotFound);
        }
        qb.push(" WHERE ");
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(*value);
        } else {
            return Err(sqlx::Error::RowNotFound);
        }
        qb.push(r#" RETURNING "id", "rel_fk_id_1", "rel_fk_id_2", "rel_fk_id_3", "field_1", "field_2", "field_3", "field_4", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::m_06_stress::Entity27 {
    pub async fn update_many<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity27WhereInput,
        input: crate::m_06_stress::Entity27UncheckedUpdateManyInput,
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"UPDATE "table_entity27" SET "#);
        let mut first = true;
        if let Some(op) = input.id {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = ");
                qb.push_bind(v);
            }
            if let Some(v) = op.increment {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" + ");
                qb.push_bind(v);
            }
            if let Some(v) = op.decrement {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" - ");
                qb.push_bind(v);
            }
            if let Some(v) = op.multiply {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" * ");
                qb.push_bind(v);
            }
            if let Some(v) = op.divide {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"id\" = \"id\" / ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_1 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_1\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_2 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_2\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.rel_fk_id_3 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"rel_fk_id_3\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_1 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_1\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_2 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_2\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_3 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_3\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.field_4 {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"field_4\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.created_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"created_at\" = ");
                qb.push_bind(v);
            }
        }
        if let Some(op) = input.updated_at {
            if let Some(v) = op.set {
                if !first {
                    qb.push(", ");
                }
                first = false;
                qb.push("\"updated_at\" = ");
                qb.push_bind(v);
            }
        }
        if first {
            // No-op update — return 0 rows affected without issuing SQL.
            return Ok(0);
        }
        qb.push(" WHERE ");
        if !crate::engine::sqlx_postgres::m_06_stress::push_entity27_where(&mut qb, w) {
            qb.push("TRUE");
        }
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

impl crate::m_06_stress::Entity27 {
    pub async fn delete<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity27WhereUniqueInput,
    ) -> sqlx::Result<Self>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"DELETE FROM "table_entity27" WHERE "#);
        if let Some(value) = &w.id {
            qb.push("\"id\" = ");
            qb.push_bind(*value);
        } else {
            return Err(sqlx::Error::RowNotFound);
        }
        qb.push(r#" RETURNING "id", "rel_fk_id_1", "rel_fk_id_2", "rel_fk_id_3", "field_1", "field_2", "field_3", "field_4", "created_at", "updated_at""#);
        qb.build_query_as::<Self>().fetch_one(executor).await
    }
}

impl crate::m_06_stress::Entity27 {
    pub async fn delete_many<'e, E>(
        executor: E,
        w: &crate::m_06_stress::Entity27WhereInput,
    ) -> sqlx::Result<u64>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(r#"DELETE FROM "table_entity27" WHERE "#);
        if !crate::engine::sqlx_postgres::m_06_stress::push_entity27_where(&mut qb, w) {
            qb.push("TRUE");
        }
        let result = qb.build().execute(executor).await?;
        Ok(result.rows_affected())
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity27CountAggregateResult {
    pub id: Option<i64>,
    pub rel_fk_id_1: Option<i64>,
    pub rel_fk_id_2: Option<i64>,
    pub rel_fk_id_3: Option<i64>,
    pub field_1: Option<i64>,
    pub field_2: Option<i64>,
    pub field_3: Option<i64>,
    pub field_4: Option<i64>,
    pub created_at: Option<i64>,
    pub updated_at: Option<i64>,
    #[serde(rename = "_all")]
    pub aggregate_all: Option<i64>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity27AvgAggregateResult {
    pub id: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity27SumAggregateResult {
    pub id: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity27MinAggregateResult {
    pub id: Option<i32>,
    pub rel_fk_id_1: Option<String>,
    pub rel_fk_id_2: Option<String>,
    pub rel_fk_id_3: Option<String>,
    pub field_2: Option<chrono::DateTime<chrono::Utc>>,
    pub field_3: Option<chrono::DateTime<chrono::Utc>>,
    pub field_4: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity27MaxAggregateResult {
    pub id: Option<i32>,
    pub rel_fk_id_1: Option<String>,
    pub rel_fk_id_2: Option<String>,
    pub rel_fk_id_3: Option<String>,
    pub field_2: Option<chrono::DateTime<chrono::Utc>>,
    pub field_3: Option<chrono::DateTime<chrono::Utc>>,
    pub field_4: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entity27AggregateResult {
    #[serde(rename = "_count")]
    pub aggregate_count: Option<Entity27CountAggregateResult>,
    #[serde(rename = "_avg")]
    pub aggregate_avg: Option<Entity27AvgAggregateResult>,
    #[serde(rename = "_sum")]
    pub aggregate_sum: Option<Entity27SumAggregateResult>,
    #[serde(rename = "_min")]
    pub aggregate_min: Option<Entity27MinAggregateResult>,
    #[serde(rename = "_max")]
    pub aggregate_max: Option<Entity27MaxAggregateResult>,
}

impl crate::m_06_stress::Entity27 {
    pub async fn aggregate<'e, E>(
        executor: E,
        input: &crate::m_06_stress::Entity27AggregateInput,
    ) -> sqlx::Result<Entity27AggregateResult>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let mut qb = sqlx::QueryBuilder::new(
            r#"SELECT COUNT(*) AS count_all, COUNT("id") AS count_id, COUNT("rel_fk_id_1") AS count_rel_fk_id_1, COUNT("rel_fk_id_2") AS count_rel_fk_id_2, COUNT("rel_fk_id_3") AS count_rel_fk_id_3, COUNT("field_1") AS count_field_1, COUNT("field_2") AS count_field_2, COUNT("field_3") AS count_field_3, COUNT("field_4") AS count_field_4, COUNT("created_at") AS count_created_at, COUNT("updated_at") AS count_updated_at, AVG("id")::double precision AS avg_id, SUM("id")::double precision AS sum_id, MIN("id") AS min_id, MAX("id") AS max_id, MIN("rel_fk_id_1") AS min_rel_fk_id_1, MAX("rel_fk_id_1") AS max_rel_fk_id_1, MIN("rel_fk_id_2") AS min_rel_fk_id_2, MAX("rel_fk_id_2") AS max_rel_fk_id_2, MIN("rel_fk_id_3") AS min_rel_fk_id_3, MAX("rel_fk_id_3") AS max_rel_fk_id_3, MIN("field_2") AS min_field_2, MAX("field_2") AS max_field_2, MIN("field_3") AS min_field_3, MAX("field_3") AS max_field_3, MIN("field_4") AS min_field_4, MAX("field_4") AS max_field_4, MIN("created_at") AS min_created_at, MAX("created_at") AS max_created_at, MIN("updated_at") AS min_updated_at, MAX("updated_at") AS max_updated_at FROM "table_entity27" WHERE "#,
        );
        if let Some(w) = &input.r#where {
            if !crate::engine::sqlx_postgres::m_06_stress::push_entity27_where(&mut qb, w) {
                qb.push("TRUE");
            }
        } else {
            qb.push("TRUE");
        }
        let row = qb.build().fetch_one(executor).await?;
        use sqlx::Row;
        Ok(Entity27AggregateResult {
            aggregate_count: input
                .aggregate_count
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(Entity27CountAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_id")?
                        } else {
                            None
                        },
                        rel_fk_id_1: if req.rel_fk_id_1.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_rel_fk_id_1")?
                        } else {
                            None
                        },
                        rel_fk_id_2: if req.rel_fk_id_2.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_rel_fk_id_2")?
                        } else {
                            None
                        },
                        rel_fk_id_3: if req.rel_fk_id_3.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_rel_fk_id_3")?
                        } else {
                            None
                        },
                        field_1: if req.field_1.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_field_1")?
                        } else {
                            None
                        },
                        field_2: if req.field_2.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_field_2")?
                        } else {
                            None
                        },
                        field_3: if req.field_3.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_field_3")?
                        } else {
                            None
                        },
                        field_4: if req.field_4.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_field_4")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_created_at")?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_updated_at")?
                        } else {
                            None
                        },
                        aggregate_all: if req.aggregate_all.unwrap_or(false) {
                            row.try_get::<Option<i64>, _>("count_all")?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_avg: input
                .aggregate_avg
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(Entity27AvgAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<f64>, _>("avg_id")?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_sum: input
                .aggregate_sum
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(Entity27SumAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<f64>, _>("sum_id")?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_min: input
                .aggregate_min
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(Entity27MinAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<i32>, _>("min_id")?
                        } else {
                            None
                        },
                        rel_fk_id_1: if req.rel_fk_id_1.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_rel_fk_id_1")?
                        } else {
                            None
                        },
                        rel_fk_id_2: if req.rel_fk_id_2.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_rel_fk_id_2")?
                        } else {
                            None
                        },
                        rel_fk_id_3: if req.rel_fk_id_3.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_rel_fk_id_3")?
                        } else {
                            None
                        },
                        field_2: if req.field_2.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>("min_field_2")?
                        } else {
                            None
                        },
                        field_3: if req.field_3.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>("min_field_3")?
                        } else {
                            None
                        },
                        field_4: if req.field_4.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("min_field_4")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_created_at",
                            )?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "min_updated_at",
                            )?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
            aggregate_max: input
                .aggregate_max
                .as_ref()
                .map(|req| -> sqlx::Result<_> {
                    Ok(Entity27MaxAggregateResult {
                        id: if req.id.unwrap_or(false) {
                            row.try_get::<Option<i32>, _>("max_id")?
                        } else {
                            None
                        },
                        rel_fk_id_1: if req.rel_fk_id_1.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_rel_fk_id_1")?
                        } else {
                            None
                        },
                        rel_fk_id_2: if req.rel_fk_id_2.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_rel_fk_id_2")?
                        } else {
                            None
                        },
                        rel_fk_id_3: if req.rel_fk_id_3.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_rel_fk_id_3")?
                        } else {
                            None
                        },
                        field_2: if req.field_2.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>("max_field_2")?
                        } else {
                            None
                        },
                        field_3: if req.field_3.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>("max_field_3")?
                        } else {
                            None
                        },
                        field_4: if req.field_4.unwrap_or(false) {
                            row.try_get::<Option<String>, _>("max_field_4")?
                        } else {
                            None
                        },
                        created_at: if req.created_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_created_at",
                            )?
                        } else {
                            None
                        },
                        updated_at: if req.updated_at.unwrap_or(false) {
                            row.try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(
                                "max_updated_at",
                            )?
                        } else {
                            None
                        },
                    })
                })
                .transpose()?,
        })
    }
}
