import { readdir, readFile, unlink } from "node:fs/promises";
import { join, relative } from "node:path";

const MARKER = "@generated by prisma-rust-generator";

export async function pruneStaleFiles(
  rootDir: string,
  keepRelativePaths: ReadonlySet<string>,
): Promise<void> {
  for await (const abs of walk(rootDir)) {
    if (!abs.endsWith(".rs")) continue;
    const rel = relative(rootDir, abs);
    if (keepRelativePaths.has(rel)) continue;
    const head = await readFirstLine(abs);
    if (head.includes(MARKER)) await unlink(abs);
  }
}

async function* walk(dir: string): AsyncIterable<string> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) yield* walk(full);
    else if (e.isFile()) yield full;
  }
}

async function readFirstLine(file: string): Promise<string> {
  const text = await readFile(file, "utf8");
  const nl = text.indexOf("\n");
  return nl === -1 ? text : text.slice(0, nl);
}
