export const GENERATED_MARKER =
  "// @generated by prisma-rust-generator — do not edit by hand";

export interface HeaderOpts {
  filePreamble: string;
  clippyAllowList: readonly string[];
}

export function emitFileHeader(opts: HeaderOpts): string {
  const parts: string[] = [GENERATED_MARKER];
  if (opts.filePreamble.length > 0) parts.push(opts.filePreamble.trimEnd());
  if (opts.clippyAllowList.length > 0) {
    parts.push(`#![allow(${opts.clippyAllowList.join(", ")})]`);
  }
  parts.push("");
  return parts.join("\n");
}
